### ISSUE TITLE
Make downloadable release

### ISSUE THREAD

**Issue by sanitas2** [insites/cookieconsent#104]
I'd like to download whole project and have it self hosted. If there is already such possibility, please update the documentation.

**Comment by welove** [comment]
Agreed, Google Page Insights gives me a lower score because i'm loading external javascripts...

**Comment by alexmorleyfinch** [comment]
You'd need to download the build files. In CookieConsent V2, visit the `build` folder. You need to select the javascript file `cookieconsent.min.js` and which ever theme you are using. If using CookieConsent V3, 
visit the `build` folder and use both the `cookieconsent.min.js` and `cookieconsent.min.css` files.

Upload these files to your server, and then modify your html files to point to the files on your server.
