### ISSUE TITLE
Feature request: Execute plugin only programmatically, not on page load

### ISSUE THREAD

**Issue by GSPP** [insites/cookieconsent#106]
I'd like to be able to set the plugin to a mode where it does nothing by default. I'd then like to execute it programmatically from script.

The use case for this is JavaScript bundling. In my specific case I have a hard time to ensure that my JavaScript runs before cookieconsent.js. That's a problem because I might not be in time to set the options.

The solution would be to set the options from my code and then to programmatically trigger cookieconsent.js processing.

On-the-fly options change does not seem to solve this scenario.

**Comment by saschalalala** [comment]
I also ran into that problem when I wanted to check the visitor's country before executing cookieconsent. I resolved it like this:
https://gist.github.com/saschalalala/18211d261a301dee1142

Then I call 
<code>
cookieconsent_wrapper();
</code>
in the success callback of my location check ajax.

Hope that can help.

**Comment by alexmorleyfinch** [comment]
CookieConsent V2 struggles to do this.

CookieConsent V3 does not run automatically if you pass `autoOpen: false` as an option. Then you can control many aspects of its execution. CookieConsent V3 also has a location feature built into it by default
