### ISSUE TITLE
Events handler on show/hide of the banner ?

### ISSUE THREAD

**Issue by sushicodeur** [insites/cookieconsent#116]
Hello,

is it possible to run custom code when the banner is showing or hiding ? We need to have a class on the body so that our header (in position:fixed) don't get overlapped by the bar and those event would allow us to do that and much more.

Thanks,

**Comment by alexmorleyfinch** [comment]
These callbacks don't exist for CookieConsent V2. However the container is added to the DOM on open and removed on close, so you could technically add and listen for DOM mutation events to the container element.

CookieConsent V3 contains many improvments on V2 and has `onPopupOpen` and `onPopupClose` callbacks.
