### ISSUE TITLE
Make cookie bar only appear once

### ISSUE THREAD

**Issue by dermueller** [insites/cookieconsent#118]
I would like to suggest a new option, so that the cookie bar only appears once, sets its cookie automatically and is therefore never seen again. Currently, it is neccessary to click the "OK" button; if one does not click the button, the bar will appear again and again. I think this might be a legal option, at least for Germany.

**Comment by oliveremberton** [comment]
Agreed, this makes sense. We'll consider it for Cookie Consent v3.

**Comment by alexmorleyfinch** [comment]
CookieConsent V3 contains an option called `dismissOnTimeout` thanks to your suggestion.

This could be set to a value like 3000 milliseconds, which would automatically dismiss the popup after 3 seconds.

If you use the Cookie Law and Location features in V3, then you should know that some countries require a "specific action". E.G. an actual "click".

The `dismissOnTimeout` will automatically be disabled in countries where an "explicit action" is required. (This is a small number of countries [as of now: Croatia, Italy, Spain])

This is also a `dismissOnScroll` which behaves similar to `dismissOnTimeout`
