### ISSUE TITLE
No "head"-tag

### ISSUE THREAD

**Issue by HTML-Loser** [insites/cookieconsent#123]
I have created a website with MOBIRISE and cannot find a head-tag.
Where do I have to insert the copied text so that the cookie-warning will be shown?
Thx in advance.

**Comment by alexmorleyfinch** [comment]
It is not entirely necessary to put the `<script>` tag in the head (although you can if you want). You can also put it at the very bottom of the page.

You must find and edit the HTML of your web page and add the `<script>` tag. Set the source of the script tag to the 'cookieconsent.js' file that is hosted on your server.

E.G.

    <script>
        window.cookieconsent_options = {
            // your configuration options
        };
    </script>
    <script type="text/javascript" src="path/to/your/cookieconsent.js"></script>
