### ISSUE TITLE
Problem Firefox and Chrome - cookieconsent v1

### ISSUE THREAD

**Issue by frafra1985** [insites/cookieconsent#130]
Google ads and Social Icon are not displayed, after the consent, in Firefox 45.01 and Google Chrome 49.02

I use cookieconsent v1, my site is http://www.cittadiferoletoantico.it/website/

**Comment by Dolondro** [comment]
This URL is no longer valid, this isn't the CookieConsent v1 repo, and we've deprecated support for it anyway.
