### ISSUE TITLE
S3 CSS not found

### ISSUE THREAD

**Issue by michelem09** [insites/cookieconsent#134]
Sorry to bother you but this URL is not found `http://s3.amazonaws.com/cc.silktide.com/dark-bottom.css`

**Comment by lluiscanals** [comment]
I've got this error too. I think you are using the wrong version. Have you installed it from bower?

**Comment by michelem09** [comment]
Yes from bower, bower.json reports 1.0.9

**Comment by michelem09** [comment]
I just tried 1.0.10 but it has the same error.

`bower install cookieconsent2#1.0.10`

**Comment by lluiscanals** [comment]
See #127 . I have put cdn in index.html until they resolve this issue.

**Comment by michelem09** [comment]
Thanks I'll do a workaround too.

**Comment by saurabh-parihar** [comment]
Simple solution for this:

Looking at the source code of this plugin, you can see that at line 293 (Line 291 in older file) it is using a parameter "theme" which is used to download the css file. The older code here refers to the broken Amazon cdn via an internal variable "THEME_BUCKET_PATH".

If you check the next few lines of the code, luckily, this default css path could be overridden by passing "theme" as a param in the options. Hence, if we use the correct cdn path from the new version of the code, it works as expected.

In short, for people using bower; use this,

`window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":null,"theme":"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.10/dark-bottom.css"};`

**Comment by Dolondro** [comment]
We were originally hosting the CSS (stupidly) on S3, which became unpractical with how many people started using cookieconsent.

This combined with sloppy dealing with bower led to this.

We've subsequently fixed these issues however, you should be able to bower install "cookieconsent" at version 2.0.0 and you should on longer have these issues.
