### ISSUE TITLE
French Law

### ISSUE THREAD

**Issue by cdric0701** [insites/cookieconsent#135]
Is this "plugin" compatible with French law about cookies ?
I've installed it and the bar is displaying correctly ... however I don't really understand how it works.
Are Google analytics and Google Adsense disabled until we click on the link ? 
Do I have to add more code to disable until the user accepted ?

**Comment by alexmorleyfinch** [comment]
CookieConsent V2 does not contain any knowledge about country location or the cookie law in each country, therefore you need to configure it to French law yourself.

CookieConsent V3 however does contain these features. It can detect what country it is in by using a location service, and then it can change it's configuration based on the laws in that country.

However, this does not affect Google Analytics or Adsense, or any other cookies on your site. CookieConsent only tells you if you *should* enable cookies or not. Whether you actually enable/disable them is down to you.

There is a handy little function in CookieConsent V3 that gets called when ever the user makes a decision, called `onStatusChange`. So you create a function called `toggleCookies(isEnabled)`

```
function toggleCookies (isEnabled) {
  if (isEnabled) {
    // enable all cookies
  } else {
    // disable all cookies (or maybe only the intrusive tracking cookies, leaving all your innocent UI cookies still enabled, it's up to you)
  }
}

cookieconsent.initialise({
  // ... options for popup ...
  onStatusChange: function (status) {
    var type = this.options type;
    // We set the default value based on the type of popup. "info", "opt-in" or "opt-out".
    // If it's "opt-in", we disable by default. If it's "opt-out" or "info", we enable by default.
    var shouldEnableCookies = type == 'opt-out' || type == 'info';
    if (this.hasAnswered()) {
      shouldEnableCookies = this.hasConsented();
    }
    toggleCookies(shouldEnableCookies);
  }
});
```
