### ISSUE TITLE
Cookie notification showing up on every refresh

### ISSUE THREAD

**Issue by akenins** [insites/cookieconsent#139]
I've gone through all the threads and tried all suggestions, I have gone to other websites using this tool and inspected their code, but no matter what I try I get the Cookie Consent notification popping up on every refresh and other page load even after I've clicked "Got It!" I only get this issue in Internet Explorer and Edge. Seems to be working fine on Chrome and Safari. It's not just my computer as everyone else testing is also getting this same issue in their instances of IE and Edge. What am I not seeing?

````javascript
    window.cookieconsent_options = {
    	learnMore:"More info",
    	link:"http://www.ourcompany.com/privacy/",
    	theme:"dark-bottom",
        cookieconsent_dismissed:"yes"
    };
````

**Comment by WiredSoftware** [comment]
I believe this may be because of the Do Not Track settings in IE being honoured by the plugin (so disallowing the cookie that the plugin tries to set). Try setting the additional parameter of

ignoreDoNotTrack: true
