### ISSUE TITLE
How to initialize programmatically?

### ISSUE THREAD

**Issue by momsenmeister** [insites/cookieconsent#143]
Is it possible to initialize cookieconset programmatically?
I don't want to show it automatically when the script is included in my page.

Insstead I'm missing methods like:
`$('#cookieconsent').show();`

The goal is to trigger this only when certain conditions are met.
As a workaround I use CSS to show and hide the panel now, but in my opinion it's not a clean solution :)

Thx, Mike

**Comment by alexmorleyfinch** [comment]
This can be done in CookieConsent V2, but it can be rather difficult. You need to defer the loading of your script.

CookieConsent V3 has just been released, which allows more customisation than ever before. The whole tool is initialised via `cookieconsent.initialise()` which can be called at any time after the script has loaded.

The `initialise` function also initialises other features of CookieConsent V3, like the Location services and the Cookie Law module. If you don't want these features, you can use just the `Popup` by instantiating it.

```
var popup = new cookieconsent.Popup(popupOptions);

// opens the popup if the user has not yet given their answer
popup.autoOpen();
```
