### ISSUE TITLE
Cookie Consent 3 demos not opening after dismissal

### ISSUE THREAD

**Issue by oliveremberton** [insites/cookieconsent#150]
Bug in the demo area (edge case, but relevant here):

1. View any demo page, open a banner, dismiss it
2. Navigate via a link to another demo
3. Try to open a banner, it will not open

Refreshing the page fixes the issue.

I suspect that we somehow fail to invoke the banner if it has already been dismissed via cookie when the page loads.

**Comment by piiupilt** [comment]
I am not able to replicate the issue, but it's probably to do with location services overriding the options. 
Added UK as the default country to examples (which should've been there anyway).
