### ISSUE TITLE
Location Services not configurable enough

### ISSUE THREAD

**Issue by Dolondro** [insites/cookieconsent#152]
Our current system tries three systems to try and ascertain what country the visitor comes from.

This potentially could work for systems that fall within these kind of usage limits, but in systems with higher numbers of visitors, this could be more problematic.

We should provide configuration options that allows people to use the services we've coded for using an API key for their paid product and provide an easy (documented) way for them to host their own service.

**Comment by Dolondro** [comment]
Being fixed in #153

**Comment by adjohu** [comment]
Fixed in #153.
