### ISSUE TITLE
3.5kb or 17kb?

### ISSUE THREAD

**Issue by jenstornell** [insites/cookieconsent#154]
**This says 3.5kb:**

https://silktide.com/tools/cookie-consent/docs/

**This says 17kb:**

https://github.com/insites/cookieconsent/blob/master/build/cookieconsent.min.js

3.5kb is almost nothing but having a js of more than 17kb just to display a cookie message is quite much, I think.

**Comment by oliveremberton** [comment]
Cookie Consent v2 was 3.5kb. We've been working on v3 which is quite a bit larger, but a lot more capable (e.g. info/opt-in/opt-out support, automatic application of country-specific rules etc). You're free to use either.

**Comment by jenstornell** [comment]
@oliveremberton Thanks for the info. I've found a smaller solution that will be just enough for my needs:

https://github.com/Alex-D/Cookies-EU-banner

Cookie Consent might be awesome because it's feature rich, but in my case I don't need all that. Thanks for the reply!
