### ISSUE TITLE
Any documentation ??

### ISSUE THREAD

**Issue by theuros** [insites/cookieconsent#157]
The only documentation I could find is that link on github page wich leads on https site with username and password.

Installation is simple, but once you have it on site there is no info how to make it actually work. On the old plugin you used a class like cc-onconsent-ga on script tag with text/plain type. That type was changed to javascript once you accepted the notification. 

Here in version 2.0 all I can find is that is much simple than before and that's it !!  

Can someone please explain me how can this thing work compared to old plugin? I need to have an option that user select what he allows to use (analytics, soccial, ....)

thanx

**Comment by piiupilt** [comment]
The current version on GitHub is actually version 3.0, which is completely rewritten and has a lot more customisation options that version 1 and 2, but is not yet officially released. The release of v3.0 and corresponding documentation will happen in a couple of days.

We don't support different kind of cookie types since v2.0, as it made things too complicated for majority of our users. However, v3.0 has several callback hooks, so developers can implement their own custom solutions.

**Comment by theuros** [comment]
Thanx for the answer. I thought that this is about version 2.0 Anyway how does it work? I mean, old script schanget type from text to javascript how about now ? 

Let keep it simple and use only google analytic. You integrate cookie consent and put GA code into page. Then what ?

**Comment by alexmorleyfinch** [comment]
Hey, the documentation for CookieConsent Version2 can be found here:

https://silktide.com/tools/cookie-consent/docs/

**Comment by theuros** [comment]
Thanx but I already found those docs which are worthless. They only explain how to install / implement it and they say nothing about how actually define which code is "activated / deactivated" when you click on "agree" !!  If I have a JS that should run only after user accepts cookies... how do I implement that ?? ... I didn't found any explanation about it.

**Comment by piiupilt** [comment]
Cookie Consent v2 does not have options for that. It was supposed to be a tiny plug-in to cover the most basic needs of majority of users. This version is now discontinued.

However, as mentioned before, we have callback hooks available in v3 to run your JS. 
This version is in the master of this repository, can also be downloaded using our [configurator](https://cookieconsent.insites.com/download/), has better [documentation](https://cookieconsent.insites.com/documentation/javascript-api/) than v2 and also [instructions](https://cookieconsent.insites.com/documentation/disabling-cookies/) for running the JS that disables cookies.

**Comment by theuros** [comment]
What v2 supposed to do?? Just show a notification that cookies are used ? What is the purpose of "accept" button? And what option user has if doesn't want to accept cookies ? From what I see a user has no choice to accept or refuse cookies, because cookies are set when first visits the page if he want them or not. 

I'll check it out v3 thanx.
