### ISSUE TITLE
Issue with code example on website

### ISSUE THREAD

**Issue by tomeightyeight** [insites/cookieconsent#159]
See here: https://cookieconsent.insites.com/download/#

The src attribute for the script / stylesheet included from a CDN isn't prefixed with // causing a 404. Browser is interpreting this is a relative URI.

```
<link rel="stylesheet" type="text/css" src="cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.1/cookieconsent.min.css" />
<script src="cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.1/cookieconsent.min.js"></script>
```

**Comment by adjohu** [comment]
Thanks @tomeightyeight - we're fixing that now.

**Comment by Dolondro** [comment]
This should be fixed! Thanks for the report!
