### ISSUE TITLE
Error breaking popup : null is not an object

### ISSUE THREAD

**Issue by mkstix6** [insites/cookieconsent#160]
I implemented the popup by following the Wizard and copy/pasting the result.

I get this error on Chrome:
cookieconsent.min.js:1:4274
TypeError: null is not an object (evaluating 's.firstChild')

I get this error on FireFox:
cookieconsent.min.js:1:4257
TypeError: s is null[Learn More]

Is this something at my end or is this the code provided?
Apologies if this is my bad somehow.

Link to the Wizard I used: https://cookieconsent.insites.com/download/

**Comment by piiupilt** [comment]
For some reason `document.body` returns null. 

You could try:
- Moving the scripts to footer, just before the `</body>` tag. 
- Wrapping the initialise code in window.onload: 
`window.onload = function() { window.cookieconsent.initialise( //your_options ) }`

**Comment by mkstix6** [comment]
Moving the scripts to the bottom has helped. Thank you :).
