### ISSUE TITLE
Wizard CSS link should be href instead of src

### ISSUE THREAD

**Issue by mkstix6** [insites/cookieconsent#162]
Using this wizard: https://cookieconsent.insites.com/download/

Talking about the code outputted to copy and paste.

[doesn't work for me]
`<link rel="stylesheet" type="text/css" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.1/cookieconsent.min.css" />`

should be [works for me]
`<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.1/cookieconsent.min.css" />`

Swapping the "src" for "href"

**Comment by piiupilt** [comment]
You are right. Fixed this in the configurator. 

Thank you for noticing!
