### ISSUE TITLE
bower.json does not include .min css   

### ISSUE THREAD

**Issue by alexanderhoset** [insites/cookieconsent#163]
Hi 

Is there a reason only the js file is added in the main tag  of bower.json, when both css and js can be found in the dist folder:
`"main": "build/cookieconsent.min.js",`

If this is a bug, this is the fix for it: 
` "main": [
      "build/cookieconsent.min.js",
      "build/cookieconsent.min.css"
    ],`

**Comment by Dolondro** [comment]
We had a very good reason, which is that none of us really use bower anymore and I didn't read the docs properly :P 

Fixed in https://github.com/insites/cookieconsent/commit/00c5e7fa5ef0cd8f377b2acfb5560f2196ce4aac
