### ISSUE TITLE
Opt-in hasConsented() is always true

### ISSUE THREAD

**Issue by alkar** [insites/cookieconsent#168]
Using the 'opt-in' mode and hooking up to the `onStatusChange` callback, `hasConsented()` is always true, regardless of what the user has selected.

Additionally, the `cookieconsent_status` cookie is set even if the user dismisses the popup (effectively opting out) - is this intentional, meaning I should clear that cookie in the callbacks? The [documentation](https://cookieconsent.insites.com/documentation/compliance/) implies otherwise.

Let me know if you need additional information.

**Comment by plenka** [comment]
I can confirm this. The `hasConsented()` method only checks whether the status is 'allow' or 'dismiss', regardless of the used mode. However, these are the two statuses used in the 'opt-in' mode...

Unfortunately, this makes the examples on https://cookieconsent.insites.com/documentation/disabling-cookies/ quite broken.

**Comment by akroii** [comment]
Any solution for this?

**Comment by OliverSchloebe** [comment]
Any news on this?

**Comment by FlorentMasson** [comment]
@alexmorleyfinch @piiupilt @Dolondro please fix this or accept one of the many PR that fix this

**Comment by RobertCordes** [comment]
There's a pull request with a fix, but for now I just didn't use hasConsented() but checked if the `status` was `"allow"`. Otherwise it's just `"dismiss"`. Hope that helps.
