### ISSUE TITLE
initialising 2 times cookieconsent and dismissing the popup, writes to the cookie name defined in the last initialization

### ISSUE THREAD

**Issue by ilias-sp** [insites/cookieconsent#171]
hi :)

i created this account on github just to ask you about my issue, i am not sure if i should raise it as an issue, as its not a problem with cookieconsent intentional functionality. my issue is:

i like the library and its configurable looks, so i gave it a shot to use it as a means of delivering tips to users, that they can dismiss (and store a cookie that the tip was seen)

my issue comes when i try to define in a single page 2 tips, i.e 2 times running the cookieconsent.initialise. the pop ups appear as expected, but the 1st popup, generates the cookie from the 2nd initialization.

Code that i am using:

the function:

```
function notifyUserwithCookie(messageText, cookieName, durationDays) {
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#151515",
      "text": "#777777"
    },
    "button": {
      "background": "#e67e22",
      "text": "#111"
    }
  },
  "content": {
    "message": messageText
  },
  "cookie": {
    "name": cookieName,
    "expiryDays": durationDays
  },
  "elements": {
  	messagelink: '<span id="cookieconsent:desc" class="cc-message">{{message}}</span>',
  }
})
}
```
and during page load:

```
<script>
$(document).ready(function() {
notifyUserwithCookie('This website uses cookies to provide you personalized features init 1.', 'cookie1', 366);
notifyUserwithCookie('This website uses cookies to provide you personalized features init 2.', 'cookie2', 367);
});
</script>
```

when you press the dismiss button, both instances generate the cookie2. Do you think this could be fixed, or better say, enhanced in order to support this kind of usage?

thank you in advance for your time!

**Comment by Dolondro** [comment]
Hi Ilias! 

This isn't something we'd be interested in changing, simply as it's not in the scope of the project. If you're using cookieconsent (as, well, something to give consent for cookies) you would never want more than one instance of it initialized.

You'd be better off grabbing the CSS/JavaScript for the styles you like and writing a very simple implementation around it.

I'm going to close the issue, but let me know if you need any help regarding it, as you phrased your issue so politely :P

Regards

**Comment by ilias-sp** [comment]
hey Dolondro,

sure, i understand, its not what it was meant to do.. 

Well, I spent some time yesterday and managed to tweak it and cover my needs. i am not so strong with js to understand the whole library, so - for anyone else interested - i added the cookie name in a data- attribute of the dismiss button html code, and when button is clicked i pick up the cookie name that i have to create.

Regards
