### ISSUE TITLE
All service failure causes infinite loop

### ISSUE THREAD

**Issue by travisp** [insites/cookieconsent#173]
**Original report**
We encountered this when the first two services failed because of too many requests and we reached requesting maxmind. We got the error "Users of MaxMind Javascript services must register their domains at ..."

However, this reliably crashed chrome browsers for many of our users. to replicate, simply use only the maxmind service and make this change to the maxmind function:
```
-                done({
-                  code: location.country.iso_code
-                });
+                done(toError(location));
```
which replicates how it responds to an error response.

I haven't fully dug into it, but the maxmind callback code seems pretty different than the other code -- it has no try/catch, and always calls the done object instead of returning a json object, but there is a comment that this is intentional because of a second ajax call.

**edit**: I complete misunderstood the source of this bug. The problem is when all of the services are exhausted, the code enters an infinite loop:

```
      do {
        service = this.getServiceByIdx(++this.currentServiceIndex);
      } while (!service);
```

if there is never another service, it keeps going...

**Comment by Dolondro** [comment]
Thanks for the report, we'll get it fixed on Monday!

**Comment by alexmorleyfinch** [comment]
A PR has been made for this issue: https://github.com/insites/cookieconsent/pull/175
