### ISSUE TITLE
The tool doesn't work with google chrome

### ISSUE THREAD

**Issue by VeillaultAdrien** [insites/cookieconsent#174]
Hello !
I am trying to add code from this page ("https://cookieconsent.insites.com/download/) on my website. It works nice on mozilla firefox but it doesn't work on google chrome. Could you help me ?

```
<link rel="stylesheet" type="text/css" href="cookies/cookieconsent.min.css" />	
<script src="cookies/cookieconsent.min.js"></script>
	<script>
		window.addEventListener("load", function(){
		window.cookieconsent.initialise({
		  "palette": {
			"popup": {
			  "background": "#edeff5",
			  "text": "#838391"
			},
			"button": {
			  "background": "#4b81e8"
			}
		  },
		  "theme": "classic",
		  "content": {
			"message": "Ce site utilise des cookies afin de vous assurer la meilleure expérience possible.",
			"dismiss": "Ok",
			"link": "Plus d'informations"
		  }
		})});
	</script>
```

**Comment by VeillaultAdrien** [comment]
No one ? :(

**Comment by piiupilt** [comment]
Could you give us some more details? 
For example, is there an error in the Javascript console or does the pop-up just fail to appear?
A link to the website itself would also help.

If there is no error of any kind, it could be one of the following: 
- You have already clicked the consent button in Chrome (it remembers the choice)
- Your browser uses a location where cookie consent is not required (outside the EU)

**Comment by Dolondro** [comment]
I copied and pasted your code, but with the links to the CDN version of cookieconsent and it works fine on Chrome.

```
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
    window.addEventListener("load", function(){
      window.cookieconsent.initialise({
        "palette": {
              "popup": {
                "background": "#edeff5",
                "text": "#838391"
              },
              "button": {
                "background": "#4b81e8"
              }
        },
        "theme": "classic",
        "content": {
              "message": "Ce site utilise des cookies afin de vous assurer la meilleure expérience possible.",
              "dismiss": "Ok",
              "link": "Plus d'informations"
        }
      })
    });
</script>
```
![image](https://cloud.githubusercontent.com/assets/1678803/20558601/c1d8c930-b168-11e6-978d-15bcf3c82a5f.png)

Without additional information there's not much we can do to help you

**Comment by VeillaultAdrien** [comment]
I try your code but it doesn't work. I think, I do something wrong but I don't know why.
I don't remember if I already consent the button. How I can reset if I consent ?
My browser use location in Europe (France).
How can I display my code without execute it ?

**Comment by Dolondro** [comment]
You can reset if it if you've already clicked consent by clearing cookies for your site.

The easier way to test this is to open up your website in incognito mode.

**Comment by VeillaultAdrien** [comment]
Thanks !
I am stupid ! It works fine in incognito mode.
