### ISSUE TITLE
File retrieval not properly resolved

### ISSUE THREAD

**Issue by kludikovsky** [insites/cookieconsent#176]
I get the following errors in my apache error log

 `File does not exist: /var/www/vhosts/domain.com/httpdocs/typo3conf/ext/cookieconsent2/Resources/Public/JavaScripts/{{options.link`
I suppose that the filename not properly resolved. 
As far as I could track this down it's somewher in the Javascripts (possibly Resources/Public/JavaScripts/cookieconsent.min.js:)

**Comment by alexmorleyfinch** [comment]
Looks like this may be some kind of pre-processor? I'm not sure if this is to do with our tool or not. We'd need more info. Sorry
