### ISSUE TITLE
Revoke button seems to be broken

### ISSUE THREAD

**Issue by plenka** [insites/cookieconsent#177]
I'm trying to implement the cookie consent to always show the revoke button, but it seems to be broken. I've implemented the first example on https://cookieconsent.insites.com/documentation/javascript-api/, replacing the URLs of the JS and CSS files with the CDN URLs. The revoke button will show up directly after dismissing the consent notice, but after a page reload the revoke button doesn't show up.

I've tested this on macOS Sierra, Chrome 54.0.2840.98 and Safari 10.0.1.

**Comment by matejslo** [comment]
I also have the same issue. Tested on Firefox 50.0.2 and Chrome 54.0.2840.99.

After reload revoke button disappears.  After page reload the button DIV get a style display:none as follows: <div class="cc-revoke cc-bottom cc-animate cc-color-override-17377638    cc-active" style="display: none;">Cookies</div>.

My work around is to edit CSS: 

.cc-revoke.cc-bottom {
    display: block !important;
}

**Comment by ErikN72** [comment]
I changed the code of cookieconsent.js in this part:

// opens the popup if no answer has been given
    CookiePopup.prototype.autoOpen = function(options) {
      //!this.hasAnswered() && this.options.enabled && this.open();
      if (!this.hasAnswered() && this.options.enabled) {
        this.open();
      } else {
        if (this.options.revokable)
         {this.toggleRevokeButton(true);
         }
      }
    };

Now it seems to work... 
I would be interested in your opinion.

**Comment by Datajuristes** [comment]
Thank you Erik, your code worked for me

**Comment by Jimmi08** [comment]
Thank you Erik, your code worked for me too.

**Comment by urbgimtam** [comment]
Great work! This should be commited. Thanks

**Comment by reformed** [comment]
When is the next release that includes this fix?

**Comment by alexmorleyfinch** [comment]
Very soon! Sorry it took so long. See [here](https://github.com/insites/cookieconsent/issues/409) for details
