### ISSUE TITLE
Change agreement button height/width

### ISSUE THREAD

**Issue by Kelly32** [insites/cookieconsent#181]
Trying to change the agreement button width and height but so far didn't succeeded.
http://prntscr.com/do6pb4

I am using the following height for the banner

`.cc-banner {
    height: 38px;
}`

Tried to change button to the following values but remains unchanged http://prntscr.com/do6pb4 and height matches the banner ones instead of 28px

`.cc-btn {
    height: 28px;
    width: 35px;
}`

Haven't found other values inside the CSS except .cc-btn & .cc-compliance that I could think of will change the height of width of the agreement button

**Comment by alexmorleyfinch** [comment]
Hey, sorry that nobody has replied yet! I'll look into your issue now and get back to you as soon as possible

**Comment by XanderGS** [comment]
Great, looking forward for an answer.

**Comment by XanderGS** [comment]
@alexmorleyfinch, any update on this one?

**Comment by alcharkov** [comment]
#180
