### ISSUE TITLE
Cookie consent not displayed in safari browser

### ISSUE THREAD

**Issue by maniz-stha** [insites/cookieconsent#182]
I added the cookie consent plugin on my site but the cookie consent block is not displayed in safari browser although it works fine in chrome and firefox. I am using safari browser v 5.1.7 in windows10.

**Comment by lasseborly** [comment]
@maniz-stha do you get any error messages back in your console?

**Comment by leshek-pawlak** [comment]
I had this issue too. Ghostery - Safari's plugin to block some web content blocked it. It's needed to add cookieconsent to the white list.
