### ISSUE TITLE
Missing rel="noreferrer" in links

### ISSUE THREAD

**Issue by Slashgear** [insites/cookieconsent#185]
I notice that links generated by cookieconsent JS API don't have *rel* attribut.
I use the fantastic [Dareboost](https://www.dareboost.com/) web performance tool and it ask me to secure all my target="_blank" link ([security breach](https://mathiasbynens.github.io/rel-noopener/))

I did it on all links with target="_blank" in my application but links generated by cookieconsent do not respect this rule.

```html
<a class="cc_logo" target="_blank" href="http://silktide.com/cookieconsent">Cookie Consent plugin for the EU cookie law</a>
```
should contain rel attribut
```html
<a class="cc_logo" target="_blank" rel="noreferrer" href="http://silktide.com/cookieconsent">Cookie Consent plugin for the EU cookie law</a>
```

**Comment by oliveremberton** [comment]
He's right and it's a trivial fix – @piiupilt or @alexmorleyfinch can you take a look?

**Comment by udos** [comment]
I was checking regarding this today and noted that this has been added in pr #209.
note: there is also an issue asking to publish version 3.0.5 on npm -> #246.

**Comment by Dolondro** [comment]
Done
