### ISSUE TITLE
Want to view more information in popup overlay instead of new page

### ISSUE THREAD

**Issue by thepdgroup** [insites/cookieconsent#187]
Hello, 

I am trying to use an onclick function to trigger my more information link in a popup instead of a new page.
I can see that the the more information link has an a class "cc_more_info" already added, but when I try to use it in my script function, it doesn't load the popup. I have created a test link using the same a class and that works fine so think perhaps the cookie content code is blocking te script somehow. 

Please can you advise how to get around this?

Thanks
Vicky

**Comment by alexmorleyfinch** [comment]
It sounds like you just need the more info class to trigger some of your own code? You could add an event handler to the "more info" button using the class `cc_more_info `.

```
document.querySelector('. cc_more_info').addEventListener('click', function() {
  // trigger your own popup
  myPopup()
})
```

You need to make sure to run this after page load though, otherwise `document.querySelector('. cc_more_info')` may be empty
