### ISSUE TITLE
Don't call location service when cookie consent status is dismiss

### ISSUE THREAD

**Issue by yvele** [insites/cookieconsent#189]
Once Cookie Consent message has been display and agreed by a user, location service should not be called again and again.

Can we skip calling location service once `cookieconsent_status == dismiss` ?

PS: In addition, can't we also store the location in cookie as a location service cache?

**Comment by Zenju** [comment]
Fully agree. Most of these geo ip services have limits and contigents in their free plans. So let's not waste these resources needlessly.

**Comment by alexmorleyfinch** [comment]
Wow, this is pretty bad. A fix has been made and will be available in the next release
