### ISSUE TITLE
Improve EU documentation

### ISSUE THREAD

**Issue by pixelchef** [insites/cookieconsent#190]
The documentation around simply showing the banner for EU only [should be improved](https://cookieconsent.insites.com/documentation/location-services-cookie-law/). There is a bunch of documentation and example around the now deprecated cookie consent around this topic. 

Can I get some tips on a working example for showing the banner for EU only? Currently I'm running this 

```
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#ffffff",
      "text": "#1C233F"
    },
    "button": {
      "background": "#9a50a5"
    }
  },
  "theme": "edgeless"
  
})});

```

**Comment by alexmorleyfinch** [comment]
It looks like you need to set `location` to `true` to get the location services working
