### ISSUE TITLE
Translating "privacy policy" button

### ISSUE THREAD

**Issue by matejslo** [insites/cookieconsent#191]
Hi, 

Can we use a multilanguage for "Cookie Policy" (cookieconsent.js line 242) 

  revokeBtn: '<div class="cc-revoke {{classes}}">Cookie Policy</div>',

best regards

**Comment by jayss** [comment]
Hi, I also wonder if it's multi-language, thanks!

**Comment by alexmorleyfinch** [comment]
We only currently support users providing their own translations. See https://github.com/insites/cookieconsent/issues/214
