### ISSUE TITLE
Banner on tablets not styled right?

### ISSUE THREAD

**Issue by kevinjoyner** [insites/cookieconsent#192]
Hello

I'm not quite sure, but I think that for Banner implementations, if it's a mobile device, the cookie banner is styled as Floating; and I think this styling includes a max-width of 384px.

The JS identifies tablets as mobile devices, on the basis of them having e.g. "Android" or "iPad" in the user agent string.

But tablets have quite wide screens, even in portrait orientation, and I think this is causing the problem shown in the attached screenshot.

![screenshot_20170226-164220](https://cloud.githubusercontent.com/assets/1257894/23392833/52c3f218-fd76-11e6-94a6-1a4df9d67dfe.png)

I've worked around this problem on my website [https://kevinjoyner.com](https://kevinjoyner.com), with a style tag loaded after the cookieconsent CSS:

`<style>@media screen and (min-device-width : 385px) {
	.cc-window.cc-floating { max-width: none; flex-direction: row; }
	.cc-floating .cc-message { width: 100%; margin-bottom: 0px; }
	.cc-window.cc-floating .cc-compliance { margin-top: -5px; float: right; }
	.cc-link { padding-left: 0px; }
	.cc-window.cc-floating .cc-compliance { min-width: 100px; }
}</style>`

I realise this isn't a very good solution, particularly the "min-width: 100px" which would have to change if I used different text in the compliance button!

Let me know if this isn't a bug at all, and I'm missing something.

Thanks!

**Comment by jackplug** [comment]
I think it would be nice if this was user-configurable via an option, as sometimes you may want the 100% banner on mobile too (again, as @kevinjoyner says, unless I am missing something)

**Comment by Mainbelt** [comment]
Same here. What I did is to remove 'iPad' from the function that checks whether is mobile and in my case (bottom placement) it works fine.

Now my function (lines 128-130) looks as follows:

`isMobile: function() {
return /Android|webOS|iPhone|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
},`

**Comment by kevinjoyner** [comment]
It being an option is nice idea, but I can imagine needing to keep the functionality of isMobile - whether it's active by default or not.

`isMobile: function() { return /Android|webOS|iPhone|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent); }`

You might think it could just no longer have "iPad" in it... but that doesn't solve the problem for Android tablets. I first saw the issue with an Android Pixel C tablet.

"Android" in the user agent string doesn't distinguish between mobile and tablet - it catches both - and I don't suppose there's anything else consistently in all Android phone user agent strings that isn't in Android tablet ones.

That's why my workaround introduces additional styling conditional on the screen width. Maybe the right thing is for that isMobile function in the JS to be related to screen width, not the user agent string? I don't know if that's possible.

**Comment by panzerfahrer** [comment]
To me, it looks like the cause is that the popup position gets always overridden to be floating on mobile (see [cookieconsent.js@L647](https://github.com/insites/cookieconsent/blob/31b1a96d9c6e605096b27a560f92e77868704dc1/src/cookieconsent.js#L647-L649) ). This obviously breaks quickly depending on the layout.

My workaround for this, is to manually remove the css classes `cc-floating` and add `cc-banner` after initialization:
```javascript
// jquery required for this snippet
$(window).load(function() {
  var container = $("#cookieconsent");
  var options = {
  container: container.get(0),
  layout: "basic",
  position: "top",
  static: true,
  content: { /* ... */ }
};

window.cookieconsent.initialise(options);
$("#cookieconsent .cc-window").removeClass("cc-floating").addClass("cc-banner");
```

**Comment by webkaktus** [comment]
any updates on this? I have the same problem (v3.0.3) and in my opinion it's really important, cause otherwise it's more or less useless on tablets.

Thank you

**Comment by garywood84** [comment]
@panzerfahrer 

I'm having a similar problem in that my banner is not a banner when viewed on an iPad, but a floating block.

I've been trying your code as a workaround but haven't succeeded in getting it to work. Can you please clarify where I ought to put the code?

Thanks,
Gary

**Comment by pnewest** [comment]
@panzerfahrer

As with Gary I'm having the same problem of the banner showing as a top corner block instead of right across the screen.  This just affects Tablets - landscape and portrait (mobile phones and Desktop are fine).

My code is:

       
        <link rel="stylesheet" type="text/css" href="css/cookieconsent.min.css" />
        <script type="text/javascript" src="js/cookieconsent.min.js"></script>
		<script>
        window.addEventListener("load", function(){
        window.cookieconsent.initialise({
          "palette": {
            "popup": {
              "background": "#1b99d6",
              "text": "#ffffff"
            },
            "button": {
              "background": "#58bbeb",
              "text": "#ffffff"
            }
          },
          "theme": "edgeless",
          "position": "top",
          "static": true,
          "content": {
            "message": "By using this website you agree to our use of cookies.",
            "dismiss": "Close",
            "link": "Learn more ",
            "href": "https://www._mysite_.com/privacy.html"
          }
        })});
        </script>  

So where would I add your js, as I've too tried and failed.

Thanks,
Mike

**Comment by garywood84** [comment]
@pnewest 

Another user helped me to get this working. Just add the following style to your code:

`@media screen and (min-device-width : 385px) {
    .cc-window.cc-floating { max-width: none; flex-direction: row; }
    .cc-floating .cc-message { width: 100%; margin-bottom: 0px; }
    .cc-window.cc-floating .cc-compliance { margin-top: -5px; float: right; }
    .cc-link { padding-left: 0px; }
    .cc-window.cc-floating .cc-compliance { min-width: 100px; }
    .cc-bottom { bottom: 0; }
  }
`

**Comment by pnewest** [comment]
Hi Gary

Many thanks for the CSS, really good of you to help out.  I added it to the end of cookieconsent.min.css (as I call it locally), but am still getting the short banner on Tablet.  Where did you add the CSS to get it to work?

Thanks,
Mike

**Comment by pnewest** [comment]
Hi Gary

Just tried again, and added into the home page after the cookie routine and it worked.  Fantastic!  Thank you so much.

Mike

**Comment by garywood84** [comment]
No problem, Mike. I can't take any credit - it was another user who helped me to get it working. I'm glad it worked for you, too.

**Comment by udegbunamchuks** [comment]
> Hello, I had the same issue (tablet showing floating box on the side, rather than the straight bar).
> 
> The CSS trick works for me as well, however I had to add `!important` to all the properties to make them take higher precedence. Ultimately, I needed way less rules. I placed my CSS in my theme's style.css (where else?).
> 
> ```
> @media screen and (min-device-width: 385px) {
>   .cc-window.cc-floating {
>     width: 100% !important;
>     max-width: 900px !important;
>     border-radius: 0 !important;
>     left: 0 !important;
>     right: 0 !important;
>   }
>   .cc-bottom {
>     bottom: 0 !important;
>   }
> }
> ```

Thanks. This sure helped
