### ISSUE TITLE
Problem with subdomain and cookie.domain option

### ISSUE THREAD

**Issue by JulienTLD** [insites/cookieconsent#194]
Hello,

First, thank you very much for your Cookie Consent free service ;)

I would like cookieconsent to set the same dismiss cookie for both our main website (www.mydomain.com) and our forum (forum.mydomain.com). I have set the following but it doesn't work, I have to click on the dismiss bar two times, for each site.

"cookie.domain": ".mydomain.com"

Same behavior without the dot prefix = "cookie.domain": "mydomain.com"

Same behavior after adding the following :

"cookie.path": "/",
"cookie.expiryDays": "365"

Tested with IE, Firefox and Chrome Under Windows 7 x64.

To set my custom cookies with PHP, I use the dot prefix and I do not have any problem.

I have added these options just after the law:{.....}, structure, it is right ? I find that the documentation is not very clear on where we have to add the options in the JavaScript tag.

Thanks for your help.

**Comment by nixa333** [comment]
I can confirm this is a problem.

**Comment by lochmueller** [comment]
👍

**Comment by JulienTLD** [comment]
Is this project still maintained ?

**Comment by poetzsas** [comment]
Same issue here on Mac Chrome and Firefox.

**Comment by pootzko** [comment]
Still no reply? :/

**Comment by pootzko** [comment]
Ok, I figured it out.. Instead of setting "cookie.domain" you should set

```json
"cookie": {
  "domain": ".yourdomain.com"
}
```

as part of the `initialise`.. So in the end you should have something like this for example:

```js
    window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#282d32",
          "text": "#c9cccf"
        },
        "button": {
          "background": "#1e5ba2"
        }
      },
      "position": "bottom-left",
      "cookie": {
        "domain": ".yourdomain.com"
      }
    })});
```

**Comment by JulienTLD** [comment]
Thanks pootzko, writing the cookie part as an independent section seems to work now with multiple subdomains (except for Internet Explorer which still displays the Cookie Consent bar at each page view even on the main domain...).

FYI, here is my code now :

		window.addEventListener("load",
		function()
		{
			window.cookieconsent.initialise(
			{
				"palette":
				{
					"popup":
					{
						"background": "#F0F0F0",
						"text": "#838391"
					},
					"button":
					{
						"background": "#004483",
						"text": "#FFFFFF"
					}
				},
				"theme": "edgeless",
				"content":
				{
					"message": "My message",
					"dismiss": "OK",
					"link": "More",
					"href": "https://www.domain.com"
				},
				"cookie":
				{
					"domain": ".domain.com",
					"path": "/",
					"expiryDays": "365"
				},
				"law":
				{
					"regionalLaw": "false"
				}
			}
			)
		}
		);

**Comment by seangreen** [comment]
Not working for me... tested it with current Chrome and Safari.

**Comment by Reshmysandeep** [comment]
I have to block Facebook, Instagram, Youtube these are subdomain for my website how will I do this . Please help me
