### ISSUE TITLE
Cookie Consent Pop up showing on every page on website in Safari Private 

### ISSUE THREAD

**Issue by shrutirathee** [insites/cookieconsent#195]
I put this code in head of my site :

<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#252e39"
    },
    "button": {
      "background": "#14a7d0"
    }
  }
})});
</script>

But the pop is opening on every page and at checkout i get the error message of :
Error processing checkout: You must enable cookies in order to check out

**Comment by bensquire** [comment]
@shrutirathee If I had to guess, privateMode prevents cookies which means cookieConsent can't save it's state.

**Comment by alexmorleyfinch** [comment]
That is correct. If private mode is like "incognito mode" in chrome, then cookies can't be saved.

There are some ways in which the tool detects if cookies can be used, and if they can't it disables its self, but I'm not sure if there is a way to detect private mode.

Like wise your checkout processor must also require cookies, which seems unrelated to CookieConsent
