### ISSUE TITLE
Doku: Wrong plugin setting

### ISSUE THREAD

**Issue by kludikovsky** [insites/cookieconsent#199]
In the manual there should be 
  tx_cookieconsent2
instead of 
  plugin.tx_extensionkey. ...

![image](https://cloud.githubusercontent.com/assets/6077916/26416287/a5f484ca-40b5-11e7-88e3-082ecd5aac90.png)

**Comment by alexmorleyfinch** [comment]
Which manual are you looking at? this doesn't seem familiar. You may be looking at a different tool or version
