### ISSUE TITLE
Cookie notice doesn't disappear on Windows Mobile 8.1

### ISSUE THREAD

**Issue by Galixte** [insites/cookieconsent#202]
Hi,

the phpBB project uses your Cookie Consent plugin. I encounter a display problem on a Windows Mobile 8.1 device like Nokia Lumia 1320, if the "Cookie notice" feature is activated the blue area comes out of the screen and it becomes impossible to click on the "Got it!" button.

Source of my report on phpBB.com: https://tracker.phpbb.com/browse/PHPBB3-15249
Source of my proposal fix for phpBB on GitHub: https://github.com/phpbb/phpbb/pull/4853 But they think it’s not to them to fix this but you.

So i have opened this issue to inform you about this problem. My proposal fix is replaces this line: https://github.com/insites/cookieconsent/blob/master/src/styles/media.css#L21 with this: ```.cc-window.cc-floating {max-width: 100%;}```.

**Comment by alexmorleyfinch** [comment]
Sorry about the lack of communication. I appreciate how much effort you put into a proposal fix. I'll look into this and get back asap

**Comment by Galixte** [comment]
Thanks!

**Comment by Galixte** [comment]
Any news?

**Comment by alexmorleyfinch** [comment]
This may be fixed, but we have no means of testing it at the minute :( We tested on an emulator and it seemed to work okay 👍

**Comment by Galixte** [comment]
@alexmorleyfinch Thanks
