### ISSUE TITLE
IE 8 support?

### ISSUE THREAD

**Issue by Miw0** [insites/cookieconsent#203]
Hello,

cookieconsent doesn't seem to work in IE 8, see screenshot below.

![screen](https://user-images.githubusercontent.com/3817545/27484398-5d6a2e86-5829-11e7-86f6-5faa6557569b.jpg)

**Comment by Miw0** [comment]
Any update on this?

**Comment by artursopelnik** [comment]
+1

**Comment by gvonem** [comment]
+1

**Comment by Zen4All** [comment]
-1

**Comment by Miw0** [comment]
@Zen4All I agree, but we still got legacy projects we need to support and update where customer enforces IE 8. 
If @insites would clearly indicate (fe. in the Readme?) which IE versions are supported I am okay with switching to another plugin solution.

**Comment by alexmorleyfinch** [comment]
Sorry about the lack of communication. I will look into this issue and add support to the README as suggested!

**Comment by broodjekipburger** [comment]
+1

**Comment by Dolondro** [comment]
IE8 support isn't something we'd look at putting time into now.

I appreciate that there are still a small number of people using IE8, but even ignoring how horrible the fix will probably have to be, it isn't worth our time to even get a dev environment up to test IE8, let alone debug and fix it.
