### ISSUE TITLE
Romania is not in the countries list

### ISSUE THREAD

**Issue by mfd12** [insites/cookieconsent#204]
Since first of January 2007, Romania is part of European Union, yet this country is not on the list of countries for showing cookie consent message. Why?

Thank you

**Comment by alexmorleyfinch** [comment]
Sorry, the list of countries isn't updated often and we currently rely on users like yourself to let us know of any errors! I've made an issue https://github.com/insites/cookieconsent/issues/216 to add Romania to the list of EU countries.

Thank you.
