### ISSUE TITLE
Disabled cookies

### ISSUE THREAD

**Issue by chefuss** [insites/cookieconsent#205]
Hi, I been reading the documentation from your site, but cannot get to disable the cookies until the user opt-in for them. This is the code: 
I don't know what should I put in the //disable or //enable cookies comments from the onInitialise functions. 
Hope you can help, thanks in advance! 

```
window.addEventListener("load", function(){
    window.cookieconsent.initialise({
        "palette": {
            "popup": {
              "background": "#edeff5",
              "text": "#838391"
            },
            "button": {
              "background": "#4b81e8"
            }
        },
        "type": "opt-in",
              "content": {
                "message": "En este sitio utilizamos cookies para mejorar la experiencia de navegación.",
                "dismiss": "Lo entiendo",
                "allow": "Permitir Cookies",
                "link": "Política de cookies",
                "href": "/politica-cookies.html"
        },
        onInitialise: function (status) {
          var type = this.options.type;
          var didConsent = this.hasConsented();
          if (type == 'opt-in' && didConsent) {
            // enable cookies
          }
          if (type == 'opt-out' && !didConsent) {
            // disable cookies
          }
        },
        onStatusChange: function(status, chosenBefore) {
          var type = this.options.type;
          var didConsent = this.hasConsented();
          if (type == 'opt-in' && didConsent) {
            // enable cookies
          }
          if (type == 'opt-out' && !didConsent) {
            // disable cookies
          }
        },
         
        onRevokeChoice: function() {
          var type = this.options.type;
          if (type == 'opt-in') {
            // disable cookies
          }
          if (type == 'opt-out') {
            // enable cookies
          }
        }
    })
});
```

**Comment by panta7** [comment]
Same problem here, I don't Know where to put that code. Example: if I would like to prevent cookie from Google Analytics code befor opt-in where have I to put that code, please? Thanks

**Comment by johnfoderaro** [comment]
Hi - I am working through a similar issue and I believe I came up with a solution.

Except, for me, all of the cookies I am contending with are third party and I do not control their "flow" from our web server, nor do we set any from our web server. My solution has been to create an object with a few methods.

Here is a rough implementation I worked on today. It'll get your cookie IDs via the `read` method and then you can "delete" the cookie dependent upon the ID via the `delete` method and passing in a cookie id ("delete" is just setting that cookie id value to nothing and setting an expiration date of 1/20/1970):

```javascript
export const cookiesUtil = {
  read() {
    const cookieIds = [];
    const cookies = document.cookie.split(';');
    cookies.forEach(cookie => cookieIds.push(cookie.split('=', 1)[0].trim()));
    return cookieIds;
  },
  delete(cookieId) {
    let cookies = document.cookie;
    return cookies = `${cookieId}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/`;
  }
}
```

**Comment by rosibabystiupida** [comment]
Same problem here! I don't know what to insert where there are   "// disable cookies" and "// enable cookies"? Someone can give a complete example please? thank you very much!

**Comment by chefuss** [comment]
I think nobody will help with this question, but I manage to solve it like this: 
- Note: my only problematic cookie is from google analytics. So I used window['ga-disable-GA_TRACKING_ID'] = true; 
So when I load the cookie with google gtag.js

```
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=GA_TRACKING_ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'GA_TRACKING_ID');
 window['ga-disable-GA_TRACKING_ID'] = true;
</script>
```
Now the cookie from google won't send any data. Then if the user says "yes" :
in the enable cookies:

`window['ga-disable-GA_TRACKING_ID'] = false;`

if the user says "no":

`window['ga-disable-GA_TRACKING_ID'] = false;`

The only problem that I still have is that if the user doesn't navigate to another page there is no data sent. I have to see in the google.developers.com how to do the same for onepage sites.

Hope this works for some of you!! if you have another newbie solution post it please!

**Comment by drhickerson** [comment]
Here was my solution: 

`  onStatusChange: function(status) {
    if (this.hasAnswered() && this.hasConsented()) {
      setTimeout(function(){ window.location.reload(true) }, 100);
          // Put Your Google Analytics Tracking Code here
	  }    
  },
`

I placed this within the window.cookieconsent.initialise brackets, but loaded the google tag manager script outside of the Cookie Consent code, on it's own line. Including it within caused an error; leaving it outside didn't affect the loading of cookies.

Additionally, I added code to remove the google cookies, which linger on revoking permission if you load the analytics code this way. I put this directly beneath the code above: 

`  onRevokeChoice: function() {
	function clearCookie(d,b,c){try{if(function(h){var e=document.cookie.split(";"),a="",f="",g="";for(i=0;i<e.length;i++){a=e[i].split("=");f=a[0].replace(/^\s+|\s+$/g,"");if(f==h){if(a.length>1)g=unescape(a[1].replace(/^\s+|\s+$/g,""));return g}}return null}(d)){b=b||document.domain;c=c||"/";document.cookie=d+"=; expires="+new Date+"; domain="+b+"; path="+c}}catch(j){}};
	clearCookie('_ga','. yourdomain.com','/');
	clearCookie('_gat_gtag_YOUR_TRACKING_ID','. yourdomain.com','/');
	clearCookie('_gid','.yourdomain.com','/');
	clearCookie('__atuvc','.google.com','/');
	clearCookie('__atuvc','.google.com','/');
	setTimeout(function(){ window.location.reload(true) }, 100);
  },
`

This forces a browser window refresh, which I found necessary for the clearing of the cookies. 

Hope this helps.

**Comment by Rohaty** [comment]
Hi,
if you do not want to send data to Google Analytics unless the user agrees cookies, use the Google Tag Manager and Simo Ahava solution, which is here:

https://www.simoahava.com/gtm-tips/opt-out-of-google-analytics-tracking/
https://www.simoahava.com/gtm-tips/respect-opt-out-from-advertising-and-analytics/

Use "cookieconsent_status" as 1st Party Cookie variables. Elegant, simple, efficient.

**Comment by Reshmysandeep** [comment]
Hi all, 
I'm facing some issue using cookie consent. I have tried this code 
window['ga-disable-GA_TRACKING_ID'] = true; for disable google analytics .

If in case the browser user needs to enable it again, where I have to put the code to enable Google Analytics. Please help me on this here am sharing my code sample.

```

 window.addEventListener("load", function () {
            window.cookieconsent.initialise({
                "palette": {
                    "popup": {
                        "background": "#4c996b"
                    },
                    "button": {
                        "background": "#384c54"
                    }
                },
                revokable:true,
                "type": "opt-out",
                "content": {
                    "dismiss": "Allow Cookies",
                    "deny": "Decline",
                    "href": ""
                },
                onStatusChange: function (status, chosenBefore) {
                   
                    if (type == 'opt-out' && !didConsent)
                    {
                        gaOptout();
                    }
                    if(type == 'opt-out' && didConsent)
                    {
                        //enable cookies
                    }
                   
                },
               
            });
        });



        function gaOptout() {
            window[disableStr] = true;
            document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';

        }

    </script>
```

**Comment by dlangh** [comment]
Hi,

I struggled with this as well.  The problem with removing specific cookies is there will always be another that can popup.  I finally managed to figure this out.

Here is my code:

`function disableCookies() {
		if(!document.__defineGetter__) {
    		Object.defineProperty(document, 'cookie', {
        		set: function(){ return true; }
    			});
			}
	 	else {
	     	document.__defineSetter__("cookie", function() {} );
		 	}
		}

function enableCookies() {
		delete document.cookie; 
		}
`
I've tested in FF, Chrome and Safari and it works . I believe it will work in at least IE 8.  What took me a while to figure out with re-enabling cookies was I was trying delete the 'set' property/method directly, you have to delete the cookie object itself, which BTW does not delete anything already present before you call disableCookie(),  it simply re-exposes the original cookie object

**Comment by niuso** [comment]
Hello dlangh,
Hi. Could you explain your solution better?
Where do we insert the code? 
Thank you.
