### ISSUE TITLE
Banner color does not override with !important

### ISSUE THREAD

**Issue by Mgamerz** [insites/cookieconsent#207]
I use a reset.css on my site, and I've been noticing that even though the text colors are set using the script, the text color is not set with !important so it can be overridden by other css - I know that is probably by design, but it would be nice to have a js api where I can tell it to force it with !important (and still use your CDN).

**Comment by alexmorleyfinch** [comment]
You can always try importing the cookie consent CSS last. That should fix the specificity issue. This shouldn't affect your site either because the cookie consent CSS is prefixed with the text `cc-`.

I don't think it's necessary to add `!important` to everything rule in the CSS
