### ISSUE TITLE
add translation

### ISSUE THREAD

**Issue by jayss** [insites/cookieconsent#214]
add translation will be awesome

**Comment by alexmorleyfinch** [comment]
We allow developers to provide their own translations using the configuration options:

```
window.cookieconsent.initialise({
  // ... blah ...
  content: {
    header: 'Cookies used on the website!',
    message: 'This website uses cookies to ensure you get the best experience on our website.',
    dismiss: 'Got it!',
    allow: 'Allow cookies',
    deny: 'Decline',
    link: 'Learn more',
    href: 'http://cookiesandyou.com',
    close: '&#x274c;',
  }
})
```

It's an interesting consideration though. I'm not sure how to go about auto-translating, but it'd have to be a build step which gets injected into the distributed files

**Comment by isletadesign** [comment]
Actually I can't understand how to translate the plugin manually. I've tried adding .po and .mo files in plugin language folder (named "locale") but the popup keeps showing texts in english (default language) on other languages.

What can I do?


Thanks in advance

**Comment by amenk** [comment]
It would be awesome to have the translations in the plugin, so it can be used easier on multi language websites without additional coding. We might be able to "steal" the translations from https://github.com/ToX82/cookie-bar/tree/master/lang ?

**Comment by jHetzer** [comment]
Example to make CookieConsent manually multilingual:
`
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
	// Default Content
    var customContent = {
        "href": "http://website/Policy"
    };
	// Language specific translation e.g. German
	// Duplicate if block and change regex for other languages
    if (document.documentElement.lang.match(/^de.*$/)) {
        customContent = {
            "message": "Um unsere Webseite für Sie optimal zu gestalten und fortlaufend verbessern zu können, verwenden wir Cookies. Durch die weitere Nutzung der Webseite stimmen Sie der Verwendung von Cookies zu. Weitere Informationen zu Cookies erhalten Sie in unserer Datenschutzerklärung.",
            "link": "Mehr Erfahren",
            "dismiss": "Verstanden",
            "href": "http://website/Datenschutz"
        }
    }
    window.addEventListener("load", function() {
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": "#000",
                    "text": "#c7c7c7"
                },
                "button": {
                    "background": "transparent",
                    "text": "#c7c7c7",
                    "border": "#c7c7c7"
                }
            },
            "content": customContent
        })
    });
</script>
`

**Comment by themidithief** [comment]
@jHetzer It works fine with the translation but I get two boxes now. On the english page I get two english boxes and on the german page I get one german and one english. How can I make the duplicate box disappear?

**Comment by jHetzer** [comment]
I would recommend to add some console.logs() to see if something is called multiple times.
