### ISSUE TITLE
Geo-ip: missing countries

### ISSUE THREAD

**Issue by Zenju** [insites/cookieconsent#222]
"RO" is missing in 

      hasLaw: ['AT', 'BE', 'BG', 'HR', 'CZ', 'CY', 'DK', 'EE', 'FI', 'FR', 'DE', 'EL', 'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'SK', 'SI', 'ES', 'SE', 'GB', 'UK'],

http://cookiepedia.co.uk/cookie-laws-across-europe says:
"Romania: Law is not yet in force."

Okay, but you also include "SI", where the law also is not yet "in force".

------------------------------

"GR" is missing as an alternative to "EL"

Some geo-IP providers use this one.

------------------------------

"EU" is missing, as used by some geo-IP providers.

**Comment by alexmorleyfinch** [comment]
Thanks for the information. We will look into updating the list of countries as soon as possible

**Comment by samlin86** [comment]
+1 for Including "GR" as that is the ISO 3166 standard code.

Also puzzled by not having Romania (RO), but Slovakia is included in the list - but also "Law is not yet in force".

**Comment by alexmorleyfinch** [comment]
This is fixed in master. We will be making a new release very soon
