### ISSUE TITLE
How to use as npm bundle

### ISSUE THREAD

**Issue by on3iro** [insites/cookieconsent#223]
Hey guys,

so I can install cookieconsent as a npm bundle. But the documentation only shows how to use
the library with `script` and `link` tags in html files. What is the purpose of the whole npm installing other
than versioning then?

Is there a way to simply import the js and css files into my main.js so that they get bundled with webpack?
I would like to initialise the plugin inside my main.js file instead of putting it into our html files.

Thanks in advance

**Comment by yudao** [comment]
Hi,

I've implemented cookieconsent with my module bundler (http://www.brunch.io).
```sh
npm install --save cookieconsent
```
```javascript
import { CookieConsent } from 'cookieconsent';
document.addEventListener('DOMContentLoaded', () => {
  cookieconsent.initialise({/*... my options ...*/});
});
```

It works. But be aware it does'nt in localhost development ;)

Yu.

**Comment by philiprabbett** [comment]
How do we import the CSS?

**Comment by yudao** [comment]
Hi @philiprabbett 

It depends on your module bundler (I presume you do not have problems with manual installation).

For brunch.io I include it directly in my brunch-config.js:

```javascript
exports.npm = {
  ...
  styles: { cookieconsent: ['build/cookieconsent.min.css'] }
};
```
For webpack for example you just need to include the css into you js with require or import fort ES6.

Yu.

**Comment by alexmorleyfinch** [comment]
I think Webpack has an `externals` option for loading external libraries like this

**Comment by belvederef** [comment]
I do not think this issue should have been closed. Documentation is still lacking on npm package uses and what was suggested above does not work for me.

**Comment by molerat619** [comment]
I agree. With `jQuery` for example, I have to do this in `webpack` (pay attention to webpack.ProvidePlugin and extract):

```javascript
let mix = require('laravel-mix');
let build = require('./tasks/build.js');
let webpack = require('webpack');

mix.disableSuccessNotifications();
mix.setPublicPath('source/assets/build');
mix.webpackConfig({
    plugins: [
        build.jigsaw,
        build.browserSync(),
        build.watch(['source/**/*.md', 'source/**/*.php', 'source/**/*.scss', '!source/**/_tmp/*']),
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            cookieconsent: "cookieconsent"
        })
    ]
});

mix.js([
    'source/_assets/js/main.js',
    'source/_assets/js/contact.js',
], 'js')
    .extract([
        'jquery',
        'cookieconsent'
    ])
    .sass('source/_assets/sass/main.scss', 'css')
    .copy([
        'node_modules/@mdi/font/fonts/**/*'
    ], 'source/assets/build/fonts')
    .options({
        processCssUrls: false,
    }).version();
```

Doing the same thing for `cookieconsent` does not work though. CookieConsent is bundled into the vendor.js-file, but I can't access it in my console.log(), no matter the case I use (cookieconsent vs. cookieConsent vs. CookieConsent). 

I also made sure to run the console.log() in `$(document).ready()` to avoid timing issues.
