### ISSUE TITLE
googleoff/googleon Tags are ignored by Google Search

### ISSUE THREAD

**Issue by a-and-m** [insites/cookieconsent#224]
I had a website with multiple pages featuring the same, short meta-description. When the page showed up in the google search results, the text from the cookieconsent box message and button ("Durch Nutzung dieser Website stimmen Sie deren Verwendung zu. Mehr erfahren") are included in the result snippet:

![grafik](https://user-images.githubusercontent.com/25027175/30214618-6f6b61e8-94ad-11e7-80a9-818654fef821.png)

I suspect this has somehow to do with one of the following facts:

 * The tags are inserted via JavaScript (and I seem unable to use static tags as a workaround, because cookieconsent inserts its markup first in the body).
 * Neither the googleoff nor the googleon tag seems to have a newline or blank before them (which is required only for googleon [according to Google](https://www.google.com/support/enterprise/static/gsa/docs/admin/70/gsa_doc_set/admin_crawl/preparing.html))

Maybe there is some other workaround for this?

Environment:

www.google.at
Firefox 55.0.3, private mode
(sorry, the meta descriptions had to be changed in the meantime, so the problem can't be reproduced using aforementioned site)

**Comment by hirnschmalz** [comment]
Same problem here

**Comment by hirnschmalz** [comment]
I think a workaround could be inserting the dialog at the bottom of the page instead of the top.

**Comment by hirnschmalz** [comment]
@a-and-m Just figured out, that you already can change the location of the HTML code. See `autoAttach` in the [documentation](https://cookieconsent.insites.com/documentation/javascript-api/).

I think it would be best to place the HTML at the end of the `body` by default.
