### ISSUE TITLE
Wordpress with advanced cookie consent

### ISSUE THREAD

**Issue by KoolP** [insites/cookieconsent#229]
Added the code to the site header after building it in the wizard.
Works great as a notifier but I would need to follow the request of the site owner and include the advanced options to activate opt-in disabling cookies. They say some kind of twitter cookie goes red in their security scan of the site.

I understand this is a Javascript solution so does it mean i need to locate a javascript file in the WP theme to implement the advanced functions. Any suggestions, for a newbie in this matter? Here are the codes you refer to when enabling op-in: https://cookieconsent.insites.com/documentation/disabling-cookies/

All the best!

**Comment by Dolondro** [comment]
Hi Koo, sorry for the very delayed response, the project has gone through a period of substandard maintenance on our parts.

You would indeed need to locate where the javascript that sets the twitter cookie was set, and then wrap that code so it would only be initiated when `this.hasConsented()` is true. I can't really give more specific advice as this is really a very site specific question which isn't really in our remit to solve.
