### ISSUE TITLE
Auto dismiss if user continues the navigation

### ISSUE THREAD

**Issue by alemela** [insites/cookieconsent#230]
Looking at the current documentation I haven't seen anything that simply leads to this. Is this feature already present? Thanks!

**Comment by thexmanxyz** [comment]
@alemela autoDismiss is there but currently broken. If you want it you must apply a fix. See #170.

**Comment by alexmorleyfinch** [comment]
This is a dismissOnScroll, dismissOnWindowClick and dismissOnTimeout that will all be available in the next release, coming very soon
