### ISSUE TITLE
Give option to use classes instead of html style attribute

### ISSUE THREAD

**Issue by ThaoD5** [insites/cookieconsent#238]
Hi, we appreciate the module and this is not an issue, but more of an "advice" for easier custom setup : 

It would be great to have the option to use classes instead of direct styling in html, there are a multiple bugs with the current html inline styling : no height changing on resize, no available selector for the different cases (validated, hidden, ... )

We are, at our office, making a lot of custom designs, so it would be perfect to be able to have more "selector" for the different cases.

Hope you get what I meant, have a great day :)

**Comment by alexmorleyfinch** [comment]
I may misunderstand, but you can use classes :) The main window is `cc-window`. All buttons are `cc-btn`. Specific buttons have specific classes like `cc-allow` and `cc-deny`. You can change the message as well using `cc-message`. You can also modify the animations as well using `cc-animate`

**Comment by ThaoD5** [comment]
Yes of course but at that time I was talking about classes of the state of the cookieconsent, valid, pending or refused for example, we moved on and made our own cookie consent since then to fit our needs.

Have a great day :)
