### ISSUE TITLE
Need some assistance

### ISSUE THREAD

**Issue by nephilim75** [insites/cookieconsent#239]
Hello

thank you so much for this tool. It helps a lot!

I try to open a fancybox window by the banner but it didn't work so far. Not sure if I understood in the correct manner how to do so. 

This is working on the website itself using `<a class="fancybox fancybox.iframe" href="datenschutz.html">Datenschutz</a>`.

Now I try to do it with banner. Here is the script I use and which is not working:

```
	<script>
		window.addEventListener("load", function(){
		window.cookieconsent.initialise({
  			"palette": {
				"popup": {
      				"background": "#f3f3f3",
      				"text": "#000000"
    			},
    			"button": {
      				"background": "#fe5000",
      				"text": "#ffffff"
    			}
  			},
  			"theme": "classic",
  			"content": {
    			"message": "Diese Webseite verwendet sogenannte Session-Cookies. Diese unterstützen die Nutzererfahrung auf unseren Webseiten.",
    			"dismiss": "Verstanden.",
    			"link": "Mehr erfahren...",
				"href": "datenschutz.html"
			},
			elements: {
  				link: '<a class="fancybox fancybox.iframe" href="{{href}}">{{link}}</a>'
			}
		})});
	</script>
```

Any idea how I can get this working?

Kind regards
//neph

**Comment by defkev** [comment]
Hey @nephilim75
Just passing through

Looks like **messagelink** takes precedence over **link** causing your **link** element to never get used.

So do this:
```
messagelink: '<span id="cookieconsent:desc" class="cc-message">{{message}} <a aria-label="learn more about cookies" tabindex="0" class="cc-link fancybox fancybox.iframe" href="{{href}}" target="_blank">{{link}}</a></span>'
```
instead of:
```
link: '<a class="fancybox fancybox.iframe" href="{{href}}">{{link}}</a>'
```
And make sure `$('a.fancybox').fancybox();` gets fired, which i assume it does as you wrote:
> This is working on the website itself 

Cheers

**Comment by nephilim75** [comment]
Great! That worked immediately.

Thank you so much! :-)
