### ISSUE TITLE
bower install: The "main" field cannot contain minified files

### ISSUE THREAD

**Issue by trainoasis** [insites/cookieconsent#241]
`bower cookieconsent#*     invalid-meta The "main" field cannot contain minified files`

I reckon the package should have only non-minified files in "main", no one has this issue as well? 
Is this on purpose?

**Comment by Dolondro** [comment]
You are right, the [spec](https://github.com/bower/spec/blob/master/json.md#main) for `bower.json["main"]` does say that you shouldn't be pointing to minified files.

It will have been ignorance on our part that we linked to the minified files, but I'm not sure it's something I'd particularly rush to change.

The documentation states that you can only have 1 file of each extension (.js, .css, etc), but we seem to have setup the compilation for the CSS so it concatenates several files together then minifies, which would give us no single file to target.

As such, unless anyone has any better ideas other than migrating to SCSS purely to satisfy bower (something I am not enthusiastic to do :P), I think leaving it be is probably the best course of action.
