### ISSUE TITLE
GDPR version

### ISSUE THREAD

**Issue by erichard** [insites/cookieconsent#242]
Have you though about making a GDPR version of cookie consent ? The current state  could be a good foundation for a more generic consent gathering tool. 

To comply with the GDPR we need to 
   1. Tell the user what data are collected
   2. Who will get the data 
   3. What the data will be used for
   4. How long the data will be kept
   5. Opt-in the consent 

What do you think ?

**Comment by Jimmi08** [comment]
Hi,
if you are interested how it should looks on website, you can look here:
https://www.optanon.com/cookie-consent-manager/
Just click on Cookie settings and you will see it in action.
Nightmare.

**Comment by purch-FE** [comment]
Hello team,
Could someone have a look to @erichard request ? Are you planning to extend this lib to support GDPR requirements ? 
Thanks

**Comment by drnickyoung** [comment]
Hi All,

I do not know if this is of any use, I adapted cookieconcent for what I beleive is the basic requirement for GDPR. See - [https://github.com/drnickyoung/cookieconsent](https://github.com/drnickyoung/cookieconsent) - it basically is allow or deny rather than allow or dismiss AND changes the revoke to settings. It is therefore obvious there is a cookies settings, it makes it obvious what the current choice is and upon clicking deny ALL current cookies are deleted.

To me this is what the standard opt-in provided by cookieconsent should be.

Hope the example is of some use!

**Comment by brasileric** [comment]
For GDRP you have to have an opt-in for all the different types of cookies, like Analytics, Marketing, Preferences etc. Only core functionally cookies don't need to have an opt-in, but you still have to mentoin this. And you have to describe why the cookies are used and what they are doing. Good example: https://www.civicuk.com/cookie-control . I also read that you have to log every change of the settings of each visitor, but don't know if that's right.

**Comment by Jimmi08** [comment]
@brasileric yes, you should have, but it's depends on your type of site. This is for big companies what wants to collect at least some data. For normal site to remove all cookies except necessary cookies are ok.

That example - it's confusing. Yes. it looks great (I am waiting when people starts to add advertisiment to cookie banners if they are so big as here), but try it. I tried to rid cookies and they still there.  Funny.

**Comment by drnickyoung** [comment]
Not sure what’s confusing about the example? Either way it is a stop gap measure and I do note
I am redoing it to add options for other types  of cookies.

The civicuk one is good, correct me if I am wrong but it is hosted only, ie i you cannot download the code. Think that is what many want, an open source solution.

**Comment by drnickyoung** [comment]
Agree. Next week I will have a crack at extending the on-site one or create one from scratch

**Comment by niebau** [comment]
@brasileric 

> For GDRP you have to have an opt-in for all the different types of cookies, like Analytics, Marketing, Preferences etc.

Are you sure about that? All (german) sources I read concluded in smth like "You have to inform your visitors about cookies, and maybee you should provide some kind of opt-out".

From [it-recht-kanzlei.de](https://www.it-recht-kanzlei.de/cookies-eu-datenschutz-grundverordnung.html#abschnitt_22) (translated via Google Translate)

> Conclusion [...] In order to minimize the risk of being warned and (theoretically) avoid possible steps Google takes for violating its terms of use, the IT-Recht Kanzlei still recommends that users of the website be aware of the use of cookies through a banner and inform them that on further visit of the website from the consent of the user in the use of cookies is assumed (see this article of the IT-Recht Kanzlei)

**Comment by brasileric** [comment]
@niebau Well, not sure, I'm not a lawyer, but that's what I read about GDRP in The Netherlands. Are you sure this sources are talking about GDRP? Because this sounds like the old (current) cookie law.

**Comment by niebau** [comment]
@brasileric neither am I ;) but I'm pretty sure, at least for the situation in germany. This is a long article obout the GDPR and associated german laws. They introduced the conclusion I cited like "Nothing realy changes in our oppinion". What a mess ...

**Comment by Jimmi08** [comment]
@drnickyoung 
`Not sure what’s confusing about the example? `
That it doesn't work?  
Wrong - it's set by default as ON.   I couldn't get it OFF, after each refresh it was back to ON (I need to use CTRL-F5), but cookies still was there although it says that there could be problems with this.

**Comment by drnickyoung** [comment]
@Jimmi08 If the civicuk uk one, had issues on my dev server but live server might be different, not tried that yet to know.

@niebau in UK guidelines are clear it has to be opt-in, no opt-out or assumptions/implied, or at least that is my understanding. I thought it was same standard throughout but from what people are saying it seems countries have their own variations.

**Comment by SuN-80** [comment]
@Ruud68 Analytics cookies are not an issue if IP-Masking is enabled. You do not have to inform your visitors that you are analyzing and tracking their behavior if anonymized (there's no PII, the point of the whole new law).
See: https://developers.google.com/analytics/devguides/collection/analyticsjs/ip-anonymization

@niebau This article is totally wrong. I've met a German and a French lawyer, they both say the exact opposite. @Ruud68's comment is a good summary. ;)

Yes, it's a mess...

**Comment by alexmorleyfinch** [comment]
Yes! We are currently working on a GDPR compliant version. It shouldn't be too long away now! See [here](https://github.com/insites/cookieconsent/issues/409) for a few more details
