### ISSUE TITLE
empty style tag in head

### ISSUE THREAD

**Issue by joeaudette** [insites/cookieconsent#243]
wondering why the script appends an empty style element into the head when we are already loading an external css from the cdn?

I've tried various configuration options to see if it resulted in any actual style rules being added there but it always seems to be empty for me.

Would be nice if the script did not add the style element unless it actually is going to add style rules there.

**Comment by alexmorleyfinch** [comment]
The tag looks empty, but they are defined dynamically via javascript, therefore it is not displayed in the dev tools.
