### ISSUE TITLE
Publish version 3.0.5

### ISSUE THREAD

**Issue by pioug** [insites/cookieconsent#246]
Hello! It seems that the version has been bumped but not released on npm yet. The last version published is `3.0.4`:
https://www.npmjs.com/package/cookieconsent
https://yarnpkg.com/en/package/cookieconsent

I can pull `master` as a dependency but I think many people can benefit from the _noopener patch_ https://github.com/insites/cookieconsent/pull/209 for free if it was on the npm registry! 

If one of the maintainers could run `npm publish` 🙏

**Comment by udos** [comment]
this would really help to pass this Lighthouse audit:
![image](https://user-images.githubusercontent.com/141107/35724672-db6728d6-07fe-11e8-848b-98886e664b82.png)
note: the "Learn more" link in the screenshot points to https://developers.google.com/web/tools/lighthouse/audits/noopener

currently no one who is using cookieconsent will pass this...

**Comment by Dolondro** [comment]
(Finally!) done. My apologies for the considerable delay :P

**Comment by rejas** [comment]
Awesome. Thx!

**Comment by pioug** [comment]
Thank you @Dolondro!
