### ISSUE TITLE
REDAXO AddOn

### ISSUE THREAD

**Issue by skerbis** [insites/cookieconsent#247]
We are proud to announce that cookie consent has been released today as a REDAXO CMS AddOn. 
https://github.com/FriendsOfREDAXO/cookie_consent

THX for the Script and THX to the developers. 

![cookie consent](https://user-images.githubusercontent.com/791247/33999994-5589074a-e0ec-11e7-9f5c-893b4afc9694.png)

**Comment by No5251** [comment]
Eh, spam?

**Comment by skerbis** [comment]
No, not spam @No5251  We only wanted to Inform the creators of this super and loved script, that we've made a free AddOn for the CMS REDAXO.
