### ISSUE TITLE
mobile browsers load cc-floating instead of cc-banner

### ISSUE THREAD

**Issue by t-muir** [insites/cookieconsent#250]
The default layout setting for position is bottom. This sets the class cc-banner when using browsers on desktops (eg  user agent Chrome - Windows)

If the user agent is changed to a mobile browser (eg Chrome Android Mobile / Safari - iPhone IOS 9) the class cc-floating is set instead of cc-banner and the default styling is broken.

**Comment by Keinbockwurst** [comment]
+1

**Comment by Dolondro** [comment]
Duplicate of #277
