### ISSUE TITLE
[Irrelevant and Annoying Question] Disabling Cookies

### ISSUE THREAD

**Issue by MilesR** [insites/cookieconsent#251]
Hiya...
I've more or less abused this tool to generate a notification on my website that is similar to a cookie notification in structure, however, is not one. My website doesn't (well didn't) use cookies. As the tool plants a cookie, I would actually need a cookie notification though... Is there any way to turn off cookies? This (https://cookieconsent.insites.com/documentation/disabling-cookies/) only works if you have selected opt-in / out as far as I can tell.
Sorry for being annoying by asking a question nobody that actually used the tool as intended will run into, any help would be greatly appreciated though.
Thanks :).

**Comment by alexmorleyfinch** [comment]
I'm not sure if what your asking is possible. I'm not sure it would be a good idea to use this as a general popup, as the `cookieconsent.Popup` object is tightly coupled to cookies. If it was coded properly in the first place (oops) then it would be separate and you'd be able to use it to your hearts content.

Anyway, the only way you could do this is by copying the `cookieconsent.Popup` and rip out all the cookie related code. This is not a simple task though. You'd probably be better writing your own small popup library, or using another, or just flat out copying the HTML and CSS and bin off all the Javascript. The options are endless if you're willing to get a little down and dirty in the code.
