### ISSUE TITLE
How to add to TagManager

### ISSUE THREAD

**Issue by GusCoyne** [insites/cookieconsent#258]
I'm looking to add the Disabling Cookies;
https://cookieconsent.insites.com/documentation/disabling-cookies/

Insites linked to this, but what do i use? 
Should I download it all and add as a new container?
is there a single JSON I should import?

**Comment by alexmorleyfinch** [comment]
Sorry Gus, I'm not sure what you are asking. Users are required to hook in their own code to disable the cookies. We cannot do this for you, as it would require our tool knowing what 3rd party tools you use (which is worth an entire plugin on it's own).
