### ISSUE TITLE
lighthouse audit - links do not have descriptive text

### ISSUE THREAD

**Issue by udos** [insites/cookieconsent#259]
lighthouse (https://developers.google.com/web/tools/lighthouse/) is a pretty useful tool to audit your web app.

besides raising an issue regarding what has been fixed with pr #209 (but unfortunately not published yet -> #246) it is also raising the following:
![image](https://user-images.githubusercontent.com/141107/35748748-5aba1210-084f-11e8-8016-27738ee6d441.png)

it would be great if you could fix this as well. thanks.

**Comment by rejas** [comment]
Can be closed now that v3.0.5. is released, I presume.

**Comment by bkmitesh** [comment]
Hi,

I am having same issue, what is the solution?

Thanks

**Comment by rejas** [comment]
@bkmitesh are you using the latest version (3.0.5) ?

**Comment by bkmitesh** [comment]
@rejas, latest version for chrome?

**Comment by bkmitesh** [comment]
Hi @rejas ,

In am using following and same error in both -
1) In Version 66.0.3350.0 (Official Build) canary (64-bit)

2) Chrome - Version 64.0.3282.167 (Official Build) (64-bit) and Ligh house - Version - 2.9.0.280

**Comment by rejas** [comment]
I was asking about the version of the cookieconsent lib

**Comment by udos** [comment]
yes @rejas, this issue has been fixed. just checked, and lighthouse indicates it as a passed audit
![image](https://user-images.githubusercontent.com/141107/36590532-daee8262-1886-11e8-88f5-63c26f65afc3.png)
thanks a lot!
