### ISSUE TITLE
CSS customizations not loaded for mobile device(s)

### ISSUE THREAD

**Issue by droolcup** [insites/cookieconsent#260]
Hello everyone,

I did some CSS changes/overrides to the plugin (version 3.0.3) in a separate CSS file. Here they are:

`@media screen,
screen and (max-width: 900px),
screen and (max-width: 414px) and (orientation: portrait),
screen and (max-width: 736px) and (orientation: landscape) {
    .cc-banner {
        padding: 5px 20px !important
    }
    .cc-banner * {
        font-family: "Museo Sans W01_500", sans-serif !important
    }
    .cc-banner .cc-btn:last-child {
        min-width: 0 !important;
        border-width: 0 !important
    }
    .cc-banner .cc-message {
        font-size: 75% !important;
        text-align: center !important
    }
    .cc-banner .cc-icon {
        margin-right: 8px !important;
        margin-top: -3px !important
    }
    .cc-banner a {
        color: #fff !important;
        text-decoration: underline !important;
        font-weight: normal !important
    }
    .cc-banner .cc-dismiss {
        font-weight: normal !important;
        text-decoration: none !important;
        font-size: 150% !important;
        line-height: 0.4 !important
    }
}`

However, when viewing the website via smartphone (or device toolbar of Google Chrome) the changes I made are not considered. It just looks like I didn't do any extra styling at all.

I guess there is some kind of device detection in the JS file preventing my stylings to be executed? Actually, I don't want to touch that code since I'm lacking JS knowledge, but I'm willing to alter/delete the according code if someone could point me to the right lines.

Is there any other way to make my custom CSS working on all devices?

**Comment by droolcup** [comment]
I also have the same issue as described here: https://github.com/insites/cookieconsent/issues/257

As said before, I'd like the notice to be shown equal on all devices. Thanks in advance for possible help!

**Comment by droolcup** [comment]
Please close/delete. I have found CSS classes to edit, in order to adress all devices AND get rid of floating optic for tablet.

**Comment by OldManBrook** [comment]
Hi, how did you resolve this problem?
