### ISSUE TITLE
Internet Explorer 10/11 Button issue not fixed by version 3.0.6

### ISSUE THREAD

**Issue by AndreKoot** [insites/cookieconsent#263]
Hi,

I tested version 3.0.6 on Internet Explorer 11 and it seems that the button issue in IE10 and IE11 is not fixed by version 3.0.6.

I have also tried the suggestions mentioned here https://github.com/insites/cookieconsent/pull/232, https://github.com/insites/cookieconsent/issues/231

Anyone got consent buttons displaying properly in IE10 and IE11?

Thank you.

André

**Comment by thexmanxyz** [comment]
@AndreKoot #231 just fixed the issue for the banner layout. I already noticed that later. Which layout did you test?

**Comment by jblank1** [comment]
Hello,
I wonder if there are any news on this? How can we enable the great Cookies Consent code to also work with IE versions 10 and 11?
Many thanks

**Comment by thexmanxyz** [comment]
@jblank1 no news from official side but I will create an extension for all layouts. See my PR on banner layout which work for ie10  and ie11

**Comment by jblank1** [comment]
@thexmanxyz - thank you so much! Sorry, am not experienced. So would I have to copy the referred CSS code prior to the one you would generate from Insites Cookies Consent?

**Comment by thexmanxyz** [comment]
@jblank1 after the original code or replace the original code

**Comment by jblank1** [comment]
@thexmanxyz : thank you :)

**Comment by Dolondro** [comment]
Closing as duplicate of #326

**Comment by thexmanxyz** [comment]
@AndreKoot @jblank1 fixed with v3.1.0
