### ISSUE TITLE
Wrong cookie value in `opt-in` type widgets

### ISSUE THREAD

**Issue by albertborsos** [insites/cookieconsent#265]
I think it is some confusion with the default labels.

Based on the [compiance type documentation](https://cookieconsent.insites.com/documentation/compliance/) it said:

| compliance type | used word in documentation | cookie value in browser | is it good? | suggested type | comment |
| - | - | - | - | - | - |
| info | accept | `dismiss` | yes || `dismiss` means "it's OK" |
| opt-out | disable | `deny` | yes ||
| opt-out | dismiss | `dismiss` | yes || `dismiss` means "it's OK" |
| opt-in | refuse | `dismiss` | NO | `deny` | `dismiss` means "refuse" (???) |
| opt-in | enable | `allow` | yes |||

If you change this, then the label will be more accurate, because in `opt-in` type widgets instead of this:
![kepernyofoto 2018-02-28 - 7 59 13](https://user-images.githubusercontent.com/7307145/36774213-60e1bcb6-1c5d-11e8-9051-79701f0c4ddf.png)

Will be this:
![kepernyofoto 2018-02-28 - 7 59 39](https://user-images.githubusercontent.com/7307145/36774220-6950153c-1c5d-11e8-83d4-4d7ad6a02988.png)

Which means I do not have to change the `dismiss` button's label to `deny` button's label if the compliance type is `opt-in`.

**Comment by Jimmi08** [comment]
I fully agree.  People are used to click on Got it because old cookie policy.   But solution for this is to change label for button Dismiss if you use opt-in type.

**Comment by albertborsos** [comment]
This is a workaround, not a solution. With this workaround it is still hard to build a logic based on the stored value in `cookieconsent_status` cookie.

Check my comment in my widget:
https://github.com/albertborsos/yii2-gdpr-cookie-consent/blob/master/src/Component.php#L167

This is very confusing :D

**Comment by alexmorleyfinch** [comment]
Hey, sorry for the confusion. The idea is that `deny` is always "no consent" and `allow` AND `dismiss` are BOTH "accept". The reason we have a differentiation between `allow` and `dismiss` is because `allow` implies 'explicit' consent, and `dismiss` implies 'implicit' consent. Something that was deemed usefully but appears to be mostly confusing
