### ISSUE TITLE
How to initialize it

### ISSUE THREAD

**Issue by debute** [insites/cookieconsent#267]
Followed instruction on https://cookieconsent.insites.com/download/ but no help.

Here is the demo: https://jsfiddle.net/jhoworum/1/

All I get is this:
Uncaught TypeError: Cannot read property 'initialise' of undefined

What now?

**Comment by debute** [comment]
I found out that Adblock Plus is blocking it.

**Comment by kegelm** [comment]
Problem solved by changed the version of the script

from
`<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>`
to
`<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>`
