### ISSUE TITLE
Where to implement "Disabling cookies" code (in Magento)

### ISSUE THREAD

**Issue by aurel5542** [insites/cookieconsent#269]
Hello, first I think Cookie consent is great but I dont know where I have to place the code from "https://cookieconsent.insites.com/documentation/disabling-cookies/"

Do I need to place the code within the 

"<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
....
"
?

I use magento and added the banner code in System -> configuration -> Design -> Scripts...

**Comment by KeithP** [comment]
@aurel5542 you can place the code in the initialiser code, like this:
<script src="https://gist.github.com/KeithP/44b7ac4555f18f6a767788243071fb35.js"></script>

**Comment by aurel5542** [comment]
Hello @KeithP thanks for your reply. Do you know where this script "https://gist.github.com/KeithP/44b7ac4555f18f6a767788243071fb35.js" has to be placed in the Magento software?  Just place the link in System -> configuration -> Design -> Scripts... ? Thank you and best regards Aurel

**Comment by KeithP** [comment]
@aurel5542 I am not familiar with Magento. 
In principle you include the script code, then you need to initialise cookieconsent.
If you look at this documentation page: https://cookieconsent.insites.com/documentation/javascript-api/
the first example includes the css and js code, then within script tags it performs window.cookieconsent.initialise. each option passed in is comma separated. In this example only one of the events is included: onStatusChange: function(status) { ... but you can include all 3 events if you wish, as listed on "https://cookieconsent.insites.com/documentation/disabling-cookies/"

**Comment by aurel5542** [comment]
Dear @KeithP thanks so much for your support! One last question: Is there a way to test if it works? Because even if I do not include the code and press "Disable Cookies" the cookie banner vanishes but it can't work because the disabling code is not included
