### ISSUE TITLE
What does cookie expiration of -1 really mean?

### ISSUE THREAD

**Issue by spartan218** [insites/cookieconsent#272]
According to documentation cookies (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) 

Cookies have to have an expiration date.

How does setting expiry -1 actually make the cookie never expire or am I mis understanding the doc?

**Comment by flm-berlin** [comment]
I also came across this. The documentation note "(specify -1 for no expiry)" is wrong since -1 result in the following code:

` var exdate = new Date();
      exdate.setDate(exdate.getDate() + (-1 || 365));`

So the cookie is immediately expired.

**Comment by FlorentMasson** [comment]
This issue should be renamed: documentation is wrong about -1 value for cookie.expiryDays
