### ISSUE TITLE
Dismiss button doesn't work on Firefox

### ISSUE THREAD

**Issue by martinhellwagner** [insites/cookieconsent#276]
I have implemented a very simple example of the Cookie Consent bar, which is working great on Chrome and Safari. However, on Firefox the _dismiss_ button (labelled "OK" in my case) doesn't actually dismiss the cookie bar. The page's cookie is added to the list of cookies just like it should, though (so the bar is also gone when the page is reloaded).

```
import 'cookieconsent';

window.addEventListener('load', () => {
    window.cookieconsent.initialise({
        'content': {
            'message': 'Some intelligent message about cookies.',
            'link': 'Learn more',
            'href': '/imprint',
            'dismiss': 'OK'
        }
    });
});
```

I'm using the Firefox 59.0 (which I believe is the newest version).

**Comment by HannesSE** [comment]
I can confirm the issue (i.e. I have the same problem).

The opt-in cookie banner works in Chrome but not in the latest Firefox version. The status is not saved in Firefox.

**Comment by martinhellwagner** [comment]
Is there any workaround or solution for this bug yet?

**Comment by martinhellwagner** [comment]
I've written a small (albeit hacky) workaround, but would prefer a "proper" solution:

```
// Workaround for Firefox and IE
const cookieBar    = document.getElementsByClassName('cc-window')[0];
const cookieButton = document.getElementsByClassName('cc-btn cc-dismiss')[0];
cookieButton.addEventListener('click', () => {
    cookieBar.style.display = 'none';
});
```

**Comment by Dolondro** [comment]
I've tested this with our latest release in Firefox 61 and can't replicate it.

If this issue persists, please respond + tag me.
