### ISSUE TITLE
Can Someone Please Help Me With Location?

### ISSUE THREAD

**Issue by MartyD23** [insites/cookieconsent#278]
Hi, I have the following code using location 'true' but with the location addition it prevents the CC bar from displaying. How do i get this working correctly? I'm using Cloudflare. Thanks!

`<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#000"
    },
    "button": {
      "background": "#f1d600"
    }
  }
location: true,
})});
</script>`

**Comment by Bavaresco** [comment]
I have the same problem, location:true isn't work...

**Comment by alexmorleyfinch** [comment]
This is the intended behaviour if you are in a European country. Where are you running this code from? If you turn `location: true` and the banner doesn't show, it's probably because it's not supposed to show in your location.

You need to check what country code the location service is returning

**Comment by MartyD23** [comment]
I am running this from the UK, so it should show in my country.

**Comment by alexmorleyfinch** [comment]
You'll have to verify the response from the Location service, as you may be in the UK, but dodgy things could be happening with your IP, or you could be using a VPN which could affect the location service. If the country code returned is UK, then it should function correctly. I am in the UK and it works correctly for me. Let me know if you still have issues and I'll set up a test case

**Comment by MartyD23** [comment]
Hi Alex, could it be possible that this doesn't function with a caching plugin enabled? Or if using Cloudflare?

**Comment by MartyD23** [comment]
@Dolondro 

Thanks for your help.

**Comment by Bavaresco** [comment]
With 3.1.0 the feature 'location' is working!
