### ISSUE TITLE
Revoke Button Text

### ISSUE THREAD

**Issue by drhickerson** [insites/cookieconsent#279]
The Revoke Button text should be editable, and not Cookie Policy, which doesn't explain what it's form. 

I would recommend it say "Revoke Cookies" or even better, have it be a smaller, float-on-scroll button on the side of the browser with a + sign or maybe of a cookie with the "no smoking" circle/slash  that expands out to show "Revoke Cookies".

This would be a more familiar location for the tab, regardless of where the full alert is located and the text itself makes more sense than what it is now.

**Comment by udegbunamchuks** [comment]
> The Revoke Button text should be editable, and not Cookie Policy, which doesn't explain what it's form.
> 
> I would recommend it say "Revoke Cookies" or even better, have it be a smaller, float-on-scroll button on the side of the browser with a + sign or maybe of a cookie with the "no smoking" circle/slash that expands out to show "Revoke Cookies".
> 
> This would be a more familiar location for the tab, regardless of where the full alert is located and the text itself makes more sense than what it is now.

If you still wish to change it you do you by adding "policy":"Cookie Policy" to content options. Like

`"content": {
    "message": "This website uses cookies.",
    "dismiss": "Close",
    "link": "More Info",
    "href": "https://www.patchworkoftips.com/cookie-policy/",
	"target":"_blank",
	"policy":"Cookie Policy"`

Just change Cookie Policy to whatever text you like
