### ISSUE TITLE
Disabling cookies / not working

### ISSUE THREAD

**Issue by mcsteGitHub** [insites/cookieconsent#281]
where to add the code exactly?

(but HEAD is working fine)

**Comment by geo-mac** [comment]
Yes, same issue. Basic banner working very nicely but can't get the callback to work. Probably missing something obvious but even an example of the site would be useful...? Terrific work though!

**Comment by alexmorleyfinch** [comment]
Users must implement the blocking of the cookies themselves. We cannot know what cookies you use and thus that makes it hard for us to disable them for you.

We are currently working on a new plugin that is GDPR compliant and will disable your cookies automatically for you. We are still working on this

**Comment by petilodie** [comment]
> Users must implement the blocking of the cookies themselves. We cannot know what cookies you use and thus that makes it hard for us to disable them for you.

What you mean with blocking of the cookies is not clear to me. How can we disable a cookie that is sent from the server with every request? Shouldn't it be handled on the server side?

So when using cookieconsent, should I send a request to the server in the callback to let the backend know about the user has disabled the cookie?

What about third party cookies that we don't have control on?
