### ISSUE TITLE
Small window below disappears completely after reload

### ISSUE THREAD

**Issue by ghost** [insites/cookieconsent#288]
When I click one of the two buttons, the window minimizes to the bottom right. When reloading the page, the small window is no longer there. Is there a setting that the option is always there?

**Comment by yang-jandro** [comment]
I was wondering the same thing.

**Comment by yang-jandro** [comment]
@harryshipton don't think I follow. Do you know the commit that fixes the problem?

**Comment by shirokoweb** [comment]
@yang-jandro see PR #261
