### ISSUE TITLE
Options for which cookies to block

### ISSUE THREAD

**Issue by GabrielDumbrava** [insites/cookieconsent#289]
I don't know if this an issue anymore, but upgrading form older versions I noticed that I don't have the option to allow user to only allow certain type of cookies.

Is there a setting not documented, or this option is not available anymore? I would really like to use certain mandatory cookies, but allow the users to not use tracking cookies, for example.

**Comment by zevnikrok** [comment]
I am also interested in this option, since I believe it is required for GDPR compliance.

**Comment by alexmorleyfinch** [comment]
Users must implement the blocking of the cookies themselves. We cannot know what cookies you use and thus that makes it hard for us to disable them for you.

We are currently working on a new plugin that is GDPR compliant and will disable your cookies automatically for you. We are still working on this

**Comment by GabrielDumbrava** [comment]
The request was not to block the cookies yourself, but have those options like "necessary", "social", "tracking", etc, which users may check themselves. According to their option I could load or not load certain scripts.
In the new version of cookie consent there is only the option to agree or not to cookies generally.

**Comment by alexmorleyfinch** [comment]
Ah sorry, my bad. Yes there is currently no way to do this in V3 and no plans to do it either, as CookieConsent was originally designed to work with the "ePrivacy Directive". We are writing a new plugin that will be GDPR compliant. When that comes out, CookieConsent will be deprecated
