### ISSUE TITLE
cookieconsent_status cookie not mentioned in any documentation

### ISSUE THREAD

**Issue by jamieburchell** [insites/cookieconsent#294]
I might just be blind, or stupid (or both), but nowhere on the website, the wizard or the documentation does it tell you how to actually disable or remove cookies. I guess this is left up to your own implementation, but the `cookieconsent_status` cookie which could be used server-side to facilitate this isn't mentioned anywhere.

Edit: OK, there is a reference to it here (https://cookieconsent.insites.com/documentation/javascript-api/#cookie_options) but it's not particularly obvious that this cookie is set without hunting through the JavaScript API.

In the JavaScript callback code, I see the placeholders/comments for `// enable cookies` and `// disable cookies` ... but how? A simple sample implementation would be useful.

**Comment by Dolondro** [comment]
This is discussed further [here](https://github.com/insites/cookieconsent/issues/387#issuecomment-405594539)
