### ISSUE TITLE
Create revoke link

### ISSUE THREAD

**Issue by NouvelleTechno** [insites/cookieconsent#295]
Hello,

I've been searching for a while on how to create a revoke link that I could put in my privacy policy (like <a href="#">Revoke cookies</a>) with an event listener...

What function should I run to revoke cookies?

Thanks

**Comment by NouvelleTechno** [comment]
Finally found an option to delete the cookie and refresh the page, that works, but I'm not sure it's a good practice

**Comment by alexmorleyfinch** [comment]
You can delete all cookies using this snippet:

```
            var res = document.cookie;
            var multiple = res.split(";");
            for(var i = 0; i < multiple.length; i++) {
               var key = multiple[i].split("=");
               document.cookie = key[0]+" =; expires = Thu, 01 Jan 1970 00:00:00 UTC";
            }
```
