### ISSUE TITLE
Support to translate Cookie Policy text

### ISSUE THREAD

**Issue by filips123** [insites/cookieconsent#296]
Add support to translate Cookie Policy text, when Opt-In or Opt-Out is selected.
![slika](https://user-images.githubusercontent.com/16626308/39053801-30cb5fac-44b0-11e8-8b60-7bf0b597e0a0.png)

**Comment by eduardoinnorway** [comment]
Just pass in a text object with the translated text you want to "content"

**Comment by filips123** [comment]
I want to translate text "Cookie Policy".

In the source code, this is [`revokeBtn`](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L242) variable:
```
// This is the html for the revoke button. This only shows up after the user has selected their level of consent
// It can be enabled of disabled using the `revokable` option
revokeBtn: '<div class="cc-revoke {{classes}}">Cookie Policy</div>',
```

You should change it to something like
```
revokeBtn: '<div class="cc-revoke {{classes}}">{{revoke}}</div>',
```
And then replace `{{revoke}}` with translated text, like for other HTML elements with text.

Also, this should be in download wizard (https://cookieconsent.insites.com/download/).

**Comment by Dolondro** [comment]
Building a translation layer into cookieconsent itself is not something we'd currently consider implementing.

if you want this functionality, put your different translated strings directly into the configuration when initialising CookieConsent.
