### ISSUE TITLE
New add feature: move cookie consent div box

### ISSUE THREAD

**Issue by philanthr92** [insites/cookieconsent#298]
It is better if user can move cookie consent div box.

**Comment by harryshipton** [comment]
If this were to be done, then it should be a position option in my opinion. Not all styles are suited to having moveable elements on the page.

**Comment by Dolondro** [comment]
This isn't a feature we'd consider adding at the moment. Ideally we would want the user to either accept or decline the cookies, not drag around the box to keep the page in limbo.
