### ISSUE TITLE
Opt in to Cookies

### ISSUE THREAD

**Issue by MikeGorton** [insites/cookieconsent#302]
Has anyone managed to get the opt-in working? Are there any live examples?

I tried to use the following code using an example from another poster looks fine, but does not stop or delete the analytics cookies.

Any ideas? thanks.

<link rel="stylesheet" type="text/css" href="cookieconsent/cookieconsent.min.css" />
<script src="cookieconsent/cookieconsent.min.js"></script>
<script>
function clearCookie(d,b,c){try{if(function(h){var e=document.cookie.split(";"),a="",f="",g="";for(i=0;i<e.length;i++){a=e[i].split("=");f=a[0].replace(/^\s+|\s+$/g,"");if(f==h){if(a.length>1)g=unescape(a[1].replace(/^\s+|\s+$/g,""));return g}}return null}(d)){b=b||document.domain;c=c||"/";document.cookie=d+"=; expires="+new Date+"; domain="+b+"; path="+c}}catch(j){}};
window.addEventListener("load", function(){
	window.cookieconsent.initialise({
	"palette": {
		"popup": {
		"background": "#000000"
	},
	"button": {
		"background": "#c19d26",
		"text": "#000000"
	}
	},
		"position": "bottom-left",
		"type": "opt-in",
		"content": {
			"message": "This website uses cookies to ensure you get the best experience on our website",
			"dismiss": "",
			"allow": "Allow Cookies",
			"link": "Learn more",
			"href": "cookies-policy.html"
		},
		"revokeBtn": "<div class='cc-revoke @{{classes}}'>Deactivate Cookies</div>",
		onInitialise: function (status) {
		var type = this.options.type;
		var didConsent = this.hasConsented();
		if (type == 'opt-in' && didConsent) {
			// enable cookies
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());
			gtag('config', 'UA-XXXXXXX-X');
		}
		},
		
		onStatusChange: function(status, chosenBefore) {
		var type = this.options.type;
		var didConsent = this.hasConsented();
		if (type == 'opt-in' && didConsent) {
			// enable cookies
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());
			gtag('config', 'UA-XXXXXXX-X');
		}
		},
		
		onRevokeChoice: function() {
		var type = this.options.type;
		if (type == 'opt-in') {
			// disable cookies
				clearCookie('_ga','.mydomain.co.uk','/');
				clearCookie('_gat_gtag_UA-XXXXXXX-X','.mydomain.co.uk','/');
				clearCookie('_gid','.mydomain.co.uk','/');
				// Get an array of cookies
				var arrSplit = document.cookie.split(";");
				for(var i = 0; i < arrSplit.length; i++)
				{
					var cookie = arrSplit[i].trim();
					var cookieName = cookie.split("=")[0];
					// If the prefix of the cookie's name matches the one specified, remove it
					if(cookieName.indexOf("ssupp.") === 0) {
						// Remove the cookie
						document.cookie = cookieName + "=; Max-Age=-99999999;";
					}
				}
			}
		},
	})});
</script>

**Comment by louischausse** [comment]
I have the same question. I found the code on Cookie Consent website, but I don't know where to paste it to make it work.

https://cookieconsent.insites.com/documentation/disabling-cookies/

Should I paste this snippet right into the cookie bar snippet or elsewhere on my site?

Do I need to paste it "as is"? Or I need to specify which cookies should be disabled/enabled.

**Comment by eleumas** [comment]
follow!

**Comment by alexmorleyfinch** [comment]
Unfortunately there are no live examples of actual cookies being enabled/disabled, only examples of usage and appearance. It looks like you've put your code in the correct place though. It's hard to know where the script is failing. You could put `console.log` in the onStatusChange and onRevokeChoice callbacks to see if they are being called at the right times?
