### ISSUE TITLE
Cookie Consent by silktide is deteced as "tracker" by Ghostery browser plugin

### ISSUE THREAD

**Issue by derBoogie** [insites/cookieconsent#303]
Hi,
Cookie Consent by silktide is deteced as "tracker" by Ghostery browser plugin.
Can the detection be switched off or supressed?

**Comment by dreadedhamish** [comment]
This needs to happen at Ghostery's end I'd assume.

**Comment by ecoron** [comment]
it's listed in the Ghostery database as essential, only the Ghostery-Team (https://github.com/ghostery/ghostery-extension) can switch off the detection.

**Comment by Dolondro** [comment]
This isn't something we can do anything about, sorry :(
