### ISSUE TITLE
Script for disabling cookies (opt-in / opt-out)

### ISSUE THREAD

**Issue by webprogrammierer** [insites/cookieconsent#306]
Need a script or code snippet for disabling cookies (for opt-in and opt-out cases).

Thank you very much.

**Comment by louischausse** [comment]
This is provided on the Cookie Consent website:

https://cookieconsent.insites.com/documentation/disabling-cookies/

My question regarding this is: **Should I paste that code right into the snippet provided by Cookie Consent or elsewhere on my site?**

**Comment by otrelin** [comment]
I am also interested in this question.
Is your plugin provide disabling cookies on the site or I have to write my own code in callbacks?

**Comment by niebau** [comment]
You have to implement it by yourself. For opt-in, how should cookieconsent know, which scripts to load or cookies to allow? 

For opt-out, I'm using the aproach to expire all cookies that are not crucial for the site to remain functional. You may have a look at [the script of this fork](https://github.com/drnickyoung/cookieconsentexample/blob/master/examples/myscript.js) for a first idea of how you can achive this.

But note, there is no perfect way to delete all all of the users cookies. From [the js-cookie FAQ](https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#how-to-remove-all-cookies);

> It's not possible to remove literally all cookies from the user's browser. Some of them might have been created with a separate domain or path attribute than the one the user is currently in or even created with the httpOnly attribute and therefore they might not be visible.

If you want to give it a try, maybe this [solution from stackoverflow will help](https://stackoverflow.com/a/33366171/9517871).

**Comment by TheSteg94** [comment]
I also struggled with this, as I wanted an actual opt-in function. I finally worked around this hosting it on my own website and using Google Tag Manager. If you have your Cookies (like GA, Facebook etc.) set up in GTM, it is relatively easy to create an opt-in function.

In that case you can set new triggers such that when the event "cookieconsent_status" equals "allow" the cookies/tags you want are fired. 

It is basically an adoption/combination of these sources: https://stuifbergen.com/2016/07/google-tag-manager-cookie-consent-dialog/ and https://www.analyticsmania.com/post/google-tag-manager-cookie-consent/.

Hope it might help out some people

**Comment by katmarketing** [comment]
@julianchristmas this doesn't seem to work?

**Comment by julianchristmas** [comment]
@klhkm if you go to https://meetintelligo.com you will be able to see the script in action with working tracking codes :-)

**Comment by klhkm** [comment]
@julianchristmas I can see it working correctly on that site but the above code doesn't send anything to the console log.

**Comment by julianchristmas** [comment]
Thanks for the heads up @ultrono , you are ever so right. 
I have updated the script, so it now uses the onStatusChange hook as well. 

Furthermore, I nested all the tracking scripts in a function for a bit cleaner look and feel. 

For reference please see this snippet: 
```
<script>
function trackingScripts() {
				// Tracking codes
 }
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#efefef",
      "text": "#404040"
    },
    "button": {
      "background": "#8ec760",
      "text": "#ffffff"
    }
  },
  "type": "opt-in",
  "content": {
    "message": "Hjemmesiden bruger cookies for at forbedre din oplevelse, vurdere brugen af de enkelte elementer på siden og til at støtte markedsføringen af vores services. Er det i orden med dig?",
    "dismiss": "Fjern bjælke",
    "allow": "Ja, tillad cookies",
    "link": "Læs mere",
    "href": "https://meetintelligo.com/legal/privacypolicy"
  },
  onInitialise: function (status) {
		 var type = this.options.type;
		 var didConsent = this.hasConsented();
		 if (type == 'opt-in' && didConsent) {
			trackingScripts()

		  }
		  if (type == 'opt-out' && !didConsent) {
		    // disable cookies
		  }
	},

  onStatusChange: function(status, chosenBefore) {
	  	  var type = this.options.type;
		  var didConsent = this.hasConsented();
		  if (type == 'opt-in' && didConsent) {
		    trackingScripts()
		  }
		  if (type == 'opt-out' && !didConsent) {
		    // disable cookies
		  }
},		
})
});
</script>
```

**Comment by clayteller** [comment]
I've effectively set up opt-in using Google Tag Manager the same way @TheSteg94 described.

**Comment by Dolondro** [comment]
This is discussed further [here](https://github.com/insites/cookieconsent/issues/387#issuecomment-405594539)
