### ISSUE TITLE
Customize font size and css

### ISSUE THREAD

**Issue by webprogrammierer** [insites/cookieconsent#307]
How to customize font size and other css styling?

**Comment by mediengestalter2** [comment]
You can customize the colors with the init-Script. See [Documentation of Javascript-API](https://cookieconsent.insites.com/documentation/javascript-api/)

` window.cookieconsent.initialise({
palette: {
  popup: {background: '#000000', text: '#fff', link: '#fff'},
  button: {background: 'transparent', border: '#f8e71c', text: '#f8e71c'},
  highlight: {background: '#f8e71c', border: '#f8e71c', text: '#000000'},
}
  });`

I would change everything else with your own CSS.

**Comment by alexmorleyfinch** [comment]
You can also customise using CSS. There are a few CSS classes defined on the popup. There is `cc-window`, `cc-revoke`, `cc-btn` and `cc-message`.

I.E

```
.cc-window {
  font-size: 20px;
  color: pink;
}
```

**Comment by Parisa1985** [comment]
> window.cookieconsent.initialise({ palette: { popup: {background: '#000000', text: '#fff', link: '#fff'}, button: {background: 'transparent', border: '#f8e71c', text: '#f8e71c'}, highlight: {background: '#f8e71c', border: '#f8e71c', text: '#000000'}, } });

How to change the font in that code please?
