### ISSUE TITLE
Read more link without "_blank" target

### ISSUE THREAD

**Issue by webprogrammierer** [insites/cookieconsent#308]
How can I remove "target=_blank" within the read more link?

**Comment by mediengestalter2** [comment]
See [Documentation of Javascript-API](https://cookieconsent.insites.com/documentation/javascript-api/)

Adding this should do it!
` window.cookieconsent.initialise({
elements: {
  link: '<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}">{{link}}</a>',
}
  });`

**Comment by jeanpiet** [comment]
I'm having the same problem. I've tried the 'elements' solution but the link still opens in a new window, even when I change the target to anything but "_blank". I've checked the source code and the aria-label is also not overwritten by mine.
Just to check whether I've done it right:

 content: {
    message: '***message here***',
    dismiss: 'OK',
    link: 'more information',
    href: '***url here***'
  },
   elements: { link: '<a aria-label="more info" tabindex="0" class="cc-link" href="{{href}}">{{link}}</a>'},

**Comment by proshot2017** [comment]
@jeanpiet Can you give us the **complete** code here please! I can't get it! Thanks

**Comment by jeanpiet** [comment]
@proshot2017 Sorry, I opted for a paid solution instead, so I no longer have the script.
