### ISSUE TITLE
Move revoke button

### ISSUE THREAD

**Issue by bobi33** [insites/cookieconsent#309]
How do you add the revoke button to somewhere else? For example, inside the actual pop-up, so that the allow and dismiss appear, but if allow is chosen, then the revoke button replaces them...or even if the revoke button is always present with the allow and dismiss?

**Comment by drnickyoung** [comment]
My example at https://github.com/drnickyoung/cookieconsentexample might be of interest.

**Comment by bobi33** [comment]
Hi, thanks, I will. 

Do I have to use the custom css though, or does it rely on the link to the css provided by insites?

I just would like to position the revoke button either at the bottom of the cookie policy menu, or in another position where it doesn’t block a site’s logo when on mobile.

**Comment by drnickyoung** [comment]
It uses the insite CSS and the custom CSS. It is only an example of altering/overriding the settings so you can integrate the code and CSS into your own.

**Comment by alexmorleyfinch** [comment]
You can move it by making a CSS rule

```
.cc-revoke {
  left: 50%
  OR left: 200px;
  OR top: 100px
}
```

etc
