### ISSUE TITLE
Banner top push down with centered content

### ISSUE THREAD

**Issue by iecwebmast** [insites/cookieconsent#311]
Hello,
How can I center the content in the banner top push down?  The message text and the button are too far apart from each other on large screens.  I would like to have something like this...
***************************************************************************
                        cc-message(text) | cc-compliance(button)
****************************************************************************
Thank you in advance for your help.
Laila

**Comment by alexmorleyfinch** [comment]
You can do something like this:

```js
      // your options ...

      layouts: {
        basic: '<div class="cc-message-wrapper">{{messagelink}}{{compliance}}</div>',
      },

      layout: 'basic'
```

```css
.cc-message-wrapper {
  max-width: 960px; // or whatever value you like
}
```
