### ISSUE TITLE
revoke button doesnt appear after page refresh

### ISSUE THREAD

**Issue by ahm-3d** [insites/cookieconsent#312]
i have tested the code below both locally and a on a live website:

```
<script type="text/javascript">
  window.addEventListener("load", function(){
  window.cookieconsent.initialise({
    palette: {
      popup: {
        background: "#000"
      },
      button: {
        background: "#f1d600"
      }
    },
    theme: "classic",
    revokable: false,
    type: "opt-out",
    //autoAttach: false,
    content: {
      message: "This website uses cookies to ensure you get the best experience on our website.",
      dismiss: "Got it!",
      deny: "Decline",
      link: "Privacy Policy",
      href: "#cookiepolicy"
    },
    onInitialise: function (status,options) {
      var type = this.options.type;
      var didConsent = this.hasConsented();
      if (type == 'opt-out' && !didConsent) {
document.getElementsByClassName("cc-revoke")[0].style.display = "block";  
      }
    },
    onStatusChange: function(status, chosenBefore) {
      var type = this.options.type;
      var didConsent = this.hasConsented();
      if (type == 'opt-out' && !didConsent) {

      }
    },
    onRevokeChoice: function() {
      var type = this.options.type;
      if (type == 'opt-out') {

      }
    }
  })});
  </script>
```

However the revoke button disappears every time i refresh the page. i believe this shouldn't be how it works. either the cookie notice banner or the revoke button should be displayed all the time to provide the user and easy way to change the cookie settings at all time.

am i missing an option or is my code above wrong which is not allowing me to see the revoke button. (the revoke button only gets displayed after you  select 'Decline' or 'Got it').

i tried adding a onInitialise callback, thinking that i could force the revoke button to be 'display: block;' on refresh but it appears that the onInitialise callback gets triggered before the element is added to the page which is erroring 'document.getElementsByClassName(...)[0].style is undefined'.

**Comment by Ruud68** [comment]
can you check if #261 fixes this for you?

**Comment by ourmaninindia** [comment]
I use opt-in and indeed this finally did it for me. It was not just a page refresh but also when you move to another page in the site

setTimeout(function() {
      document.getElementsByClassName("cc-revoke")[0].style.display = "block";
});

**Comment by mcdappdev** [comment]
This fix worked for me - would love to see it merged!

**Comment by alexmorleyfinch** [comment]
This has been fixed and will be available in the next release coming soon!
