### ISSUE TITLE
cookieconsent not working with prototype js

### ISSUE THREAD

**Issue by WOLKENBRUCH** [insites/cookieconsent#315]
Hi!
I'm currently working on an old website to update it to the new privacy regulations. 
But unfortunately cookie consent is not working. I tracked the problem down to the prototype.lite.js library which is loaded in the head. If I remove it cookie consent works. 
Has anybody encountered something similar and knows a fix or workaround?
THANKS!

**Comment by Dolondro** [comment]
Without further details this isn't something we can easily help with. Issues with prototype.js are normally to do with missing `hasOwnProperty` checks and as far as I can see the codebase isn't lacking in them at the moment.

If you provide a narrowed down test case we can potentially help further, but as it is, I'll close this issue for the time being.
