### ISSUE TITLE
Opt Out Not Working

### ISSUE THREAD

**Issue by FSCreatives** [insites/cookieconsent#316]
I've been trying to figure out how to let the use the opt out function using the disable cookies script.

However it just doesn't appear to work no matter what I try, so I'm resolved to the fact that I'm doing something wrong.

The 4 cookies (all related to Google Analytics) I want to disable if the user chooses to are :
_ga
_gat
_gid
collect

The website is wordpress based and currently uses Google Analytics Dashboard v5.3.3 plugin to implement this.

Can anyone tell me were I've gone wrong?

	
	
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
	"cookie":
		{
		"domain": `".localhost:8888/XXXXXXX-XX/",`
		"expiryDays": "365"
			},
  "palette": {
    "popup": {
      "background": "#343c66",
      "text": "#cfcfe8"
    },
    "button": {
      "background": "#f71559"
    }
  },
  "theme": "edgeless",
  "type": "opt-out",
  "content": {
	  "deny": "Decline Cookies",
    "href": "/policy"
  },
	
  onInitialise: function (status) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    // enable cookies
  }
  if (type == 'opt-out' && !didConsent) {
    // disable cookies
	  
	// Google Analytics
	  
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-XXXXXXX-XX', 'auto');
  ga('send', 'pageview');
	  
	// End Google Analytics
	  
	  
  }
},
 
onStatusChange: function(status, chosenBefore) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    // enable cookies
  }
  if (type == 'opt-out' && !didConsent) {
    // disable cookies
	  	  
	// Google Analytics
	  
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-XXXXXXX-XX', 'auto');
  ga('send', 'pageview');
	  
	// End Google Analytics
	  
  }
},
 
onRevokeChoice: function() {
  var type = this.options.type;
  if (type == 'opt-in') {
    // disable cookies
  }
  if (type == 'opt-out') {
    // enable cookies
	  
	  
	  	  
	// Google Analytics
	  
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-XXXXXXX-XX', 'auto');
  ga('send', 'pageview');
	  
	// End Google Analytics
	  
  }
},	
})});
</script>

**Comment by niebau** [comment]
I think you have to dive deeper into the code. You are loading your analytics.js somethimes on the "disable cookies" code block, sometimes this block is blank.

Maybe my answer will clear things up a bit: https://github.com/insites/cookieconsent/issues/306#issuecomment-387114027

**Comment by FSCreatives** [comment]
Thanks niebau. I've taken a look at that comment before and it just confuses me even more.

**Comment by alexmorleyfinch** [comment]
You could try something like this:

```

function enableCookies() {
  // ENTER YOUR CODE TO ENABLE GOOGE ANALYTICS HERE
  // PLUS ANY OTHER SERVICES
    ga('create', 'UA-XXXXXXX-XX', 'auto');
    ga('send', 'pageview');
}

function disableCookies() {
  if(!document.__defineGetter__) {
    Object.defineProperty(document, 'cookie', {
        get: function(){return ''},
        set: function(){return true},
    });
  } else {
    document.__defineGetter__("cookie", function() { return '';} );
    document.__defineSetter__("cookie", function() {} );
  }
}

cookieconsent.initialise({
  
  // ... your options ...
  
  onInitialise: function (status) {
    var type = this.options.type;
    var didConsent = this.hasConsented();
    if (type == 'opt-in' && didConsent) {
      enableCookies()
    }
    if (type == 'opt-out' && !didConsent) {
      disableCookies()
    }
  },
   
  onStatusChange: function(status, chosenBefore) {
    var type = this.options.type;
    var didConsent = this.hasConsented();
    if (type == 'opt-in' && didConsent) {
      enableCookies()
    }
    if (type == 'opt-out' && !didConsent) {
      disableCookies()
    }
  },
   
  onRevokeChoice: function() {
    var type = this.options.type;
    if (type == 'opt-in') {
      disableCookies()
    }
    if (type == 'opt-out') {
      enableCookies()
    }
  },
});
```
