### ISSUE TITLE
popup behavior when refreshing page

### ISSUE THREAD

**Issue by Ruud68** [insites/cookieconsent#317]
Hi,
when I first visit the page (with opt-in banner, dismissOnScroll = 0, dismissOnTimeout=0, autoOpen=1, revokable=1):

- the banner displays correctly
- no cookieconsent_status is created

Then I reload the page (F5):

- the banner displays corretly
- the cookieconsent_status is set to value dismiss?

When reloading the page again (F5):

- the banner is hidden (only revoke button is showing)
- the cookieconsent_status is still set to dismiss

Problem is: I did not dismiss anything, nor did I press any button in the banner?

What I would expect is that the banner keeps showing until I actually click 'Got it!' or the 'Allow' button in the banner?

Or am I missing something here?

**Comment by InsanityMeetsHH** [comment]
dismissOnScroll = 0 and dismissOnTimeout=0 looks like you dismiss cookies instant. I guess you need higher values than 0 or set it to "false".

**Comment by alexmorleyfinch** [comment]
I think @InsanityMeetsHH is correct, if you set `dismissOnTimeout` to 0, it will actually dismiss the message immediately! It needs to be set to `false`
