### ISSUE TITLE
Hosted instead of CDN

### ISSUE THREAD

**Issue by mark-milton** [insites/cookieconsent#320]
How do I use Cookie Consent from my site instead of CDN?

Where to a put the files and what files do I need to change the url to? Currently it is using
//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js
//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css

**Comment by krvermeulen** [comment]
I have uploaded the JS and CSS to a seperate folder on my site called /cookieconsent. Then I changed the URL to //www.example.com/cookieconsent/cookieconsent.min.js and //www.example.com/cookieconsent/cookieconsent.min.css.

**Comment by Dolondro** [comment]
Krvermeulen is correct, you simply need to copy the files from `build` into any directory on your own server then link to them.
