### ISSUE TITLE
How to use OPT OUT with Google Tag Manager?

### ISSUE THREAD

**Issue by MyWiKy** [insites/cookieconsent#325]
Hi there,

I already created an Analytics Opt Out via the Google Tag Manager (following this [guidelines](url http://www.wrel.de/google-analytics-opt-out-google-tag-manager/) , using this code:

<script>var optOutLink = document.getElementById("ga-opt-out"); if(optOutLink) {    
optOutLink.onclick = function() {        
document.cookie = 'ga-opt-out=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';        
this.innerHTML = "Google Analytics opt-out successful";        
return false;    
}}
</script>

I use it on my data protection regulation with a deactivating link and it works fine: 
<a id="ga-opt-out" href="#">Google Analytics deactivating</a>

**But my question is: How to use GTM Opt out in cookie consent?**

I want to use it with the cookie consent opt out as well but I can't figure out how to do this. 'cause I don't understand JS/Jquery enough...

Any ideas would be much appreciated!

**Comment by fuerbringer** [comment]
The "standard" way of doing it like the following still holds up as far as I know:
```
// Set to the same value as the web property used on the site
var gaProperty = 'UA-XXXX-Y';

// Disable tracking if the opt-out cookie exists.
var disableStr = 'ga-disable-' + gaProperty;
if (document.cookie.indexOf(disableStr + '=true') > -1) {
  window[disableStr] = true;
}

// Opt-out function for onClick
function gaOptout() {
  document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
  window[disableStr] = true;
}
```

In your Privacy Policy you'd probably have the opt out link declared somewhere. A click on it would trigger `onClick="gaOptout()"`

**Comment by MyWiKy** [comment]
Hi there,

thanks for your answer. But unfortunately this is not my problem: I already have working link for deactivating In my data protection regulation/privat policy together with a opt out cookie-Script vis Google Tag Manger (see above).

What I need is a functional [Cookie Consent-Script](url https://cookieconsent.insites.com/demos/) for alerting users about the use of cookies on my website with an opt out option for deactivating Google Analytics. I want to use the Cookie consent insites theme 4 together with my  opt out cookie-Script vis Google Tag Manger (see above).
