### ISSUE TITLE
Method API to accept the banner?

### ISSUE THREAD

**Issue by parkerwebteam** [insites/cookieconsent#327]
Might be an feature request, but following recent GDPR rules, it'd be useful to have a method that accepts the banner that you can call elsewhere.

E.g: `cookieConsent.accept();`

This would be a useful feature, if it doesn't already exist - as you can tie this in with a Cookie Settings page.

**Comment by Dolondro** [comment]
This exists, the documentation and examples for it can be found [here](https://cookieconsent.insites.com/app/themes/insites-cookie-consent/examples/example-7-javascript-api.html)
