### ISSUE TITLE
Additional links in custom text.

### ISSUE THREAD

**Issue by davidnzfraser** [insites/cookieconsent#329]
Hope it's okay to ask this here. Really appreciate all the work here guys.

I couldn't find it being asked previous comments which surprised me so I'm probably just being a moron.

Instead of just having the learn more section. What is the best way to add links to the message? 
Such as "We use cookies <a href="link">(what is a cookie?)</a> to do this and that and this and that."

I'm not a js guy, can navigate through once pointed in the right direction.

Thanks again.

**Comment by AlexanderHofmeister** [comment]
You can simple add a <a href="...">linktext</a> to whatever you like.  I did it in the message label of the content. The customer wants an extra link to an other private policy

**Comment by alexmorleyfinch** [comment]
You need to change the configuration. The easiest way is to just modify the `messagelink` option inside `elements`. Check this out below:

```js
cookieconsent.initialise({
  // ... your options ...
  elements: {
    messagelink: '<p class="cc-message">My SPECIAL MESSAGE WITH <a href="#">SPECIAL</a><a href="#">LINKS</a></p>'
  }
})
```

😄
