### ISSUE TITLE
MaxMind GeoIP location service - is this actually free?

### ISSUE THREAD

**Issue by thenickdude** [insites/cookieconsent#331]
I don't understand the inclusion of MaxMind GeoIP in the list of location services that is attempted to be used automatically, isn't this API pay-only? [Their website says](https://dev.maxmind.com/geoip/geoip2/javascript/):

>All domains using the service must be registered. New users may purchase web service lookups and receive an account to register domains. Existing account holders are able to register domains directly.

**Comment by m-cameron** [comment]
@thenickdude You are right, it is pay web API.

We can consider IPInfoDB web service https://www.ipinfodb.com for free geolocation API

**Comment by FlorentMasson** [comment]
FYI IPInfoDB needs an API key and is rated limited to 2 queries/second with a free account

**Comment by Dolondro** [comment]
I'm unsure if this was always the case and this was originally just tested on localhost or whether they changed their T&C's at some point.

We'll remove MaxMind from the list of services in the next release.

With the benefit of hindsight we shouldn't have put the list of services to use as defaults inside the repository, instead giving people sample code to implement different services if they were willing to pay for it, but what is done is done in that regard.

The ideal solution from our point of view is that people either [self host](https://github.com/insites/cookieconsent/issues/401#issuecomment-405303307) their own solution or subscribe to one of the services
