### ISSUE TITLE
No callback when location enabled and detected country law does not require cookies

### ISSUE THREAD

**Issue by gondalez** [insites/cookieconsent#332]
First of all thanks for the handy library :)
However I have a bit of a question/bug around the location function.

# Steps to Repro
* set `location: true`
* handle `onIntialise` and `onStatusChange`
* load in country where there is no cookie law (e.g. Australia)
* popup does not show

# Expected
* `onInitialize` or `onStatusChange` called with `status` of `'allow'` so that I may configure my app to start emitting cookies for analytics, etc.

# Actual 
* no hooks are called

# Workaround
Looking at the [source](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L1456), I can handle the success callback on `initialise` myself as follows, but this ~seems a bit gross~ is undocumented and prone to breaking for future releases :)
```javascript
 window.addEventListener(
   "load",
   function() {
     window.cookieconsent.initialise(
       {
         location: true,
         onInitialise: function(status) { console.log('init'); console.log(arguments) },
         onStatusChange: function(status, chosenBefore) { console.log('change'); console.log(arguments) },
         onRevokeChoice: function() { console.log('revoke') },
         onPopupClose: function() { console.log('close'); console.log(arguments) },
       },
       function(result) { if (!result.options.enabled) console.log('No Cookie Law') }, 
       //                #^^^ the important bit
     )
   },
 );
```

I feel like I'm missing something simple. Am I? :)

**Comment by alexmorleyfinch** [comment]
There is now a new hook `onNoCookieLaw` that is called :)
