### ISSUE TITLE
Improve contrast ratio of button colours

### ISSUE THREAD

**Issue by smth** [insites/cookieconsent#334]
Some of the ratios, such as [this one](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=8EC760) are a bit low, we should probably be aiming for at least 3:1 here.

**Comment by Dolondro** [comment]
I'm all for WCAG compliance, but I've gone through all our examples and can't find anything that is using `#8EC760` nor can I find any colour palette options that have less than 3.25 contrast ratio.
