### ISSUE TITLE
Switch to maxmind for location 

### ISSUE THREAD

**Issue by attinderdhillon** [insites/cookieconsent#335]
How do I switch the default location service to maxmind or ipinfo ?
I can't figure the where to add the code. below is the code I am using, Regards

`
`
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#edeff5",
      "text": "#838391"
    },
    "button": {
      "background": "#4b81e8"
    }
  },
  "theme": "edgeless",
  "location": "true",
  "content": {
    "message": "We use cookies to ensure you get the best experience",
    "href": "https://url"
  }
})});
</script>
`
`

**Comment by InsanityMeetsHH** [comment]
Remove "location":"true" from your code and configure your own [location options](https://cookieconsent.insites.com/documentation/javascript-api/#location_options)

**Comment by davidsekar** [comment]
Move the service which you want to try first 

```
window.cookieconsent.initialise({
...
location:{
 services: [‘maxmind’, ‘freegeoip’, ‘ipinfo’]
}
....
}
```

**Comment by attinderdhillon** [comment]
Couldn't make it work. how do I append to this code --

`window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#edeff5",
      "text": "#838391"
    },
    "button": {
      "background": "#4b81e8"
    }
  },
  "theme": "edgeless",
  "location": "true",
  "content": {
    "message": "UNP use cookies to ensure you get the best experience",
    "href": "https://www.unp.me/privacy/"
  },
})});`
