### ISSUE TITLE
Opt-in enables cookies no mater what you click (Allow cookies or Got it!)

### ISSUE THREAD

**Issue by digibum** [insites/cookieconsent#339]
Using method: Ask users to opt into cookies (Advanced)
Info: You tell your users that you wish to use cookies, and give them one button to **enable cookies**, and another to **refuse them**

Issue: No matter witch button is clicked, this.hasConsented() is allways true.
In opt-in mode, dissmis button should not resolve to consent!

Is this a bug or what?

**Comment by digibum** [comment]
Closed by accident...

**Comment by zbacsi** [comment]
I have a quick fix! Check status=='allow' instead of didConsent.

Old code:
```javascript
if (type == 'opt-in' && didConsent) {
```
Fix:
```javascript
if (type == 'opt-in' && status=='allow') {
```

**Comment by alexmorleyfinch** [comment]
This should be fixed in the latest release
