### ISSUE TITLE
two links needed - how do I add a 2nd hyperlink?

### ISSUE THREAD

**Issue by GretchPlayer** [insites/cookieconsent#341]
Really great plugin, but I need 2 links / hyperlinks in the popup.
1) linking to a "read more..."
2) linking to "Read our Privacy Policy".

It would be easy if I could add "<a href="example.com">link</a>"   to the comment text, but it give an error.  Does anyone know why, or have a solution?
Thanks.

**Comment by GretchPlayer** [comment]
I see that GitHub has converted my textual <a link - to an 'a link'  - I should have thought of that.
What I try to say was that it would be good to be able to add an <a link  
such as \ ....a href="www.example.com" ....  (typed this time without the <>'s)

**Comment by InsanityMeetsHH** [comment]
Use elements > [messagelink](https://cookieconsent.insites.com/documentation/javascript-api/#custom_options) to solve the task. ([example](https://github.com/InsanityMeetsHH/gulp-templating/blob/master/src/js/module/cookieconsent.js))

**Comment by GretchPlayer** [comment]
Thanks @InsanityMeetsHH  I think? I understand it.  i.e   in messagelink I can add additional a links (which I couldn't in message). so  your line:
```
messagelink: '<div class="col-12 col-sm-6 col-lg-8 pb-3 pb-sm-0"><span id="cookieconsent:desc" class="cc-message">{{message}} ' 
                    + '<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_blank">{{link}}</a></span></div>'
```
I added at the end of the 2nd line (purely as a demo/test) to :
```
messagelink: '<div class="col-12 col-sm-6 col-lg-8 pb-3 pb-sm-0"><span id="cookieconsent:desc" class="cc-message">{{message}} ' 
                    + '<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_blank">{{link}}</a>  <a href="example.com">HERES A NEW LINK</a>  </span></div>'
```
And it works !!   I can now get a 2nd link ;-)
Now I need to understand the bootstrap column formatting  (col-12 col-sm-6 col-lg-8 pb-3 pb-sm-0).
I've read https://getbootstrap.com/docs/3.3/css/ but I cant see "pb-3".  Am I looking in the right place??
Thanks v much for your help.

**Comment by InsanityMeetsHH** [comment]
These are Bootstrap 4 classes.

**Comment by GretchPlayer** [comment]
I've found that 'pb' is about spacing, but still having problems understanding the column spacing.
col-12 col-sm-6 col-lg-8
and later in the code:
col-12 col-sm-6 col-lg-4
@InsanityMeetsHH's version doesnt give the formating on wide devices that I want.
i.e. messagelink on the left and compliant button on the right.
Can someone help me with understanding what the format should be - thanks

**Comment by GretchPlayer** [comment]
If there are 12 virtual columns I thought spacing should always total 12 (for each size device)
Have I misunderstood, or  if "col-lg-8" is declared, is the  "col-lg-4" assumed?
ref: https://getbootstrap.com/docs/3.3/examples/grid/
