### ISSUE TITLE
Disabling cookies doesn't work

### ISSUE THREAD

**Issue by klhkm** [insites/cookieconsent#342]
The dismiss button seems to trigger the cookies as well as the accept button despite following this method: https://cookieconsent.insites.com/documentation/disabling-cookies/

**Comment by DanMan** [comment]
Same here. It seems that `hasConsented()` always returns `true`, because it only checks, if a cookie has been set, not what it's value is:

https://github.com/insites/cookieconsent/blob/7a493e8996faa691f47c777225ec66095fdd14d6/src/cookieconsent.js#L559

**Comment by klhkm** [comment]
@DanMan I've read a few threads now saying there's an error in the code which is causing this. Thinking those of us with the Friday deadline probably need to find another solution for GDPR compliancy?

**Comment by DanMan** [comment]
@klhkm It looks like this PR: https://github.com/insites/cookieconsent/pull/284 solves the problem. I'm about to test it now.

**Comment by klhkm** [comment]
@DanMan Thanks for this - have you then hosted the .js locally rather than using the cloudflare version from Insites?

**Comment by DanMan** [comment]
@klhkm Yes, I host the file locally anyway.

**Comment by klhkm** [comment]
@DanMan Makes sense - I'll do the same! Please let me know how testing went! :)

**Comment by klhkm** [comment]
@DanMan Testing for me doesn't seem to have resolved the issue - seems to stop the banner from showing.

**Comment by klhkm** [comment]
@DanMan Ignore my previous comment - these changes seem to have fixed the issue!
