### ISSUE TITLE
Anchoring to a div

### ISSUE THREAD

**Issue by neelam88** [insites/cookieconsent#346]
Adding a hash (#) to the learn more link is creating funny results...

The link changes from: **https://www.xxxxx.com/xxx/xxxx/xxxx/privacy-policy#cookies** to: **https://www.xxxxx.com/xxx/xxxx/xxxx/privacy-policy/#cookies** when clicked.

A "**/**" is added between privacy-policy and the "**#**"

Is it not possible to anchor to a div?

**Comment by InsanityMeetsHH** [comment]
Your div should look like this
````html
<div id="cookies"></div>
````
The plugin doesn't adds slashes but your server or application could (e.g. .htaccess).

**Comment by alexmorleyfinch** [comment]
@InsanityMeetsHH is right, the tool doesn't rewrite urls at any point. It should also be noted that trailing slashes generally don't affect the url so you should be okay.
