### ISSUE TITLE
Only display banner to visitors in the EU

### ISSUE THREAD

**Issue by wolfbeast** [insites/cookieconsent#35]
The vast majority of my site's visitors are not from the EU, but are apparently still presented with the consent popup. This should not happen because it doesn't apply to them, and they really don't agree with having this completely N/A consent requirement thrown in their face.

**Comment by jtlocsei** [comment]
I agree, this would be a great feature. It was part of v1 wasn't it? Why the removal of the feature?

**Comment by adisos** [comment]
At that moment it initiates automatically. But I have JS code which checks user country code and shows this popup. I have to change source code to accomplish this. It would be better if we can control initiating.

**Comment by gvdm** [comment]
Of all the implementations I've surveyed I like cookieconsent from silktide best (and GPL) but having the warning restricted to EU visitors is the main feature that I've been told has to be part of my implementation of cookie consent. @adisos would you mind sharing how you managed to implement this? Is there any chance of this making it into master?

**Comment by adisos** [comment]
@gvdm 

I used third party service to fetch user's country code and check if it belongs to EU or not.

**Comment by SteveMcArthur** [comment]
As a bit of an aside. If you run your website through cloudflare (https://www.cloudflare.com/) it is supposed to add the country code to the request object. However, I've never been able to get this to work. Other than that, its a matter of making a request to a third party service that looks up the country based on the IP address and then deciding whether to show cookie consent or not.

**Comment by bshilpaa** [comment]
Hi,
The geomaxmind database allows you to easily find the country code of the visitor. Have the countrycodes of all EU countries in an array , match this to the maxmind geo lookup for countrycode. if it matches, call the javscript function to display the cookie notice.
I used <script src="//js.maxmind.com/js/apis/geoip2/v2.1/geoip2.js" type="text/javascript"></script>

**Comment by oliveremberton** [comment]
We had this feature in Cookie Consent v1, but it requires you connect a 3rd party API to our tool to work. It's because location lookup costs money and we already serve billions of page requests every month, we couldn't do this for free.

You can take a look at how this works in Cookie Consent 1 here: http://sitebeam.net/cookieconsent-v1/documentation/hide-from-visitors-outside-the-eu/

**Comment by wolfbeast** [comment]
So what's wrong with having a static geoip lookup file hosted by yourself, and using a CDN like CloudFlare to serve it? Seriously, presenting this pop-up to non-EU visitors is a no-go area.

**Comment by wolfbeast** [comment]
In fact, you could use CloudFlare to do the GeoIP for you, and draw on that.

**Comment by oliveremberton** [comment]
We'll need to investigate, but I'll re-open for consideration - thanks.

**Comment by ArwedSchmidt** [comment]
+1

**Comment by SteveMcArthur** [comment]
I suppose it might be possible to set up a website through CloudFlare that did only one thing and that is serve up the user GeoIP or country code....mm thinking...

**Comment by CanRau** [comment]
I'm coding a module for [Processwire](https://github.com/ryancramerdesign/ProcessWire/) which will include CookieConsent into the site.
Is the Cloudflare hosted version of cookie consent already taking care of the location? Or would the whole site need be hosted on cloudflare, or do I have to handle this myself?

**Comment by scienced** [comment]
I made a working wrapper using Geoplugin: http://www.geoplugin.com/webservices/extras#eu_cookie_law

`<script src="http://www.geoplugin.net/extras/cookielaw.js" type="text/javascript"></script><script type="text/javascript"> window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":null,"theme":"light-bottom"};</script><script type="text/javascript">if ( geop1ugin_cookieConsent () ) { jQuery.getScript("//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js", function(){});} </script>`

**Comment by themichael123** [comment]
@scienced This is gold. Thanks.

**Comment by alexmorleyfinch** [comment]
This feature is now contained within CookieConsent V3, although it is disabled by default (because people are expected to configure their own location services, or use free ones)

It becomes as simple as:

```
cookieconsent.initialise({
  // ... popup options ...
  location: true
});
```

This means that we attempt to get the country code from the list of location services first. If we get the country code successfully, then the original popup options are slightly modified to conform to the laws of that country. If we couldn't get the country code, the options remain as they are, and the popup is shown without any country specific options.

E.G. if that country states that popups cannot be automatically clicked, then that rule is followed.

Custom services can be injected through the options too. See http://cookieconsent.insites.com/documentation/location-services-cookie-law/

**Comment by csteh** [comment]
Hello everyone. Hope is the place where it's allowed to ask help?  
I use this code. 

> <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
> <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
> <script>
> window.addEventListener("load", function(){
> window.cookieconsent.initialise({
>   "palette": {
>     "popup": {
>       "background": "#F28C12",
>       "text": "#ffffff"
>     },
>     "button": {
>       "background": "#27ae60"
>     }
>   },
>   "position": "bottom-right",
>   "type": "opt-in",
>   "content": {
>     "message": "Loi sur les cookies de l'UE.\nNotre site Web utilise des cookies pour vous assurer d'avoir la meilleure expérience sur notre site.",
>     "dismiss": "Refuser les cookies",
>     "allow": "Accepter",
>     "deny": "Refuser",
>     "link": "En savoir plus",
>     "href": "https://www.xxxx.com/cookie-policy.html"
>   }
> })});
> </script>

 
from cookieconsent.insites.com to dispay cookie consent in my website, it work fine!

My issue, what is the code I sould add to this to display cookieconsent banner only if my website opened in EU??

Thank you in adance

**Comment by Vlad-UA** [comment]
> I made a working wrapper using Geoplugin: http://www.geoplugin.com/webservices/extras#eu_cookie_law

Unfortunately geoplugin.com work with http only.
My be somebody know service with https?

**Comment by doktorrr** [comment]
I'm only interested in sample code because of Adsense terms. Is there someone with sample code for this purpose?

**Comment by davidh-nuts** [comment]
So can we get the `location` flag onto the documentation. Asking for a friend.

**Comment by derpyherp** [comment]
I can get the visitor's country code from Cloudlfare via $_SERVER["HTTP_CF_IPCOUNTRY"]; header. Where do I plug this into Insites' javascript code?
