### ISSUE TITLE
Revoke consent at a later date

### ISSUE THREAD

**Issue by klhkm** [insites/cookieconsent#351]
Is there an option to add a link somewhere on the site (i.e. privacy policy or website footer) that will clear/revoke cookie consent? Has anyone implemented anything like this?

**EDIT: To be clear, I mean after consent has been given on the cookies banner originally and specifically to cover the GDPR requirement to allow users to revoke consent AFTER they've given consent if they want to.**

**Comment by maddovr** [comment]
How to do that? for example my website only has third party cookies to deal with(analytics and Disqus). How do I do what you said @philnelson?

**Comment by klhkm** [comment]
@philnelson That's the process I've followed for my cookie consent banner however it does not allow the user to revoke consent at a later date because the banner disappears after consent is given.

**Comment by niko5** [comment]
here's an example of how to do it this is implemented in google tag manager

**Comment by klhkm** [comment]
@maddovr It will depend on how the cookies are initialised on your site. Google Analytics can be done by placing the GA tracking code underneath //enable cookies in this part of the documentation - https://cookieconsent.insites.com/documentation/disabling-cookies/

Disqus could mean you can't initialise Disqus until consent has been given, in which case you may have to customise the Disqus script or use something like JS .innerHTML to include it once consent is given.

This post is not related to what you're asking but instead revoking consent at a later date if you had already consented, it could be worth checking the other issues as many people have asked what you're asking.
