### ISSUE TITLE
onInitialise only triggered when user has consented?

### ISSUE THREAD

**Issue by iwasherefirst2** [insites/cookieconsent#352]
Hi this is my code:

 ```
 window.addEventListener("load", function(){
  window.cookieconsent.initialise({
    "palette": {
      "popup": {
        "background": "#eaf7f7",
        "text": "#5c7291"
      },
      "button": {
        "background": "#56cbdb",
        "text": "#ffffff"
      }
    },
    "type": "opt-out",  ,
  onInitialise: function (status) {
    alert('hi guys');  
  }
});
}
```

When I load the page, no alart is prompted. If I decline, then there is also never an alert propted. Only if I click on "Got it" onInitialise will trigger from then on. 

If this is intended, then I think oen should change the example on the docs at https://cookieconsent.insites.com/documentation/disabling-cookies/

Because

```
onInitialise: function (status) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    // enable cookies
  }
  if (type == 'opt-out' && !didConsent) {
    // disable cookies
  }
},
```

makes no sense, since the function is only executed if  `didConsent` is true..

**Comment by fitzel** [comment]
jup, doesnt make sense, onInitialise should be called regardless of the status.

**Comment by iwasherefirst2** [comment]
@fitzel thanks for the honor! I actually figured out that I don't need `onInitialise` for opt-out. I think in your case if someone clicks on "revoke" and "got it", his tracking info will still be disabled. That the code how I am using it:
```

  window.addEventListener("load", function(){
  window.cookieconsent.initialise({  
     "palette": {
    "popup": {
      "background": "#000"
    },
    "button": {
      "background": "#f1d600"
    }
  },
  onStatusChange: function(status, chosenBefore) {   
    if (!this.hasConsented()) {
      gaOptout()
    }
  },
  onRevokeChoice: function() {
      gaRevoke()
  }
})

  var gaProperty = 'UV-XXXXXXXXXXXXXXXx-XX';
  var disableStr = 'ga-disable-' + gaProperty;

  if (document.cookie.indexOf(disableStr + '=true') > -1) {
      window[disableStr] = true;
  }

  function gaRevoke(){
    document.cookie = disableStr + '=; expires=Thu, 01 Jan 1970 00:00:01 GMT;';
  }

  function gaOptout() {
      document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
      window[disableStr] = true;
  }

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  //alert(window[disableStr]);
  ga('create', gaProperty, 'auto');
  ga('set', 'anonymizeIp', true);
  ga('send', 'pageview');

});
```

**Comment by Dolondro** [comment]
onInitialise is only called if you're loading the page and you've already accepted/denied cookies. This is being discussed in #389

**Comment by iwasherefirst2** [comment]
@Dolondro sorry but thats not correct. onInitialise is only called if you're loading the page and you've already **accepted** the cookie. If you denie it, onInitialise won't work, thats why its so strange that you use **didConsent** in the example at the docs. Thats why I think one should reopen this issue.

**Comment by Dolondro** [comment]
I've just double checked this and confirmed that onInitialise *is* called regardless of whether the user accepted/declined cookies.

You can test this by using this code:
```html
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<html><body></body></html>
<script>
    window.addEventListener("load", function(){
        window.cookieconsent.initialise({
            type: 'opt-in',
            onInitialise: function (status) {
                console.log("OnInitialise", this.hasConsented());
            },
        });
    });
</script>
```

Clicking Deny, then refreshing the page will log to the console "OnInitialise false"

**Comment by TheMangoTrain** [comment]
Dolondro:

Incorrect, onInitialise only runs when some kind of consent has been made (Dismiss or Agree). Both ways leave a cookie with a flag so the preference is remembered. That is why after you refresh the page, you're seeing your console.log line.
