### ISSUE TITLE
Layout "edgeless" and position "floating right" causes display error on IE 11

### ISSUE THREAD

**Issue by nelgmo** [insites/cookieconsent#353]
![image](https://user-images.githubusercontent.com/795917/40484408-caffd588-5f5b-11e8-89ed-e7aaf34f0f13.png)

**Comment by shaunopp** [comment]
Experiencing this issue as well. Thought it was due to the fact that I was using a large amount of copy but it looks like a bug.

**Comment by Dolondro** [comment]
Closing as duplicate of #326
