### ISSUE TITLE
how to invoke open() method?

### ISSUE THREAD

**Issue by imezei** [insites/cookieconsent#354]
how to open popup?
my code:
```js
var instance = new cookieconsent.Popup();
instance.initialise({
    "position": "bottom-right",
    "theme": "classic",
    "type": "opt-out",
    "content": {
        "message": "...",
        "dismiss": "...",
        "deny": "...",
        "link": "...",
        "href": "..."
    },
    revokable:true,
    onInitialise: function(status) {
        if(!instance.hasConsented()) {
            instance.open(); // this does not work!!!
        }
    },
    onStatusChange: function(status) {
        if(!this.hasConsented()) {
            window.location.href = 'https://cookiesandyou.com/';
        }
    }
});
```

**Comment by davidsekar** [comment]
Check this example where the popup object is made available **after the plugin is initialized**. .

https://github.com/insites/cookieconsent/blob/master/examples/example-7-javascript-api.html#L87

You can set a flag in the initialize method and then use the flag to either open the popup as follows

```
var instance = new cookieconsent.Popup();
var hasConsented = false;
var popup;
instance.initialise({
"position": "bottom-right",
"theme": "classic",
"type": "opt-out",
"content": {
"message": "...",
"dismiss": "...",
"deny": "...",
"link": "...",
"href": "..."
},
revokable:true,
onInitialise: function(status) {
var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
hasConsented  = true;
  }
},
onStatusChange: function(status) {
var didConsent = this.hasConsented();
if(type == 'opt-in' && !didConsent) {
window.location.href = 'https://cookiesandyou.com/';
}
}
},
function(p){
popup=p;
popup.open();
}
);
```

**Comment by imezei** [comment]
thanks!
but, it just doesn't work. or i don't get it.
this is what i want to do: 
i want opt-out type, and when someone click deny button that 'https://cookiesandyou.com/' link opens. that works fine. but when you go back from that link to the original site i want to popup opens again. 
can you please help me.
thanks.

**Comment by imezei** [comment]
this is my current code:
window.addEventListener("load", function(){
		window.cookieconsent.initialise({
			"palette": {
				"popup": {
					"background": "#3399ff"
				},
				"button": {
					"background": "#fff",
					"text": "#3399ff"
				}
			},
			"position": "bottom-right",
			"theme": "classic",
			"type": "opt-out",
			"content": {
				"message": "Obavještavamo Vas kako ova stranica koristi kolačiće (cookies) u svrhu funkcionalnosti naše web stranice, kvalitetnijeg postavljanja našeg sustava i bolje prezentacije.",
				"dismiss": "Da, pristajem",
				"deny": "Ne pristajem",
				"link": "Više o kolačićima",
				"href": "https://www.centar-za-poduzetnistvo.hr/cookies"
			},
			onStatusChange: function(status) {
				if(!this.hasConsented()) {
					window.location.href = 'https://cookiesandyou.com/';
				}
			},
		})
	});

**Comment by Dolondro** [comment]
CookieConsent remembers that they declined cookies, so doesn't show the popup again.

It's not particularly nice but you can get around this by immediately clearing the status as part of your code:
```js
window.addEventListener("load", function(){
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": "#3399ff"
                },
                "button": {
                    "background": "#fff",
                    "text": "#3399ff"
                }
            },
            "position": "bottom-right",
            "theme": "classic",
            "type": "opt-out",
            "content": {
                "message": "Obavještavamo Vas kako ova stranica koristi kolačiće (cookies) u svrhu funkcionalnosti naše web stranice, kvalitetnijeg postavljanja našeg sustava i bolje prezentacije.",
                "dismiss": "Da, pristajem",
                "deny": "Ne pristajem",
                "link": "Više o kolačićima",
                "href": "https://www.centar-za-poduzetnistvo.hr/cookies"
            },

            onStatusChange: function(status) {
                if(!this.hasConsented()) {
                    this.clearStatus();
                    window.location.href = 'https://cookiesandyou.com/';
                }
            },
        })
    });
```
