### ISSUE TITLE
Can't change cookie name

### ISSUE THREAD

**Issue by amooreTO** [insites/cookieconsent#355]
I am trying to change the cookie name to something else like this:

```
window.cookieconsent.initialise({
        cookie.domain : '.foo.com',
        cookie.name: 'cookieconsent_status_v2',
        palette:{
            popup: {background: "#000"},
            button: {background: "#f1d600"},
        },            
        content:{          
            message: "My Message",                
            href: "/privacy-policy"
        },
    });
```

I am getting the following error "Uncaught SyntaxError: Unexpected token ." at cookie.name

Is there a different way to do this?

**Comment by rubyji** [comment]
Thank you for posting this, I was making the same syntax mistake and this helped me figure it out.
