### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by thany** [insites/cookieconsent#359]
I just clicked the demos link ([and got here](https://cookieconsent.insites.com/demos/)) and all I'm seeing is a totally unstyled html document that's not showing any form of cookie consent.

See:
![capture](https://user-images.githubusercontent.com/152227/40540011-e2ebe0c2-6016-11e8-9bee-9028da788f17.PNG)

That's Firefox 61 on Windows 10.

**Comment by krvermeulen** [comment]
Cookie Consent is recognized (and therefore possibly blocked) by Ghostery. Try disabling Ghostery and/or Adblock.
