### ISSUE TITLE
open link in _self and not _blank

### ISSUE THREAD

**Issue by ZweisteinT** [insites/cookieconsent#365]
i saw several duscussions but no answers….

can i set the "more Information" link to _self instead of _blank?

one of the most crucial functionalities… Maybe also add it to documentation.

**Comment by nick0** [comment]
I would also like to know how to do this - opening the Learn More links in a new window makes no sense when the privacy / cookie policy is on the same website.

Thanks for a great script.

**Comment by thexmanxyz** [comment]
@nick0 @ZweisteinT You have to change under `elements:` the `messagelink:` or `link`. But be aware of the `layouts:` and the default `layout:`.

for more information see the code: [Layouts](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L255), Llayout](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L266), [Elements](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L222) see also Issue were I had a similiar issue https://github.com/insites/cookieconsent/issues/228

**Comment by nick0** [comment]
Thanks for your help @thexmanxyz. 

I am working in EvolutionCMS which uses the curly {{brackets}} for repeatable items called chunks as an inbuilt default feature. So when I use the following cookieconsent code which also has curly brackets, nothing appears where the text and link should be because the CMS is looking for those chunks.
```
		"layouts": {
			"basic": "{{messagelink}}{{compliance}}",
			"basic-close": "{{messagelink}}{{compliance}}{{close}}",
			"basic-header": "{{header}}{{message}}{{link}}{{compliance}}"
		},
		"elements": {
			"messagelink": "<span id="cookieconsent:desc" class="cc-message">{{message}} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_self">{{link}}</a></span>",
			"link": "<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_self">{{link}}</a>"
		}
```
Is there an alternative to the curly brackets with cookieconsent? eg can you easily change the regex?

If not I will just not show the learn more link.

Thanks again for your help.

**Comment by thexmanxyz** [comment]
@nick0 np, I have no experience with EvolutionCMS a good place to ask for a workaround would be at their communication channels. What locations are parsed for the `{{}}` I guess only the HTML files. So a quick work around would be putting JS with curly bracelets in a file and not directly within HTML so it won't get recognized by EvolutionCMS. IDK if this works but typically only dom output is filtered.

**Comment by nick0** [comment]
Thanks @thexmanxyz. Good call, I have asked if there is a way for EvolutionCMS to ignore treating the cookieconsent items in curly brackets as chunks. Waiting to hear if there is an escape method.
Correct - they are treated as html (I think) and putting the cookieconsent code into an external file will definitely work - I just wanted to give the site owner easier access to change the message. But that is probably less important than opening the privacy policy in the same window. Many thanks,

**Comment by thexmanxyz** [comment]
@nick0 You should be able to work around with a combination of external / internal js.

**Comment by nick0** [comment]
Thanks @thexmanxyz. 

I heard re escaping the curly brackets in EvolutionCMS - it should work like so \{\{ and \}\} - apparently this should work, though it just shows a blank white box when I include the layouts and elements parts - does the code included for layouts and elements look right to you and do you think it should still work with the escaping?

```
<script>
window.addEventListener("load", function(){
	window.cookieconsent.initialise({
		"content": {
			"message": "This website uses cookies to ensure you get the best experience on our website.",
			"dismiss": "Got it!",
			"link": "Learn more",
			"href": "/privacy-policy/"
		},
		"layouts": {
			"basic": "\{\{messagelink\}\}\{\{compliance\}\}",
			"basic-close": "\{\{messagelink\}\}\{\{compliance\}\}\{\{close\}\}",
			"basic-header": "\{\{header\}\}\{\{message\}\}\{\{link\}\}\{\{compliance\}\}"
		},
		"elements": {
			"messagelink": "<span id="cookieconsent:desc" class="cc-message">\{\{message\}\} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="\{\{href\}\}" target="_self">\{\{link\}\}</a></span>",
			"link": "<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="\{\{href\}\}" target="_self">\{\{link\}\}</a>"
		}
	})
});
</script>
```

Thanks for your help.

**Comment by thexmanxyz** [comment]
@nick0 If this is the correct escaping method it should work. Check how the curly braces are rendered to the DOM. If the escape operator (backslashes) are still there it's probably the wrong escaping method. Also check for JS errors in your developer tools.

**Comment by thexmanxyz** [comment]
If you don't get the escaping right rework your Javascript. Put all curly braces to your external script wrap the cookie consent js code in a javascript class and parameterize it via interntal js.

Internal:
```
var myCC = new MyCookieConsent(parameters,...);
  myCC.init(parameters,...);
```
External:
function MyCookieConsent(paramters,...){
   ...set variables
  init: function(parameters,...){
  //func used within the load() event
  };
}

That's just a basic pseudo code. But that would allow parameterization and fixes your escaping issue.

**Comment by proshot2017** [comment]
@thexmanxyz When you solved the problem, please provide here for all non coding experts the complete working code. (not the evolution CMS solution!) This issue is asked by many people, so please ... the simple copy&paste way. We'll appreciate it. Thanks again

**Comment by thexmanxyz** [comment]
@proshot2017 I can't provide a copy&paste full working solution because it depends on your favor how to design the banner. Read through this thread and the attached links. Everything already explained. @nick0 Asked for a Evolution CMS solution, you don't have to bother about that part.

**Comment by thexmanxyz** [comment]
@proshot2017 Take especially a look at https://github.com/insites/cookieconsent/issues/169

**Comment by proshot2017** [comment]
@thexmanxyz The design is not the problem. I am able to change this accordingly. I tried to make it - believe me. Thanks in advance

**Comment by proshot2017** [comment]
@thexmanxyz Ok thanks - here we are ...

          <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css">
          <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
```<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
  "popup": {
      "background": "rgb(155, 0, 0)",
      "text": "#ffffff"
    },
   "button": {
   "background": "rgba(255, 255, 255, 0.3)"
    }
  },
 "position": "top",
  "static": true,
  "content": {
    "message": "Durch die weitere Nutzung der Webseite stimmen Sie der Verwendung von Cookies zu. ",
    "dismiss": "Verstanden",
    "link": "Zur Datenschutzerklärung",
    "href": "impressum.html",
  },
  
})});
</script>

**Comment by thexmanxyz** [comment]
@proshot2017 So yeah and what's now the actual problem. There is nothing set concerning layout or message.

**Comment by proshot2017** [comment]
@thexmanxyz ?? the problem is the _target_self_ thing. The thread opener @ZweisteinT  asked for. And again - I can't set the messagelink thing by myself, sorry.

**Comment by thexmanxyz** [comment]
@proshot2017 ok...
```

elements: {
   messagelink: '<span id="cookieconsent:desc" class="cc-message">{{message}} <a aria-label="learn more about cookies" role=button tabindex="0" class="cc-link" href="{{href}}" rel="noopener noreferrer nofollow" target="_blank">{{link}}</a></span>',
}
```

```
  },
  //here i go
})});
```

Don't forget to change your target.

**Comment by proshot2017** [comment]
@thexmanxyz Thanks again for your kind help, it works like a charm!

**Comment by nick0** [comment]
Thanks for your 2 posts @thexmanxyz, I got sidetracked by other design elements of the project, will tackle early next week and confirm back. Thanks again and have a great weekend.

**Comment by nick0** [comment]
Just sending you an email. Thanks.

**Comment by nick0** [comment]
Thanks for your help @thexmanxyz.

The brackets looked correctly escaped in the front end html so EvolutionCMS was correctly escaping.

I found a javascript error in Chrome using developer. It was throwing an “Uncaught SyntaxError: Unexpected identifier” for my cookie consent code – specifically relating to elements.

I narrowed it down to “” within the “” call.

So I changed…
```
                        "elements": {
                                    "messagelink": "<span id="cookieconsent:desc" class="cc-message">/{/{message/}/} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="/{/{href/}/}" target="_self">/{/{link/}/}</a></span>",
                                    "link": "<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="/{/{href/}/}" target="_self">/{/{link/}/}</a>"
                        }
```

to… 
```
                        "elements": {
                                    'messagelink': '<span id="cookieconsent:desc" class="cc-message">\{\{message\}\} <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="\{\{href\}\}" target="_self">\{\{link\}\}</a></span>',
                                    'link': '<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="\{\{href\}\}" target="_self">\{\{link\}\}</a>'
                        }
```

And now it works a treat within the CMS and also plain html draft pages - and it opens in the same window. You beauty

Thanks again.

**Comment by thexmanxyz** [comment]
@nick0 np, glad that it now works. didn't notice the unescaped doublequotes but yeah that's a syntax issue ;)

**Comment by jodumont** [comment]
I simple way to do it is to load the cookieconsent.js locally
then change line [225](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L225) and [229](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L229) to make them point to your url such as :

`link: '<a aria-label="learn more about cookies" role=button tabindex="0" class="cc-link" href="https://mydomain.tld/cookie.html" target="_self">Cookie and Me</a>',`

**Comment by thexmanxyz** [comment]
@jodumont directly modifying an library file, especially since we already have an option, is not the way to go. No one should do that in that case.

**Comment by jodumont** [comment]
Sorry to prolong this issue, but I'm eager to learn
@thexmanxyz Where is **the tools** ?

**Comment by thexmanxyz** [comment]
@jodumont We have the toolset which doesn't makes it necessary to modify the original file (`.initilaise()`).
You should not modify any lib files as long as you maintain changes, otherwise I wouldn't recommend this anyone else.

The "tools" (what was not the best word) are listed above and show how you pass code to Cookie Consent without modifying core files.

**Comment by OLEXNY** [comment]
Open in _self instead of _blank. Following the suggestions above, I am still having troubles to get this to work... For some reason the "Learn more" link doesn't open _self but in a new tab. Could someone please review the code below in order to make this work?

```
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#ebebeb",
      "text": "#404040"
    },
    "button": {
      "background": "#ff0099",
      "text": "#ffffff"
    }
  },
  
  "elements": { 
  "link": '<a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{href}}" target="_self">{{link}}</a>',
},
  "content": {
    "href": "https://www. example.com/learnmore" 
  }
  
})});
</script>
```

**Comment by thexmanxyz** [comment]
@OLEXNY here is no review place, read the thread it already got handled multiple times, you didn't do like discussed and you didn't read the whole discussion, do that now

**Comment by OLEXNY** [comment]
Yeah... let's review syntax issues then... Thanks....

**Comment by thexmanxyz** [comment]
@OLEXNY you have no syntax issue otherwise the Cookie Consent wouldn't work at all

**Comment by thexmanxyz** [comment]
@OLEXNY but one last time check the `messagelink` parameter

**Comment by OLEXNY** [comment]
Yes, I did and it works now. Problem I had that I copied the code piece with   `"messagelink"` instead of `'messagelink'`.

**Comment by thexmanxyz** [comment]
@OLEXNY glad that it works

**Comment by Dolondro** [comment]
There is now a `["content"]["target"]` configuration option in 3.1.0

**Comment by nick0** [comment]
Thanks so much! 

That's a lot easier - no layout / element hacks required.

For anyone needing an example...
`````
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
	window.cookieconsent.initialise({
		"content": {
			"href": "/privacy-policy/",
			"target": '_self'
		}
	})
});
</script>
`````

Thanks again.
