### ISSUE TITLE
How do I force the page to reload after click?

### ISSUE THREAD

**Issue by frieauffcom** [insites/cookieconsent#366]
Maybe a dummy question, I am a total JS newbie.
I would like to force the browser to reload the page after the user clicks one of the buttons (either one, but esp. the allow button would be important).
How can I do that?

**Comment by eleumas** [comment]
follow

**Comment by InsanityMeetsHH** [comment]
[My solution](https://github.com/InsanityMeetsHH/gulp-templating/blob/master/src/js/module/cookieconsent.js#L59)

**Comment by Tralapo** [comment]
Add something like location.reload() in the part that gets executed after cookies are enabled (my script is opt-in and only does something on a status change)

`<script>
     window.addEventListener("load", function(){
     window.cookieconsent.initialise({
		"palette": {
			"popup": {
			"background": "#252e39"
			},
			"button": {
			"background": "#14a7d0"
			}
		},
		"position": "bottom-left",
		"type": "opt-in",
		"content": {
			"message": "Cookies:",
			"dismiss": "No",
			"allow": "Yes",
			"link": "link"
		},
	onStatusChange: function(status, chosenBefore) {
		var type = this.options.type;
		var didConsent = this.hasConsented();
			if (type == 'opt-in' && didConsent) {
				// enable cookies
				location.reload(); 
			}
	},
})});
</script>`
