### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by bigfraggle** [insites/cookieconsent#374]
After adding the code the console shows an error message:

> Uncaught TypeError: Cannot read property 'className' of undefined at Object.removeClass (cookieconsent.min.js:1) at n.o (cookieconsent.min.js:1) at temp (global.js:24)

Any ideas?

**Comment by Dolondro** [comment]
It looks like an element is being passed to removeClass that doesn't exist. However, without a test case it isn't something we can help with further.
