### ISSUE TITLE
Working in reverse

### ISSUE THREAD

**Issue by whoknowsit** [insites/cookieconsent#376]
My coding knowledge is zero and I've been trying to get various GDPR cookie systems/plugins/codes to work and I can't get them working. This one is the closest I've gotten to getting one to work but somehow I've got it working in reverse and can't get it working as I think it should based on how I'm interpreting the documentation - so I'm presuming I'm reading things wrong.

I have chosen "Let users opt out of cookies" and the default text that is generated using the cookieconsent wizard at https://cookieconsent.insites.com/download/ has "Got it!" for Dismiss and has "Decline" for Deny. 

The code I have implemented on my website is below and I am finding that when I click on the "Decline" button then the Google Analytics cookies actually show up. Isn't this working the wrong way around?

I can't figure out what change I need to make to set it up so that when the user clicks "Got it!" that the cookies show up and if they click "Decline" that they don't.

Any help on this is really really appreciated.

EDIT: For some reason my brain is starting to possibly make sense of this. Am I right in saying that by choosing the "Let users opt out of cookies" that the "Decline" button is in essence saying "I decline to be opted out of cookies, and so I am actually opting in to cookies"?

EDIT2: I changed the code to an "opt-in" and added the callback hook placing the analytics code under the 'opt-in' part this time. Now it doesn't matter which button I click on (Allow / Decline), they both allow the cookies. Before clicking any button no cookies are shown so they are initially blocked but both buttons allow them to show up.

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
    window.addEventListener("load", function(){
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": "#000"
                },
                "button": {
                    "background": "#f1d600"
                }
            },
            "type": "opt-out",
            "content": {
                "message": "We use cookies to ensure you get the best experience on this website and to provide services and advertising.",
                "dismiss": "Allow Cookies",
                "link": "Read our cookies policy.",
                "href": "http://www.MYWEBSITE.com/cookie-policy.html"
            },
            onInitialise: function (status) {
                var type = this.options.type;
                var didConsent = this.hasConsented();
                if (type == 'opt-out' && !didConsent) {
                    // disable cookies
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());

                    gtag('config', 'UA-XXXXXXXX-X', { 'anonymize_ip': true });
                }
            },
            onStatusChange: function(status, chosenBefore) {
                var type = this.options.type;
                var didConsent = this.hasConsented();
                if (type == 'opt-out' && !didConsent) {
                    // disable cookies
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());

                    gtag('config', 'UA-XXXXXXXX-X', { 'anonymize_ip': true });
                }
            },
            onRevokeChoice: function() {
                var type = this.options.type;
                if (type == 'opt-out') {
                    // enable cookies
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());

                    gtag('config', 'UA-XXXXXXXX-X', { 'anonymize_ip': true });
                }
            }
        });
    });
</script>


<!-- Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXX-X"></script>
</script>


<!-- Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXX-X"></script>

**Comment by alexmorleyfinch** [comment]
You've done pretty well to say your coding knowledge is zero!  👍 It's probably worth mentioning first that: If ALL you are using is GoogleAnalytics, and you use the `anonymize_ip` option (as it appears you are) then you don't actually need a cookie banner!! 😄 

Which is great, because banners are annoying.

From the code you posted, it looks like your code to `enable` is exactly the same as the code to `disable`. This is probably the issue.

You can take a look at this [issue](https://github.com/insites/cookieconsent/issues/387#issuecomment-405594539) to see my previous response to a similar problem.

You need two functions. An `enableCookies` function and a `disableCookies` function. You call these functions from the javascript hooks below.

In the `enableCookies` function you add the code with adds your GoogleAnalytics to the page.
In the `disableCookies` function you need to write some code that disables all cookies and reloads the page. See [here](https://stackoverflow.com/questions/179355/clearing-all-cookies-with-javascript) for details on how to delete all cookies.

Careful though, you don't actually want to delete ALL of the cookies. If you do, you'll also delete the cookie which remembers what the user chose. You only need to delete tracking cookies. I.E. cookies that contain personally identifiable information.

```js

function enableCookies() {
  // write some code to add Google Analytics
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-XXXXXXXX-X', { 'anonymize_ip': true });
}

function disableCookies() {
  // write some code to delete all cookies that are trackable
  // reload page
}

cookieconsent.initialise({

  // your options...

  onInitialise: function (status) {
    var type = this.options.type;
    var didConsent = this.hasConsented();
    if (type == 'opt-in' && didConsent) {
      enableCookies()
    }
    if (type == 'opt-out' && !didConsent) {
      disableCookies()s
    }
  },

  onStatusChange: function(status, chosenBefore) {
    var type = this.options.type;
    var didConsent = this.hasConsented();
    if (type == 'opt-in' && didConsent) {
      enableCookies()
    }
    if (type == 'opt-out' && !didConsent) {
      disableCookies()
    }
  },

  onRevokeChoice: function() {
    var type = this.options.type;
    if (type == 'opt-in') {
      disableCookies()
    }
    if (type == 'opt-out') {
      enableCookies()
    }
  },
});
```
