### ISSUE TITLE
How to only load Adwords conversion tag when cookies are accepted

### ISSUE THREAD

**Issue by Geert81** [insites/cookieconsent#377]
Hi,

I've been trying to figure this out for hours and cannot find how to only load the adwords conversion tag (the old one), when cookies are accepted.

I can do it with analytics, with the facebook pixel, but I cannot get the adwords tag to work. I specifically want to use the old one, because I only want this Google cookie (a marketing cookie) to be loaded on my conversion page.

It's the one that looks like this:
```html
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 1234567890;
    var google_conversion_label = "xxx-XXx1xXXX123X1xX";
    var google_remarketing_only = "false"
    var google_conversion_value = 10.0;
    var google_conversion_currency = "USD"
    /* ]]> */
</script>
<script type="text/javascript"
        src="//www.googleadservices.com/pagead/
		conversion.js">
</script>
<noscript>
    <img height=1 width=1 border=0
         src="//www.googleadservices.com/pagead/
		conversion/1234567890/
		?value=10.0&amp;currency_code=USD&amp;label=xxx-   
		XXx1xXXX123X1xX&amp;guid=ON&amp;script=0">
</noscript>
```

Has anyone done this and made sure it works (Google still gets the conversions)?

I've tried to hide it behind functions, innerhtml and so on, but it never works.

Thanks!

**Comment by Dolondro** [comment]
This is discussed further [here](https://github.com/insites/cookieconsent/issues/387#issuecomment-405594539)
