### ISSUE TITLE
pushdown issue

### ISSUE THREAD

**Issue by neoman666** [insites/cookieconsent#379]
Hi,

pushdown doesnt work with bootstrap 4 fixed top navbar.

**Comment by neoman666** [comment]
Here is a codepen for this issue...

https://codepen.io/anon/pen/yEzYez

Who can help?

**Comment by balazs184** [comment]
What is you set  "static" to  false?

**Comment by neoman666** [comment]
Is works with "static false".

In the description was the following: "static true"
See here... https://cookieconsent.insites.com/documentation/troubleshooting/
