### ISSUE TITLE
New service

### ISSUE THREAD

**Issue by jakefuller1** [insites/cookieconsent#384]
How do I add a service if it only returns a 2 letter country code response via text/html, i.e. KR for Korea? No json.

I am trying to send http://ipservicedemo.com/123.45.67.89?mysite.com and it would respond KR (where 123.45.67.89 is user ip)

**Comment by Dolondro** [comment]
The site you have referenced doesn't exist so I assume it's psuedocode. Given the slightly lacking details, I assume the code would need to look something like this
```js
cookieconsent.initialise({
    location: {
        serviceDefinitions: {
            geoip: function() {
                return {
                    url: 'https://ipservicedemo.com/',
                    callback: function(done, response) {
                        return {code: response);
                };
            },
        },
        services: [
            'geoip'
        ]
    }
});
```
