### ISSUE TITLE
How can i disable check if cookies consent is opt-in the only load the you-tube video to i frame

### ISSUE THREAD

**Issue by Reshmysandeep** [insites/cookieconsent#387]
I have an iFrame 
<iframe width="1903" height="1070" class="swiper-slide-video" src="http://www.youtube.com/embed/ixxxxxxxxs?loop=1&amp;controls=0&amp;showinfo=0&amp;playlist=ih7GGPN1d4s&amp;start=100&amp;wmode=transparent&amp;enablejsapi=1&amp;api=1&amp;enablejsapi=1&amp;api=1" allowfullscreen="" height="270" width="480"></iframe>
which is running on the landing page on my website.  I need to block it , If the cookies consent is not allowed. how will i do it

**Comment by kieran23101** [comment]
You can simply put something over the top of it, for example: 
`<div id="blank" style="display:none; position:absolute; top:0; left:0; width:1903px; height:1070px;">`

Then in the documentation of cookieconsent, you should find a part where it does an action like disabling cookies, change that to the following: 
`document.getElementById("blank").style.display="block";`

Ensure that the Iframe is positioned relatively

**Comment by alexmorleyfinch** [comment]
```js

function enableCookies() {
  // write some code to add the youtube iframe to the page
  document.body.appendChild('<iframe width="1903" height="1070" class="swiper-slide-video" src="http://www.youtube.com/embed/ixxxxxxxxs?loop=1&controls=0&showinfo=0&playlist=ih7GGPN1d4s&start=100&wmode=transparent&enablejsapi=1&api=1&enablejsapi=1&api=1" allowfullscreen="" height="270" width="480"></iframe>')
}

function disableCookies() {
  // write some code to delete all cookies that are trackable
  // reload page
}

cookieconsent.initialise({
  onInitialise: function (status) {
    var type = this.options.type;
    var didConsent = this.hasConsented();
    if (type == 'opt-in' && didConsent) {
      enableCookies()
    }
    if (type == 'opt-out' && !didConsent) {
      disableCookies()s
    }
  },

  onStatusChange: function(status, chosenBefore) {
    var type = this.options.type;
    var didConsent = this.hasConsented();
    if (type == 'opt-in' && didConsent) {
      enableCookies()
    }
    if (type == 'opt-out' && !didConsent) {
      disableCookies()
    }
  },

  onRevokeChoice: function() {
    var type = this.options.type;
    if (type == 'opt-in') {
      disableCookies()
    }
    if (type == 'opt-out') {
      enableCookies()
    }
  },
});
```
