### ISSUE TITLE
How can i block youtube ,facebook and google share using cookie consent.

### ISSUE THREAD

**Issue by Reshmysandeep** [insites/cookieconsent#390]
Please help me, I trying to implement cookie consent on my website. I need to provide a checkbox for user acceptance like Marketing,  analytics etc . how can I implement these using cookies consent?

**Comment by Dolondro** [comment]
This isn't something that cookie consent is designed for. This tool only provides a yes/no acceptance for cookies. I believe this is something that may be done by [a tool we are making](https://github.com/insites/cookieconsent/issues/409#issuecomment-404567026) to deal with GDPR compliance, but I'm not currently involved in the development of it, so I cannot say for certain.
