### ISSUE TITLE
disable revoking tab

### ISSUE THREAD

**Issue by jmar83** [insites/cookieconsent#391]
hi there,

i have that from the internet, but i do not really belive that's the only way to realize that behavior?

`                          document.getElementsByClassName("cc-revoke")[0].style.visibility = "hidden";
`

Regards,
Jan

**Comment by alexmorleyfinch** [comment]
Setting the option `revokable: false` should remove this button. This is the best method for disabling the revoke button.

If you just want to hide the button forever you could attach a specific style for it. E.G.

```css
.cc-revoke { display: none }
```

There is also a function on the popup object `toggleRevokeButton()` which accepts true or false. You need to get the popup instance first though. You get it from the callback of the `initialise` function.

```js
cookieconsent.initialise({...options...}, function(popup){
  popup.toggleRevokeButton(false) // this will hide the revoke
})
```

**Comment by jmar83** [comment]
Thank you very much!!
Regards, Jan

**Comment by gdm85** [comment]
> Setting the option `revokable: false` should remove this button.

Not working, as far as I can see.
