### ISSUE TITLE
No callback available if regional law allows cookies

### ISSUE THREAD

**Issue by tylercamp** [insites/cookieconsent#393]
If location and regional law are enabled, and the user's region has no cookie laws, no callbacks will be invoked since `enabled` is automatically set to `false`. Cookie-based logic has to occur in a cookieconsent callback, of course (that's the point), but nothing will happen in this case, so my cookie logic never runs. This is using 3.0.3, as linked on https://cookieconsent.insites.com/download/

**Comment by alexmorleyfinch** [comment]
This will be added in the next release, coming real soon
