### ISSUE TITLE
Need a callback for when the country has no cookie law

### ISSUE THREAD

**Issue by ndbroadbent** [insites/cookieconsent#394]
I noticed this library is missing a callback for when the country has no cookie law. I want to automatically "allow cookies" at that point. For example, when the IP address is geolocated to the US, I want to run the function that sets up Google Analytics.

**Comment by alexmorleyfinch** [comment]
This callback has been added and will be in the next release

**Comment by TheMangoTrain** [comment]
Any update on this and/or early documentation?
