### ISSUE TITLE
Found bug in last version (Uses status keys instead of values)

### ISSUE THREAD

**Issue by mikedjo** [insites/cookieconsent#397]
Hello,

I had to change the current static settings (cookie values) to 0, 1 or 2 instead of deny, dismiss & allow.

When i did:
` window.cookieconsent.status = {deny: '0',     allow: '2',     dismiss: '1'};`

I found out that it kept using cookie values "deny, dismiss & allow", so I had a look in cookieconsent.js.

In function Hasanswered:
Line 553: `Object.keys(cc.status)`

should be:
Line 553:  `Object.values(cc.status)`

-------
In function setStatus:
Line 573: `if (Object.keys(cc.status).indexOf(status) >= 0) {`

Should be:
Line 573: `if (Object.values(cc.status).indexOf(status) >= 0) {`

-------
In function handleButtonClick:

I added `match = cc.status[match];` inside the `if (match) {` on line 751

Mike

**Comment by MaximilianUE** [comment]
Same here. Can we create a fork or contribute as maintainer?

**Comment by DanielRuf** [comment]
> Same here. Can we create a fork or contribute as maintainer?

I would like to contribute, help crushing PRs and bugs, answer and close issues and help as maintainer.

**Comment by RabsRincon** [comment]
It should, but I'm not seeing where it's done, and testing locally does not change the values. 
Now that I think about it, might the reason be the bug @mikedjo reported?

**Comment by DanielRuf** [comment]
> I found out that it kept using cookie values "deny, dismiss & allow", so I had a look in cookieconsent.js.
> 
> In function Hasanswered:
> Line 553: Object.keys(cc.status)
> 
> should be:
> Line 553: Object.values(cc.status)

In general this is the issue, they keys and not the values are used.

**Comment by RabsRincon** [comment]
I did not realize the __allowedStatuses is only checking that the status keys are valid for its usecase. Sorry for the confusion. So yeah, the error here is the one reported by the OP. :)

**Comment by DanielRuf** [comment]
Do we have a PR for this?

**Comment by alexmorleyfinch** [comment]
I'm just curious as to why you'd need to change the values in the first place? They were never designed to be changed. The `cc.status` is more of an enumeration that you use programatically.

I.E

```js
if (getCookie('cookieconsent_status') === cc.status.allow) {
  // blah
}
```

**Comment by RabsRincon** [comment]
My usecase is to set the allow value to the current hash of the cookie policy and some other bits, making it invalid if I push a change (So users have to give their consent again) or similar. This then renders `cc.status.allow` unnecessary as it's not anymore the correct value and would always compare false.
Hope it helps :)

**Comment by alexmorleyfinch** [comment]
Ah okay, this is useful use-case actually. This is more of a feature request than a bug report though, as the `cc.status` was originally meant for comparisons only. This isn't something we've got the time to implement though, especially seeing as we will be deprecating the tool in the coming months. Feel free to make a fork or a pull request though and we'll check it out!
