### ISSUE TITLE
Cookie-Zustimmung "target _self

### ISSUE THREAD

**Issue by ofv1907** [insites/cookieconsent#399]
Hallo, wie kann ich die Datenschutzmitteilung im selben Fenster (target _self) öffnen?

  "dismiss": "Verstanden",
    "messagelink": "Mehr erfahren...",
    "href": "/impressum",
    "target": "_self"

Danke.

**Comment by davidjamartin** [comment]
https://github.com/insites/cookieconsent/pull/396
