### ISSUE TITLE
FreeGeoIP Deprecation message

### ISSUE THREAD

**Issue by Schuer84** [insites/cookieconsent#401]
The current implemenation of FreeGeoIP gives the following warning: 

"This API endpoint is deprecated and will stop working on July 1st, 2018. For more information please visit: https://github.com/apilayer/freegeoip#readme"

**Comment by Nemo64** [comment]
Here is a good replacement: https://geoip.nekudo.com

**Comment by exhtml** [comment]
Now the warning is an error in the console:
"Failed to load resource: the server responded with a status of 403 (Forbidden)"
calling to http://freegeoip.net/json/

Thanks for your help!

**Comment by dev-hero** [comment]
@Nemo64 The open geo api you referenced works like a charm and does not require a key. TY!

**Comment by Dolondro** [comment]
We're going to remove FreeGeoIP very shortly to address this.

Although your service seems pretty legit @Nemo64, I'm very hesitant to push people to automatically use a third party service that's run by an individual, heck, in this world of GDPR pushing people to use third party companies that are presumably accountable for what they do is probably not a wise choice.

For those who do want to implement this using Nemo64's API, you should be able to do it using the below code, although I'd personally recommend hosting your own copy of the [software](https://github.com/nekudo/shiny_geoip) instead.

```js
cookieconsent.initialise({
    location: {
        serviceDefinitions: {
            geoip: function() {
                return {
                    // This service responds with JSON, but they do not have CORS set, so we must use JSONP and provide a callback
                    // The `{callback}` is automatically rewritten by the tool
                    url: 'https://geoip.nekudo.com/api/?callback={callback}',
                    isScript: true, // this is JSONP, therefore we must set it to run as a script
                    callback: function(done, response) {
                        try {
                            var json = JSON.parse(response);
                            return json.type === "error" ? new Error('Error [' + (json.msg) + ']' : {code: json.country.code};
                        } catch (err) {
                            return new Error("Error: Invalid response [" + err + ")");
                        }
                    }
                };
            },
        },
        services: [
            'geoip'
        ]
    }
});
```
