### ISSUE TITLE
Suspicious email announcing a new CDN from the Insites Team

### ISSUE THREAD

**Issue by jigawot** [insites/cookieconsent#402]
I just got an email informing me that the official CDN for cookieconsent is being changed from cdnjs.cloudflare.com to cdn.cookiescriptcdn.com and I need to update to prevent interruption of service. When I tried to investigate, I can't find any information on https://cookieconsent.insites.com/ that would indicate the CDN has changed. Has anyone else received this email?

Seems phishy to me.

**Comment by jigawot** [comment]
Here's a copy of the email:

![image](https://user-images.githubusercontent.com/9836477/42112871-2ca07c94-7b9e-11e8-9e22-b7db6ef86d98.png)

**Comment by Seao** [comment]
Hmm, it's strange indeed. I didn't received this email, but it looks like a malicious script injection attempt. Right now the javascript hosted on this fake cdn is exactly the same than the original one, but this can change at any time. And without subresource integrity checking, anyone using it will be corrupted 🙉

**Comment by Travisism** [comment]
I also got this email. As @Seao mentioned, the scripts are currently the same, but given I can find no info from Insites, I'm assuming this is a phishing attempt until proven otherwise.

**Comment by yeago** [comment]
also very strange not to hear from the contributor during this time....

**Comment by Dolondro** [comment]
Hi, this is nothing to do with us, do not change the URL.

Can you paste/send me the raw email headers so I can try and verify the nature of the email spoofing?

**Comment by Dolondro** [comment]
Thanks, I've filed an abuse report with Freshdesk which is where the message seems to have originated and I'll update the readme once I'm back on the clock to reduce the chances of someone falling for it.

**Comment by Dolondro** [comment]
I've shoved a warning on the readme, hopefully that should provide more clarification for anyone who gets a phishing email 👍
