### ISSUE TITLE
No way to view cookie settings without revoking consent

### ISSUE THREAD

**Issue by nsrosenqvist** [insites/cookieconsent#403]
~~Even if no choice is made after reopening a revokable consent banner the cookie is reset. A user can easily disregard it or not even wanting to change their choice and simply navigate away, then, incorrectly, it would have changed their status.~~

**Update:** there's currently no way of simply reviewing your cookie settings without causing them to be revoked. The revoke button is incorrectly labeled simply "Cookie Policy" which would cause you to believe it just reopens the banner for you to review it, not immediately revoke your consent.

**Comment by nsrosenqvist** [comment]
Ok, I think I understand what is happening now. Clicking the "Cookie Policy" fires the revoke event, so that is how revoking has been implemented. Shouldn't this instead be in another button after re-opening it?

**Comment by alexmorleyfinch** [comment]
This can be achieved by playing around with the configuration. The cookie is revoked (cleared) when a button is clicked with the className `cc-revoke`. Therefore, to prevent this behaviour you just need to remove that class. You can use the `revokeBtn` option which allows you to change how to revoke button is rendered. The default is

```
{
    revokeBtn: '<div class="cc-revoke {{classes}}">{{policy}}</div>',
}
```

which you can change to:

```
{
    revokeBtn: '<div class="my-special-revoke {{classes}}">Show options!</div>',
}
```

The `{{classes}}` placeholder is replaced with positioning classes like `cc-bottom` and animation classes like `cc-animate`. Therefore if you remove it, it may have unexpected behaviour.

You now have a button, but nothing will happen when you click on this button. Therefore, you need to attach a handler:

```
document.querySelector('.my-special-revoke').addEventListener('click', function() {
  // show popup.
})
```

You need to get a reference to the `popup` object though so you can `open` and `close` freely.

You do this using the callback method in the `initialise` function. See the full snippet below:

```
      var ccPopup;

      cookieconsent.initialise({
        // ... your options ...
        revokable: true,
        revokeBtn: '<div class="my-special-revoke {{classes}}">Show options!</div>',
      }, function (popup) {
        ccPopup = popup;
      });

      document.querySelector('.my-special-revoke').addEventListener('click', function () {
        ccPopup.open();
      });
```

The last thing you need to do is change the styles of your new button. The revoke button is also styled using the `cc-revoke` className (not the best idea but hey ho) so when you remove that class, you also remove all the base styles like: `position: fixed` etc. So you'll need to add those styles back to get it working correctly.

```
    .my-special-revoke {
      position: fixed;
      overflow: hidden;
    }
```

Hope this helps
