### ISSUE TITLE
X-Requested-With Headers Problem using ipstack.com

### ISSUE THREAD

**Issue by Jonathan-Bryan** [insites/cookieconsent#405]
As commented here #401 freegeoip is deprecated. The replacement for freegeoip is ipstack.com. I have made a new service (see below) but the request fails because cookie consent adds the request header 'X-Requested-With' and it appears that ipstack does not support this. I get the error...

> Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.

    location: {
      serviceDefinitions: {
        ipstack: function(options) {
          return {
            url: '//api.ipstack.com/check?access_key=APIKEY&fields=country_code',
            callback: function(done, response) {
              // This function must parse the 'response' and return the country code, or fail.
              // If this function doesn't fail correctly, then the next service will not run.
              // Therefore, it's generally best to add a try {...} catch () {...} block
              try {
                var json = JSON.parse(response);
                if (json.country_code) {
                  return {code: json.country_code}
                }
                throw 'Could not find a country code in the response';
              } catch (err) {
                return new Error('Invalid response (' + err + ')');
              }
            },
          };
        },
      },
 
      services: [
        'ipstack'
      ]
    }

Is there a way to disable this request header? It appears hard coded to me but hopefully I'm mistaken. Or is there some other solution that I'm missing? Thanks!

**Comment by exhtml** [comment]
Any news about this issue?
Thank you so much!

**Comment by Jonathan-Bryan** [comment]
My workaround has been to move over to https://ipinfodb.com/
This service is supported out of the box by cookieconsent. You just need to sign up for an API key (which is a painful experience as they have a terrible drop down menu for selecting your city). And then you configure cookie consent to use your api key...

    "location": {
      "services": [
        {"name":"ipinfodb", "interpolateUrl": {"api_key": "YOURAPIKEY"}}
      ],
    }

**Comment by dhurba87** [comment]
Thanks @Jonathan-Bryan . It worked.

**Comment by alexmorleyfinch** [comment]
There's currently no way to disable this. I'm not sure why it was added tbh. I'll make a PR to remove it in the next release. Nice job on the workaround @Jonathan-Bryan
