### ISSUE TITLE
Expected behaviour when cookies are accepted or declined?

### ISSUE THREAD

**Issue by kaleidografik** [insites/cookieconsent#407]
When using cookieconsent, what is the expected behaviour when a user accepts or declines? Obviously the popup notice itself gets hidden, but what happens in terms of the actual cookies themselves? Looking in the inspector, no cookies seem to be deleted?

I'm installing on a Wordpress site and there are a few essential cookies required to log the username etc, and wondering if the script should be clearing all cookies if permission is denied. Does anything happen 'out of the box' or do callbacks need to be set to disable/enable cookies?

The code on this page (https://cookieconsent.insites.com/documentation/disabling-cookies/) seems to suggest it is a manual process, but not sure entirely what the script is offering if it doesn't deal with this automatically?
Thanks

**Comment by InsanityMeetsHH** [comment]
This plugin saves only a cookie named "cookieconsent_status" and it is your task to handle this value (allow, dismiss or deny) in your source code or with the [callbacks](https://cookieconsent.insites.com/documentation/disabling-cookies/). Depends on your [compliance](https://cookieconsent.insites.com/documentation/compliance/).
[Example](https://github.com/InsanityMeetsHH/gulp-templating/blob/master/templates/layouts/base.phtml#L78)

**Comment by alexmorleyfinch** [comment]
@InsanityMeetsHH got it bang on 👍 There is some more info on [this](https://cookieconsent.insites.com/documentation/disabling-cookies/) page. If you are struggling to understand the page, just re-open this issue and I'll be happy to help you out some more.
