### ISSUE TITLE
Store consents in database

### ISSUE THREAD

**Issue by bigmmind** [insites/cookieconsent#408]
Hello!

Is there any existing solution to store consents in database ?
We've installed Cookie Consent on our site and even disabled google analytics and other trackers before the consent is provided and we are very happy with this solution.
However the only thing missing to fully comply with GDPR is ability to store evidences of the given consents.

Thanks in advance.

**Comment by alexmorleyfinch** [comment]
There is currently no solution for this. CookieConsent is not designed for GDPR. If you are a javascript wizard or you know someone who is, you *could* potentially hack this in, as there is a javascript callback when the user clicks a button.

You could do something like:

```js
window.cookieconsent.initialise({
  onStatusChange: function(status) {
    // make API request to store the value in a database
    //makeRequest('mySpecialEndpoint', {
    //  personId: <some_id>,
    //  consentLevel: status
    //})
  }
})
```

However, I am __NOT__ an expert in GDPR and the fact that you are storing an ID which directly relates to a user *could* actually be against GDPR. I'm not sure, it depends how you implement it I think.

CookieConsent was not designed for GDPR, so you'll really have to know what you're doing if you want to use it to be GDPR compliant.

As an aside, we are currently working on a tool similar to CookieConsent that will be GDPR compliant, but this new tool has not been released yet.

You can find a little extra info about CookieConsent and compliance support on a previous [thread](https://github.com/insites/cookieconsent/issues/409)

**Comment by bigmmind** [comment]
Thanks a lot for a detailed answer, Alex.

Would be interested to know about new tool once it is launched. Thank you
