### ISSUE TITLE
PageSpeed optimization

### ISSUE THREAD

**Issue by mkoonrad** [insites/cookieconsent#41]
I suggest to:

1. Enable compression of http://s3.amazonaws.com/cc.silktide.com/dark-bottom.css and another style.
2. Add browser caching.
3. Optimize images like: https://s3-eu-west-1.amazonaws.com/assets.cookieconsent.silktide.com/cookie-consent-logo.png.

Please look at page with cookieconsent2 by PageSpeed Insights by Google. Let's make websites faster.

**Comment by marcinmaruszewski** [comment]
+1

I also ask to fix this!

**Comment by lolametro** [comment]
+1

**Comment by hnnweb** [comment]
To be fair, the logo doesn't even show? So why is it included?

**Comment by mxdpeep** [comment]
logo is shown in compact block design

**Comment by DenisMir** [comment]
I would love to see that one as well. +1

**Comment by Dolondro** [comment]
Since we moved to CDNJS as a host, that correctly does both the caching and the compression.

The image is (I believe) no longer included in version 3 of the plugin.
