### ISSUE TITLE
A One of your External CDN hacked

### ISSUE THREAD

**Issue by biapar** [insites/cookieconsent#411]
I wish to inform that a one of your CDN was hacked.
This is the image with the code:

![image](https://user-images.githubusercontent.com/661517/42735967-ab369ee6-885d-11e8-8180-2a8c1ad5ff1b.png)

**Comment by nebrot** [comment]
Perhaps related to #402 and this warning https://github.com/insites/cookieconsent/commit/79bc7a584eca792435a7c27db97136dd9f376322 ?

**Comment by DanielRuf** [comment]
Best solution: never use a CDN.

**Comment by biapar** [comment]
@nebrot maybe, but the javascript code was changed. I sure that the hacked CDN was reported by the wizard last week.

**Comment by biapar** [comment]
@DanielRuf  or not use one free or emulate a CDN with more own server.

**Comment by DanielRuf** [comment]
> @nebrot maybe, but the javascript code was changed. I sure that the hacked CDN was reported by the wizard last week.

Well, this is what the attackers goal was. Please use the official CDN or no CDN at all and host the files on your server (you can use npm / yarn).

**Comment by DanielRuf** [comment]
> emulate a CDN with more own server.

Not a solution / good idea in general.
Please consider fallbacks if a CDN is down or if its content has changed (SRI hashes).

**Comment by DanielRuf** [comment]
> or not use one free

This is not the issue.

Please provide the CDN url that you use.

**Comment by DanielRuf** [comment]
Never saw cdn.front.to as official CDN.

**Comment by DanielRuf** [comment]
See https://cookieconsent.insites.com/download/

**Comment by Dolondro** [comment]
@DanielRuf is right, this isn't a CDN we've ever used or endorsed and thus nothing to do with us.
