### ISSUE TITLE
Close cookie consent bar manually

### ISSUE THREAD

**Issue by AlexanderHofmeister** [insites/cookieconsent#412]
Hi there,

is there a way to close the cookie bar by an other javascript function (no hook, just a function)? Or should I just add the cookieconsent_status = dismiss as cookie by this function and the cookie bar will get dismissed automatically? 

We need to have the dismiss button in the middle of the text. I add an listener to a link, but the bar will not close obviously. 
```js
$(document).on ("click", "#dismissCookieConsent", function () {
  // do other stuff 
  // dismiss cookie consent -  ? 
});
```

Any idea/hin?

Thanks,

Alexander

**Comment by AlexanderHofmeister** [comment]
I just set the cookie manually now. Can be closed.

**Comment by alexmorleyfinch** [comment]
As an aside you can call `this.open()`, `this.close()`, `this.setStatus(cookieconsent.status.allow)` and `this.clearStatus()` in the callback hooks. This may be useful :)

**Comment by AlexanderHofmeister** [comment]
I see. If we need it, I can refer to it. Unfortunately, the customer changed her mind.

**Comment by fotiDim** [comment]
@alexmorleyfinch I am trying to do `this.setStatus(cookieconsent.status.allow)` within `onNoCookieLaw: function (countryCode, country) {}` and I am getting `this.setStatus is not a function at Object.onNoCookieLaw`. Any suggestions?

**Comment by sarinkarma** [comment]
@fotiDim i'm having the same issue. Did you find a solution?

**Comment by fotiDim** [comment]
@sarinkarma not really. I ended up setting doing something like that:
```
var gaCode = 'UA-XXXXXX-X';
window['ga-disable-' + gaCode] = true;
if(getCookie('cookieconsent_status') === "allow") {
  window['ga-disable-' + gaCode] = false;
}

function getCookie(name)
  {
    var re = new RegExp(name + "=([^;]+)");
    var value = re.exec(document.cookie);
    return (value != null) ? unescape(value[1]) : null;
  }
```
which enables Google analytics when the user accepts cookies. It was basically what I wanted to do with it.
