### ISSUE TITLE
Cookie categories consent

### ISSUE THREAD

**Issue by eafiontzi** [insites/cookieconsent#416]
Hello,
is there an option to categorize cookies (Functional Cookies, Preferences Cookies, Performance Cookies, Advertising Cookies) and the user can consent or not to one or many of these categories? Or are you planning on implementing such a feature?
Thanks

**Comment by Dolondro** [comment]
This is outside the scope of this project which purely does a yes/no to cookies.

This is potentially a feature that may be in [our GDPR](https://github.com/insites/cookieconsent/issues/409#issuecomment-404567026) plugin in the near future (although I'm not involved in it, so I cannot be certain) but it isn't something that you will be able to do with this tool.

**Comment by niccoX** [comment]
You can use this script that does what you are asking for:

https://termsfeed.com/cookie-consent/
