### ISSUE TITLE
GDPR solution

### ISSUE THREAD

**Issue by uzigone** [insites/cookieconsent#439]
Hello,

I have some toruble getting this plugin to work in the correct way. I want the plugin to have 2 choices:

- Required cookies
- Experience cookies

With the first one is the cookies from the website itself, like session, analytics etc.

The second one I want for example the sharing buttons, facebook widget, twitter widget, being able to block or let through. There is nothing described how to achieve this. Is this plugin capable of being GDRP compliant?

**Comment by Dolondro** [comment]
This plugin was created before GDPR was a thing, we are working on a [GDPR solution](https://github.com/insites/cookieconsent/issues/409) but it is not currently complete.
