### ISSUE TITLE
How to install this addon ?

### ISSUE THREAD

**Issue by ploraky** [insites/cookieconsent#442]
Hello ,

Please I want to install a cookie consent that have the ability to GeoLocate and only show the cookies bar to people in the countries that have a cookie law , and also support  different types of compliance to show specific message for every specific country according to it's cookies law

And I found your amazing addon : https://github.com/insites/cookieconsent

But I don't know how to install it with these features ?? ( I downloaded https://github.com/insites/cookieconsent/archive/master.zip and uploaded it into my cpanel and extract it , but i don't know what's the next step ?? )

Please help me .. And thanks very very much on advance .

**Comment by icemac** [comment]
See https://cookieconsent.insites.com/download/ how to configure and use the add-on.

**Comment by ploraky** [comment]
Yes i tried it , but the cookie consent appear to all countries ! , and I want cookie consent have the ability to GeoLocate and only show the cookies bar to people in the countries that have a cookie law , and also support different types of compliance to show specific message for every specific country according to it's cookies law , but I don't know how to add these features in the code !
Please help me , and Thanks very much for your reply .

**Comment by alexmorleyfinch** [comment]
To enable the location feature, you set `{location: true}` in the configuration. I.E.

```js
cookieconsent.init({
  // ... your options
  location: true
})
```

However this feature uses free location services by default, which may have a limit or expire. You can configure the location service to your your own, but this is an advanced feature. Documentation can be found [here](https://cookieconsent.insites.com/documentation/location-services-cookie-law/)
