### ISSUE TITLE
Add the title attribute 

### ISSUE THREAD

**Issue by hahlamine** [insites/cookieconsent#447]
Hi,

I've search but never found how to add title attribute in the links (privacy link and button link) to be W3C HTML Valid.

Thanks for your good job !

**Comment by thexmanxyz** [comment]
@hahlamine title is an option attribute and isn't mandatory as far as I know. However youcan always override the default link markup via the following [parameters](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L265-L280)

**Comment by hahlamine** [comment]
@thexmanxyz Perfect ! Thanks a lot for your contribution !

**Comment by thexmanxyz** [comment]
@hahlamine Glad to hear that this helped you. :)
