### ISSUE TITLE
Dismiss button not accessible from keyboard

### ISSUE THREAD

**Issue by dasgrafikerin** [insites/cookieconsent#453]
I just implemented the cookie consent and tried to click on the dismiss button from the keyboard. Doesn't work. Clicking on the Link works though. How can I change that or could you please fix that?
Thanks a lot and thank you for this nice Plugin.

**Comment by alexmorleyfinch** [comment]
There is no support in the tool for this at the moment, but you *should* be able to focus the dismiss button, and then click it with the keyboard by pressing enter when it is focused.

```js
document.querySelector('.cc-dismiss').focus();
```

You could also add your own keyboard handler. I.E:

```js
cookieconsent.initialise({
  // ... options ...
}, function(popup) {
  var handler = function(event) {
    // if key <enter>
    if (event.keyCode === 13) {
      popup.setStatus(cookieconsent.status.ALLOW);
      popup.close();

      document.removeEventListener('keyup', handler);
    }
  };
  document.addEventListener('keyup', handler)
})
```

This will accept and close the popup if enter if pressed
