### ISSUE TITLE
How to make popup visible after 5 seconds?

### ISSUE THREAD

**Issue by suslikt** [insites/cookieconsent#457]
Hi! Now the window opens immediately when you visit the page, how to slow down its appearance for 5 seconds? 
It seems that this function is responsible for appearance
`function o(e){this.openingTimeout=null,t.removeClass(e,"cc-invisible")}`

**Comment by iclukas** [comment]
If you want the banner to appear after 5 seconds, you can wrap `initialise()` in a `setTimeout()`.

Like so:
```
window.addEventListener("load", function(){
  setTimeout(function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#000"
        },
        "button": {
          "background": "#f1d600"
        }
      }
    });
  }, 5000);
});
```

**Comment by suslikt** [comment]
Thank you! it works.
