### ISSUE TITLE
Bug: opt-out, opt-in in version 3.1.0

### ISSUE THREAD

**Issue by TilenKreca** [insites/cookieconsent#460]
## There is a bug in version 3.1.0. Same settings are for opt-out && opt-in.

In cookieconsent.js file under compilance property:

### This is working example from version 3.0.6:
```javascript
compliance: {
        'info': '<div class="cc-compliance">{{dismiss}}</div>',
        'opt-in': '<div class="cc-compliance cc-highlight">{{dismiss}}{{allow}}</div>',
        'opt-out': '<div class="cc-compliance cc-highlight">{{deny}}{{dismiss}}</div>',
},
```
### This is currently in version 3.1.0:
There is {{deny}}{{allow}} in ```<div>``` for both opt-out && opt-in. 
```javascript
 compliance: {
        info: '<div class="cc-compliance">{{dismiss}}</div>',
        'opt-in':
          '<div class="cc-compliance cc-highlight">{{deny}}{{allow}}</div>',
        'opt-out':
          '<div class="cc-compliance cc-highlight">{{deny}}{{allow}}</div>'
},
```

**Comment by alexmorleyfinch** [comment]
Weirdly enough, this is intended. 'opt-out' used to be {deny}{dismiss} but this caused other issues. As in, both deny and dismiss are a "no" answer. Therefor, the opt out banner had no option to {allow}, which was clearly wrong.

You can change it back if you like, it just means a little extra configuration.

```js
compliance: {
  'opt-out': '<div class="cc-compliance cc-highlight">{{deny}}{{dismiss}}</div>'
}
```
