### ISSUE TITLE
Phoning MaxMind...

### ISSUE THREAD

**Issue by jhabdas** [insites/cookieconsent#504]
https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L1224

Really. You've gotta be kidding...

**Comment by jhabdas** [comment]
You should be using this and stop feeding maxmind data you're only exacerbating the problem.

https://tracker.debian.org/pkg/geoipupdate

**Comment by DanielRuf** [comment]
This is just one of many services that are supported but not directly used.

**Comment by DanielRuf** [comment]
I hope you know that this is just a JS API for geolocation as cookies and optin / optout can be configured to only affect users in specific countries.

**Comment by DanielRuf** [comment]
See https://cookieconsent.insites.com/documentation/location-services-cookie-law/

**Comment by jhabdas** [comment]
That's sufficiently confusing enough I doubt most will do it. Good to know.
