### ISSUE TITLE
Cookie prompt seems to be an AdSense violation because it can cover an ad

### ISSUE THREAD

**Issue by shuvee** [insites/cookieconsent#51]
I have looked at most of your themes (admittedly not all), and the ones I checked can cause the cookie message to overlay an AdSense ad (either immediately, or when the page is scrolled). This is an AdSense Policy violation, and if the button falls near or on top of an ad, it can lead to an invalid click (but it is a violation, regardless of whether invalid clicks occur). It seems to me that Cookie Consent can't be used on pages with AdSense ads, meaning one would have to route all EU visitors to a "doorway" page with no ads. Or am I missing something?

**Comment by HmmmUK** [comment]
I see what you are saying - try the top or bottom themes these shouldn't overlay an ad.

FWIW I'm not 100% sure cookieconsentv2 is compliant for Google's new AdSense announcement - but I'm hoping so as I've installed it!
v1 has the option to turn off cookies - that's not available in the simpler v2, but Google's recent announcement isn't completely clear to me (I've asked Google and Silktide via Twitter but no reply)...

**Comment by oliveremberton** [comment]
Two of the built-in themes should push the webpage down. Go here:

https://silktide.com/tools/cookie-consent/download/

and try the first and the 5th theme option, these should move the page, but never appear on top of it.

You also have the ability to create your own themes with a little custom CSS if you wish.

**Comment by shuvee** [comment]
Thanks to both of you! I was not looking at the cookie prompts with my brain turned on. I had chosen the first theme and you are correct: it does not overlay the page itself. (And yes, I know I could create custom CSS, but I have already spent more time on this AdSense requirement than my earnings justify ... my CSS coding skills are not what they should be). Again, thank you!

**Comment by HmmmUK** [comment]
@oliveremberton Hi. Any thoughts on whether v1 and/or v2 is compliant for Google's recent AdSense announcement re. EU Cookies?   Google link to you, so hopefully you've had time to think about this?
Obviously v2 is much easier to implement so it would be good to know ASAP.
Thanks...

**Comment by HmmmUK** [comment]
I've just been reading forum comments about the consent banner covering ads and had a re-think about what I'm doing and the previous comments here...!

The 1st and 5th themes mentioned earlier push the page contents down when displayed BUT then stay in place when the page is scrolled - so will cover ads!

**Comment by shuvee** [comment]
The banner seems to drop down a pixel when you scroll, or at least it does so on my (sloppily coded) site. So you see a tiny squiggle at the top, corresponding to whatever is that many pixels above the banner - and making it obvious that the banner is overlaying the page. If it stayed snug against the top, one could argue that the "page" is the area below the banner, and maybe keep Google happy. Silktide folks? Is that a problem in general that you can fix? (The bottom banners seem to sit 8 to 10 pixels above the bottom of the screen, so maybe this positioning issue isn't just my site ...).

**Comment by shuvee** [comment]
Also, the (top and bottom) banners are not responsive, or at least they don't adjust properly. I tested on a Nexus 4 in both portrait and landscape orientation ... Are we having fun yet?

**Comment by HmmmUK** [comment]
I'm not seeing the extra padding/pixels you mention so I guess this is down to your sites CSS/code?

NB. Changing the CSS for:  cc_container from position:fixed to position:static allows the banner to scroll with the page, so it doesn't cover any ads. 

Positioning the banner at the top of the page and allowing it to scroll works well and looks more subtle to me :)

**Comment by shuvee** [comment]
Thanks HmmmUK. I made the change to the javascript to allow the banner to scroll with the page. I am still uneasy about the whole thing, especially not knowing AdSense's position regarding showing their ads before cooke consent has been given. But at least I know more about this particular solution than I knew before!

**Comment by chrismagenta** [comment]
There is always something with Adsense that needs updating. Get used to it. Just think of the fun we all have spending sleepless nights getting it to work. Now EU cookie compliance requires that no cookie is loaded until it has been implicitly allowed by pressing a button. This means if you are using Adsense you need to use version 1 not 2 so the advertisements do not display until the cookie is accepted. Adsense says all publishers must comply with EU compliance rules. That includes the whole world of publishers inc USA.

**Comment by HmmmUK** [comment]
@chrismagenta I'm not sure you're correct there.
This is definitely wrong: "...so the advertisements do not display until the cookie is accepted."

FWIW - AdSense adverts will still display with or without cookies!
Cookies just allow Google to target the ads.

**Comment by chrismagenta** [comment]
Hi  HmmmUK this is the case. See accountants.usa121.com if you do not believe. Adds do not display until cookies are allowed. I use version 1 of Cookieconsent to do it.

**Comment by HmmmUK** [comment]
Hi - try turning cookies off in your browser and visiting some sites running AdSense. You'll still see the ads! :) 
If rejecting cookies stopped ads there would be lots of people doing it - easier than installing an ad-blocker! 

I haven't investigated 'v1' does it involve modifying the AdSense code and is this stopping it running?
If your visitors aren't seeing your ads without accepting your 'cookie consent' then I would imagine your ads won't be working very well for you...

**Comment by oliveremberton** [comment]
Cookie Consent v1 does provide options to disable ads (or anything else) if you don't choose to accept cookies, this is called "explicit consent". We don't support that in v2 as only a microscopic fraction of users were using it, and it massively complicates the plugin.

**Comment by piiupilt** [comment]
Cookie Consent v3 is available now and it has a built-in non-fixed pushdown available. 

Plus the popup itself can be appended to other elements than body - see `container` attribute in [v3 documentation](https://cookieconsent.insites.com/documentation/javascript-api/).
