### ISSUE TITLE
Can CookieConsent gray out the rest of the screen?

### ISSUE THREAD

**Issue by rhires** [insites/cookieconsent#514]
Before I go with an additional script to handle this, I wonder if cookieconsent is able to gray out the rest of the screen until the user selects the "I accept cookies" option. The docs say that disabling cookies until the user accepts is possible, but I just want the rest of the screen inactive until the user says that they will accept cookies.

**Comment by Shuyinsan** [comment]
The cookieconsent code has the check to see if the user has accepted or denied the cookies.

You could word of that and write some custom javascript that displays a overlay when the cookieconsent.status is refused or nonexistent. If it is accepted then we don’t show the overlay. 

Basically you would do the same as the cookie bar itself.

**Comment by rhires** [comment]
Yeah. I went ahead with my custom script and CSS, and it's fine.
