### ISSUE TITLE
How to specify multiple domains

### ISSUE THREAD

**Issue by rubyji** [insites/cookieconsent#515]
For development purposes I'd like to be able to set the pop-up to work on both `.mydomain.org` and `.mystagingsite.com`. What would be the correct syntax for this in the script?

**Comment by rubyji** [comment]
In case anyone also has this question, I figured it out. 

`	cookie: {
		domain: "local.site",
		domain: "dev.site",
		domain: "production.site",
		domain: "etc",
	},`

**Comment by jansotola** [comment]
But if you have a pair of _domain_ and _subdomain_ (like `example.com` and `www.example.com`), use the top one only: 

```
	cookie: {
		domain: "example.com",
	},
```
