### ISSUE TITLE
Add option to set link to open in a new window

### ISSUE THREAD

**Issue by realcookielover** [insites/cookieconsent#52]
Hello,

I know there was already an issue and it is stated, that this function is already included in the cookieconsent2, but somehow it doesn't work on my website.

I uploaded the latest .js and .css file on my domain and included it via <script src="cookieconsent.js"></script> in the head tag of the .php file.

Everything works, but when I click on "Learn more" the link always open in the current tab, which is not really beneficial because I'm linking to another domain.

I'm a beginner, so if someone could help me, I would really appreciate it.

Thanks in advance!

**Comment by Wanabo** [comment]
Did you downloaded the latest version from Github? About 15 days ago this feature was added.
Search your cookieconsent.js for target="_blank" around line 242. If not present download from github again.

**Comment by realcookielover** [comment]
Thank you for your fast replay. I downloaded it today and yes, target="_blank" is in the code like you mentioned. I also tried it with the code from the wizard, but it doesn't work either.
That's why I feel so at loss...

**Comment by aish1550** [comment]
Hi guys, firstly, just wanted to say thank you for the work you have done on this! it's awesome. Is there any chance this issue could be re-looked into? I believe the default the link with class "cc_logo" has a target 'blank' but not the learn more link. This is purely quite selfish but I think a lot of people may benefit from a object of some sort that could be set with a boolean of True or False value and that would produce the link with a target blank or not depending on whether they have specified that True parameter. 

This would also mean that the user may be directed to perhaps a universal home link Privacy Policy if they are managing multiple micro-sites.

**Comment by alexmorleyfinch** [comment]
This option was added in later versions of CookieConsent V2.

However, CookieConsent V3 is a lot more configurable. All the HTML can be modified to suit your needs
