### ISSUE TITLE
error thrown when using code to disable cookies: 'onInitialise: function(status) {...'

### ISSUE THREAD

**Issue by oliv-j** [insites/cookieconsent#520]
I have tried to add the cookie disable code using the [provided callback hooks script](https://cookieconsent.insites.com/documentation/disabling-cookies/):

Safari throws error:
> SyntaxError: Function statements must have a name

Chrome error:

> Uncaught SyntaxError: Unexpected token (`

The only other js on my [test page](https://graduate.unipartconsulting.com/test/) is the google tag manager code which is working properly.

My Code:
```
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js" ></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#4f4b4c",
      "text": "#e5e5e8"
    },
    "button": {
      "background": "#0099cc",
      "text": "#ffffff"
    }
  },
  "theme": "edgeless",
  "type": "opt-out",
  "content": {
    "href": "https://graduate.unipartconsulting.com/Privacy-Notice-Job-Applicants.pdf"
  }
})});
	
onInitialise: function(status) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    window['ga-disable-GA_TRACKING_ID'] = false;
  }
  if (type == 'opt-out' && !didConsent) {
    window['ga-disable-GA_TRACKING_ID'] = true;
  }
},
 
onStatusChange: function(status, chosenBefore) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    window['ga-disable-GA_TRACKING_ID'] = false;
  }
  if (type == 'opt-out' && !didConsent) {
    window['ga-disable-GA_TRACKING_ID'] = true;
  }
},
 
onRevokeChoice: function() {
  var type = this.options.type;
  if (type == 'opt-in') {
    window['ga-disable-GA_TRACKING_ID'] = true;
  }
  if (type == 'opt-out') {
    window['ga-disable-GA_TRACKING_ID'] = false;
  }
},

</script>
```

**Comment by arunrajahgopal** [comment]
@oliv-j Add it within the initialize function like below
![image](https://user-images.githubusercontent.com/24190571/54833490-7f9cf200-4cbe-11e9-8aea-4f9c9974addc.png)

Your final version should look like 
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js" ></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#4f4b4c",
      "text": "#e5e5e8"
    },
    "button": {
      "background": "#0099cc",
      "text": "#ffffff"
    }
  },
  "theme": "edgeless",
  "type": "opt-out",
  "content": {
    "href": "https://graduate.unipartconsulting.com/Privacy-Notice-Job-Applicants.pdf"
  },
onInitialise: function(status) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    window['ga-disable-GA_TRACKING_ID'] = false;
  }
  if (type == 'opt-out' && !didConsent) {
    window['ga-disable-GA_TRACKING_ID'] = true;
  }
},
 
onStatusChange: function(status, chosenBefore) {
  var type = this.options.type;
  var didConsent = this.hasConsented();
  if (type == 'opt-in' && didConsent) {
    window['ga-disable-GA_TRACKING_ID'] = false;
  }
  if (type == 'opt-out' && !didConsent) {
    window['ga-disable-GA_TRACKING_ID'] = true;
  }
},
 
onRevokeChoice: function() {
  var type = this.options.type;
  if (type == 'opt-in') {
    window['ga-disable-GA_TRACKING_ID'] = true;
  }
  if (type == 'opt-out') {
    window['ga-disable-GA_TRACKING_ID'] = false;
  }
},
})});
	


</script>

**Comment by oliv-j** [comment]
Thanks - that seems to works great.
