### ISSUE TITLE
Set window.cookie_consent via lambda function, allowing conditional execution of plugins

### ISSUE THREAD

**Issue by mxdpeep** [insites/cookieconsent#57]
you should set a global variable window.cookie_consent to TRUE or FALSE within the lambda function, so it is possible to check the value during the page load, and disable trackers if it is NOT set to TRUE!

it is a violation of EU rights to monitor the first page load if the "victim" has not agreed first :santa:

as for the silktide.com page, this is cookie set BEFORE I agree:

_ga=GA1.2.660093563.1440424277
_gat=1

and the consent code is BELOW the Google Analytics code, that's also BAD = I assume the best position is within the HEAD section

**Comment by oliveremberton** [comment]
We're considering this, but just to clarify this:

> "it is a violation of EU rights to monitor the first page load if the "victim" has not agreed first"

The law various from country to country in the EU. For the UK at least, this isn't the case, but other countries (notably France and Greece) are more restrictive.

**Comment by janwidmer** [comment]
A conditional execution  would be great, since I have a multi-country site and the plugin will be active on some sites, but not on all.. For now, I am setting the JS Options inline, but it would be great, if I could move the options and initialization of the cookie plugin to my js code..

**Comment by alexmorleyfinch** [comment]
This is now possible in CookieConsent V3, as it has location and cookie law features built into it.

There are a few callback functions that can be used to enable/disable cookies.
