### ISSUE TITLE
Add option to auto accept on scroll (implied consent if you keep browsing the website)

### ISSUE THREAD

**Issue by sharoncreech** [insites/cookieconsent#58]
Is there any option or way to modify code to allow implied consent where by the message is removed automatically if you keep browsing the website?

Also is there way to show cookie only on first visit. If you browse to another page of the website cookie will be automatically accepted?

Thanks

**Comment by collimarco** [comment]
+1

**Comment by alexmorleyfinch** [comment]
This feature does not exist in CookieConsent V2. It does however exist in CookieConsent V3. There is an option called `dismissOnScroll`. Simply set it to the scroll value that it must exceed before the popup is dismissed.

I.E. `dismissOnScroll: 1000`

If the `scrollTop` of the parent container exceeds 1000, then the popup is dismissed.
