### ISSUE TITLE
Give a CSS style to "OK" link on focus for accessibility

### ISSUE THREAD

**Issue by keul** [insites/cookieconsent#59]
Right now there's only a CSS style for the `a:active` selector.
Accessing the cookiconsent section using the keyboard and focusing on the accept button will not change the button color or highlight the status in any way.

**Comment by oliveremberton** [comment]
@piiupilt is this an issue with Cookie Consent 3?

**Comment by piiupilt** [comment]
Fixed in #166.
Included in release [3.0.2](https://github.com/insites/cookieconsent/releases/tag/3.0.2)
