### ISSUE TITLE
Add some WAI-ARIA attributes for accessibility

### ISSUE THREAD

**Issue by keul** [insites/cookieconsent#60]
Users using a screen reader will not see the cookie consent as it's generated using JavaScript ater DOM load.
WAI-ARIA attributes can help:

    <div class="cc_banner-wrapper  aria-live="assertive" role="alert" {{containerClasses}}">

**Comment by piiupilt** [comment]
Additional ARIA tags added with #166.
Included in release [3.0.2](https://github.com/insites/cookieconsent/releases/tag/3.0.2)
