### ISSUE TITLE
Sometimes readyState 'complete' can be "too late"

### ISSUE THREAD

**Issue by keul** [insites/cookieconsent#61]
See https://github.com/silktide/cookieconsent2/blob/eca71f6a2cfa24c724ba4744e2453ab8d853383f/cookieconsent.js#L343

There's some situation where waiting for `document.readyState=='complete'` can be a long time. If something in the fame, like an `iframe` hang the connection forever, the banner is not displayed.

My suggestion is to change this to:

    if (!initialized && document.readyState == 'interactive')

This will only wait for the `DOMContentLoaded` event.

**Comment by alexmorleyfinch** [comment]
Thanks for your suggestion, although the change cannot be made now as CookieConsent V2 is no longer supported.

CookieConsent V3 does not assume that the user wants to run the script on "document ready". The tool can be initialised at any time, so this is no longer an issue.
