### ISSUE TITLE
Issues with banner not showing on some mobile / tablet devices

### ISSUE THREAD

**Issue by ubound** [insites/cookieconsent#62]
Thank you for this awesome code! It works perfectly on my desktop, but it seems like it doesn't show on my Samsung mobile and on iPad. Is there any issues with mobiles and tablets?

**Comment by cvogl** [comment]
I had the same issue on one of our sites (as well as on silktide.com).

The cause: 
render was never executed as loadTheme's callback function (line 260). I worked around by calling render without waiting for the loading of the theme.

Maybe it helps you working around, too.

**Comment by sharoncreech** [comment]
cvogl,

Maybe you can share the code for this issue with us. I've tried with Lumia 920 and it does not show on mobile. From other side testing with browsers emulation addons within Chrome and Firefox does not show any issue.

But there seems to be really issue. Do not know of developer are aware of this issue but if someone have fix for mobile devices then it would be more than appreciated to share it with us.

Thanks

**Comment by eonardol** [comment]
I have the same issue only on a specific page of my site.
I have solved replacing [this block](https://github.com/silktide/cookieconsent2/blob/master/cookieconsent.js#L343-L353) with this (very bad) piece of code:

    $(document).ready(function(){
      cookieconsent.init();
      window[OPTIONS_UPDATER] = Util.bind(cookieconsent.setOptionsOnTheFly, cookieconsent);
    });

The `document.readyState` never seems to become `complete`

**Comment by alexmorleyfinch** [comment]
Unfortunately there is no simple fix for mobile styles in CookieConsent V2. A fix would include having to write and test your own CSS, which I understand is not a great solution.

CookieConsent V3 has been designed from the ground up to work with modern browsers, and to work on as many devices as possible
