### ISSUE TITLE
For better accessibility, swap order of text and button inside banner

### ISSUE THREAD

**Issue by keul** [insites/cookieconsent#63]
Using a screen reader the first item read inside the banner is the accept button, which is werd, then a user can read the text.
Swapping that order will enhance accessibility of the plugin.

A suggestion: you can remove the `float: left` of the button then position it in an absolute way:

    .cc_container .cc_btn {
        position: absolute;
        right: 10px;
    }

**Comment by alexmorleyfinch** [comment]
The reason the button is first was for display issues on older machines that we wanted to support.

In CookieConsent V3, this is no longer an issue, as it only supports "modern" browsers.
