### ISSUE TITLE
Set custom cookie name 

### ISSUE THREAD

**Issue by mxdpeep** [insites/cookieconsent#65]
allow cookie name to be changed via options

**Comment by oliveremberton** [comment]
We might consider this, but can I ask for a use case? It's not immediately obviously why we'd benefit from this feature.

**Comment by GSPP** [comment]
This is useful in order to have less network traffic and less web log space usage by configuring a shorter cookie name. Upload speed is often very limited (mobile networks, rural areas, 3rd world countries, ...).

Also, I would request that the cookie value is not set to "yes" which also wastes space. Doesn't it suffice to create the cookie with an empty value? Or, use "1".

@oliveremberton

**Comment by kulnor** [comment]
Another benefit is to be able to reuse the same script for other consents / messages that we want the user to acknowledge.

**Comment by alexPerezLillo** [comment]
Another benefit is to be able to set a common format for all the cookies that your page sets, and then in a frontend cache like varnish dismiss all cookies with the same format.

Thank's.

**Comment by mwillerich** [comment]
For me the main legal use-case for this is that when you change what you're setting cookies for, you should re-request the cookie usage consent. 
So, imagine I build a holding page and the cookie is for Google Analytics. You create the message "We're using cookies to analyse our web traffic".
Now you've continued to develop the site, and people can now log in, and the cookie is used to store this state. If you want to be super-legal, you need to re-request the cookie usage, as the usage is now analytics _and_ preservation of state on the site.

**Comment by alexmorleyfinch** [comment]
The cookie name can be easily changed in CookieConsent V3. You can use the `cookie` option.

```
cookieconsent.initialise({
  cookie: {
    name: 'my_own_personal_cookie_name'
  }
})
```

https://cookieconsent.insites.com/documentation/javascript-api/#cookie_options
