### ISSUE TITLE
Detect when cookies are disabled in browser via navigator.cookieEnabled, hide banner automatically

### ISSUE THREAD

**Issue by archerbarrie** [insites/cookieconsent#93]
If the user disables cookies the banner still appears saying the website uses cookies. Either the banner should not appear or it should say the website cannot be used (as a developer option). Disabled cookies can be tested with navigator.cookieEnabled

**Comment by oliveremberton** [comment]
Makes sense, we'll take a look at this.

**Comment by alexmorleyfinch** [comment]
Thanks to this suggestion, CookieConsent V3 does not initialise if consent can be implied in other ways. E.G. If `cookieEnabled` or `CookiesOK` exists
