### ISSUE TITLE
Add option to automatically dismiss banner after a fixed number of seconds

### ISSUE THREAD

**Issue by bauhausweb** [insites/cookieconsent#98]
I saw that in version 1 an implicit consent was possible. Why did it disappear in v2? 
It would be nice if one could set a timer in seconds when the banner should disappear, implying an implicit consent of the visitor.

**Comment by alexmorleyfinch** [comment]
CookieConsent V2 does not have this by default, but CookieConsent V3 does.

There is now an option called `dismissOnTimeout` which will automatically dismiss the popup after the specified number of milliseconds.
