### ISSUE TITLE
Reload after dismiss

### ISSUE THREAD

**Issue by MaamuT** [insites/cookieconsent#99]
Hi all,

Sorry for my funny english, i'm french and i don't speak very well…

In my website, i wanted the page reloads after accepting, but i'm not a big develloper…

Well, i just added this followed inline into the cookieconsent-min.js ```window.location.reload();```

Before ```s.setCookie(n,"yes",this.options.expiryDays,this.options.domain,this.options.path);```

After ```s.setCookie(n,"yes",this.options.expiryDays,this.options.domain,this.options.path);window.location.reload();```

I think is not a good parctice, but it's work ;)

But i think this option can added to the script, maybe, if you want ;)

**Comment by oliveremberton** [comment]
That should work, but can I ask why you'd want to reload after dismissing?

**Comment by MaamuT** [comment]
In my case, it's for displaying my customer login form, after refresh and cookie verification.

The form should be displayed if cookies are enabled and accepted.

It's a rule for my customer, and this script is the more simple i have found who correspond.

It's not the original task, but for me, it's good.

My submission is just an information ;)

**Comment by alexmorleyfinch** [comment]
In CookieConsent V3, this functionality could be easily added in a callback. I.E.

```
cookieconsent.initialise({
  onStatusChange: function(status) {
    if (this.hasAnswered() && this.hasConsented()) {
      window.location.reload();
    }
  },
});
```
